import { describe, expect, it } from "vitest";
import {
	PLATFORM_CONNECT_METHODS,
	PLATFORM_CONNECT_SERVICES,
	PLATFORM_HTTP_ROUTES,
	platformConnectMethodPath,
	platformConnectServicePath,
} from "../../src/platform/core-services.js";

describe("Platform core service contract names", () => {
	it("pins Connect service and method paths used by Maestro clients", () => {
		expect(
			platformConnectMethodPath(
				PLATFORM_CONNECT_METHODS.agentRuntime.handleTrigger,
			),
		).toBe("/agentruntime.v1.AgentRuntimeService/HandleTrigger");
		expect(
			platformConnectMethodPath(
				PLATFORM_CONNECT_METHODS.agentRuntime.claimNextRun,
			),
		).toBe("/agentruntime.v1.AgentRuntimeService/ClaimNextRun");
		expect(
			platformConnectMethodPath(PLATFORM_CONNECT_METHODS.agents.delegate),
		).toBe("/agents.v1.AgentService/Delegate");
		expect(
			platformConnectMethodPath(
				PLATFORM_CONNECT_METHODS.agents.resolveDelegation,
			),
		).toBe("/agents.v1.AgentService/ResolveDelegation");
		expect(
			platformConnectMethodPath(
				PLATFORM_CONNECT_METHODS.agentRuntime.recordRunStep,
			),
		).toBe("/agentruntime.v1.AgentRuntimeService/RecordRunStep");
		expect(
			platformConnectMethodPath(PLATFORM_CONNECT_METHODS.agentRuntime.waitRun),
		).toBe("/agentruntime.v1.AgentRuntimeService/WaitRun");
		expect(platformConnectServicePath(PLATFORM_CONNECT_SERVICES.prompts)).toBe(
			"/prompts.v1.PromptService",
		);
		expect(
			platformConnectMethodPath(PLATFORM_CONNECT_METHODS.prompts.resolve),
		).toBe("/prompts.v1.PromptService/Resolve");
		expect(
			platformConnectMethodPath(PLATFORM_CONNECT_METHODS.meter.ingestWideEvent),
		).toBe("/meter.v1.MeterService/IngestWideEvent");
		expect(
			platformConnectMethodPath(PLATFORM_CONNECT_METHODS.meter.queryWideEvents),
		).toBe("/meter.v1.MeterService/QueryWideEvents");
		expect(
			platformConnectMethodPath(
				PLATFORM_CONNECT_METHODS.meter.getEventDashboard,
			),
		).toBe("/meter.v1.MeterService/GetEventDashboard");
		expect(
			platformConnectMethodPath(
				PLATFORM_CONNECT_METHODS.approvals.requestApproval,
			),
		).toBe("/approvals.v1.ApprovalService/RequestApproval");
		expect(
			platformConnectMethodPath(
				PLATFORM_CONNECT_METHODS.governance.evaluateAction,
			),
		).toBe("/governance.v1.GovernanceService/EvaluateAction");
		expect(
			platformConnectMethodPath(
				PLATFORM_CONNECT_METHODS.connectors.listConnections,
			),
		).toBe("/connectors.v1.ConnectorService/ListConnections");
		expect(
			platformConnectMethodPath(
				PLATFORM_CONNECT_METHODS.connectors.setSourceOfTruthPolicy,
			),
		).toBe("/connectors.v1.ConnectorService/SetSourceOfTruthPolicy");
		expect(
			platformConnectMethodPath(
				PLATFORM_CONNECT_METHODS.llmGateway.createMessage,
			),
		).toBe("/llmgateway.v1.GatewayService/CreateMessage");
		expect(
			platformConnectMethodPath(
				PLATFORM_CONNECT_METHODS.remoteRunner.createRunnerSession,
			),
		).toBe("/remoterunner.v1.RemoteRunnerService/CreateRunnerSession");
		expect(
			platformConnectMethodPath(
				PLATFORM_CONNECT_METHODS.remoteRunner.mintAttachToken,
			),
		).toBe("/remoterunner.v1.RemoteRunnerService/MintAttachToken");
		expect(
			platformConnectMethodPath(
				PLATFORM_CONNECT_METHODS.remoteRunner.getStatus,
			),
		).toBe("/remoterunner.v1.RemoteRunnerService/GetStatus");
		expect(
			platformConnectMethodPath(
				PLATFORM_CONNECT_METHODS.maestroTimeline.listRunTimeline,
			),
		).toBe("/maestro.v1.MaestroTimelineService/ListRunTimeline");
		expect(
			platformConnectMethodPath(
				PLATFORM_CONNECT_METHODS.toolexecution.executeTool,
			),
		).toBe("/toolexecution.v1.ToolExecutionService/ExecuteTool");
		expect(
			platformConnectMethodPath(
				PLATFORM_CONNECT_METHODS.toolexecution.resumeToolExecution,
			),
		).toBe("/toolexecution.v1.ToolExecutionService/ResumeToolExecution");
		expect(
			platformConnectMethodPath(
				PLATFORM_CONNECT_METHODS.toolexecution.recordToolExecutionOutput,
			),
		).toBe("/toolexecution.v1.ToolExecutionService/RecordToolExecutionOutput");
		expect(
			platformConnectMethodPath(
				PLATFORM_CONNECT_METHODS.fermata.createTestSuite,
			),
		).toBe("/fermata.v1.FermataService/CreateTestSuite");
		expect(
			platformConnectMethodPath(
				PLATFORM_CONNECT_METHODS.fermataExecution.runTestSuite,
			),
		).toBe("/fermata.v1.FermataExecutionService/RunTestSuite");
	});

	it("keeps durable memory on the existing HTTP JSON route", () => {
		expect(PLATFORM_HTTP_ROUTES.memory.recall).toBe("/v1/memories/recall");
	});

	it("pins identity HTTP routes used by EvalOps login and delegation", () => {
		expect(PLATFORM_HTTP_ROUTES.identity.authGoogleStart).toBe(
			"/v1/auth/google/start",
		);
		expect(PLATFORM_HTTP_ROUTES.identity.tokenRefresh).toBe(
			"/v1/tokens/refresh",
		);
		expect(PLATFORM_HTTP_ROUTES.identity.tokenRevoke).toBe("/v1/tokens/revoke");
		expect(PLATFORM_HTTP_ROUTES.identity.delegationTokens).toBe(
			"/v1/delegation-tokens",
		);
	});
});
