import type { IncomingMessage } from "node:http";
import type { AgentEvent, AssistantMessage } from "../../agent/types.js";
import { createLogger } from "../../utils/logger.js";
import {
	resolveUsageAgentId,
	resolveUsageWorkspaceId,
} from "../usage-analytics/recorder.js";
import { getComplianceService } from "./service.js";
import type {
	AgentActionInput,
	ComplianceJsonValue,
	GovernanceEvaluationInput,
} from "./types.js";

const logger = createLogger("compliance:recorder");

type ToolExecutionEndEvent = Extract<
	AgentEvent,
	{ type: "tool_execution_end" }
>;

function costMetadata(
	message: AssistantMessage,
): Record<string, ComplianceJsonValue> {
	const usage = message.usage;
	if (!usage) return {};
	return {
		inputTokens: usage.input,
		outputTokens: usage.output,
		cacheReadTokens: usage.cacheRead,
		cacheWriteTokens: usage.cacheWrite,
		totalTokens:
			usage.input + usage.output + usage.cacheRead + usage.cacheWrite,
		...(typeof usage.cost?.total === "number"
			? { costUsd: usage.cost.total }
			: {}),
	};
}

export function trackComplianceAgentAction(input: AgentActionInput): void {
	try {
		getComplianceService().trackAgentAction(input);
	} catch (error) {
		logger.warn("Compliance action tracking failed", {
			error: error instanceof Error ? error.message : String(error),
			type: input.type,
			workspaceId: input.workspaceId,
			agentId: input.agentId,
		});
	}
}

export function trackComplianceGovernanceEvaluation(
	input: GovernanceEvaluationInput,
): void {
	try {
		getComplianceService().trackGovernanceEvaluation(input);
	} catch (error) {
		logger.warn("Compliance governance tracking failed", {
			error: error instanceof Error ? error.message : String(error),
			actionType: input.actionType,
			workspaceId: input.workspaceId,
			agentId: input.agentId,
		});
	}
}

export function recordComplianceToolAction(params: {
	req: IncomingMessage;
	event: ToolExecutionEndEvent;
	sessionId?: string;
	subject?: string;
}): void {
	const { event } = params;
	const sessionId = params.sessionId;
	trackComplianceAgentAction({
		actionId: event.toolCallId,
		workspaceId: resolveUsageWorkspaceId(params.req),
		agentId: resolveUsageAgentId(params),
		type: "tool_call",
		status: event.isError ? "failure" : "success",
		resource: event.toolName,
		description:
			event.summaryLabel ??
			`Tool ${event.toolName} ${event.isError ? "failed" : "completed"}`,
		metadata: {
			toolCallId: event.toolCallId,
			toolName: event.toolName,
			...(event.displayName ? { displayName: event.displayName } : {}),
			...(event.summaryLabel ? { summaryLabel: event.summaryLabel } : {}),
			...(sessionId ? { sessionId } : {}),
		},
	});
}

export function recordComplianceAssistantAction(params: {
	req: IncomingMessage;
	message: AssistantMessage;
	sessionId?: string;
	subject?: string;
}): void {
	const { message } = params;
	const occurredAt =
		typeof message.timestamp === "number" && Number.isFinite(message.timestamp)
			? new Date(message.timestamp)
			: new Date();
	const sessionId = params.sessionId;
	trackComplianceAgentAction({
		workspaceId: resolveUsageWorkspaceId(params.req),
		agentId: resolveUsageAgentId(params),
		type: "llm_inference",
		status: "success",
		resource: message.model,
		timestamp: occurredAt,
		description: `LLM completion generated by ${message.provider}/${message.model}`,
		metadata: {
			provider: message.provider,
			model: message.model,
			...(sessionId ? { sessionId } : {}),
			...costMetadata(message),
		},
	});
}
