/**
 * Transport Utilities
 * Pure functions for credential resolution, cost calculation, audit logging,
 * and PII policy formatting. Zero class coupling.
 */

import { getEnvVarsForProvider } from "../../providers/api-keys.js";
import type { AuthCredential } from "../../providers/auth.js";
import { sanitizeLogMessage } from "../../safety/context-firewall.js";
import type { Clock } from "../../utils/clock.js";
import { createLogger } from "../../utils/logger.js";
import type { WorkflowStateSnapshot } from "../action-approval.js";
import type { ToolCall, ToolResultMessage } from "../types.js";

const logger = createLogger("transport");

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

export type SessionTokenCounter = (sessionId: string) => Promise<number | null>;

export type ToolAuditLogger = (entry: {
	toolName: string;
	args: Record<string, unknown>;
	status: "success" | "failure" | "denied";
	durationMs: number;
	error?: string;
}) => Promise<void>;

// ─────────────────────────────────────────────────────────────────────────────
// Text Extraction
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Extract text content from a message content field.
 * Handles both string format and array format (multimodal messages).
 *
 * This is critical for semantic safety analysis - without this, multimodal
 * messages would bypass intent extraction and skip the semantic judge.
 */
export function extractTextFromContent(
	content: string | { type: string; text?: string }[] | undefined,
): string | undefined {
	if (!content) return undefined;

	// Simple string content
	if (typeof content === "string") {
		return content;
	}

	// Array content (multimodal) - extract text from all text blocks
	if (Array.isArray(content)) {
		const textParts: string[] = [];
		for (const block of content) {
			if (
				typeof block === "object" &&
				block !== null &&
				block.type === "text" &&
				typeof block.text === "string"
			) {
				textParts.push(block.text);
			}
		}
		return textParts.length > 0 ? textParts.join("\n") : undefined;
	}

	return undefined;
}

// ─────────────────────────────────────────────────────────────────────────────
// Credential Resolution
// ─────────────────────────────────────────────────────────────────────────────

export function resolveEnvCredential(
	provider: string,
): AuthCredential | undefined {
	const vars = getEnvVarsForProvider(provider);
	for (const name of vars) {
		const value = process.env[name];
		if (!value) continue;
		const isAnthropicOAuth =
			provider === "anthropic" && name === "ANTHROPIC_OAUTH_TOKEN";
		return {
			provider,
			token: value,
			type: isAnthropicOAuth ? "anthropic-oauth" : "api-key",
			source: isAnthropicOAuth ? "anthropic_oauth_env" : "env",
			envVar: name,
		};
	}
	return undefined;
}

// ─────────────────────────────────────────────────────────────────────────────
// Audit Logging
// ─────────────────────────────────────────────────────────────────────────────

/** Sensitive tools that should be logged for audit purposes */
export const SENSITIVE_TOOLS = new Set([
	"bash",
	"background_tasks",
	"write",
	"edit",
	"git_cmd",
	"gh_pr",
	"gh_issue",
	"websearch",
	"webfetch",
]);

export async function logToolExecutionAudit(
	auditLogger: ToolAuditLogger | undefined,
	toolName: string,
	args: Record<string, unknown>,
	status: "success" | "failure" | "denied",
	durationMs: number,
	error?: string,
): Promise<void> {
	// Only log sensitive tools and only if enterprise features are available
	if (!SENSITIVE_TOOLS.has(toolName) || !auditLogger) {
		return;
	}

	try {
		const sanitizedError = error ? sanitizeLogMessage(error) : undefined;
		await auditLogger({
			toolName,
			args,
			status,
			durationMs,
			error: sanitizedError,
		});
	} catch (err) {
		// Log audit failures but fail open (allow legitimate use) per user feedback
		logger.error(
			"Failed to log tool execution",
			err instanceof Error ? err : new Error(String(err)),
			{ toolName },
		);
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Cost Calculation
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Calculate API Cost from Token Usage
 *
 * Computes the total cost of an LLM request based on token counts and
 * per-token pricing. Costs are specified in dollars per million tokens
 * (the standard industry format), so we divide by 1,000,000.
 *
 * ## Cost Components
 *
 * - **Input tokens**: Tokens in the prompt (system prompt + messages + tools)
 * - **Output tokens**: Tokens generated by the model
 * - **Cache read**: Tokens loaded from prompt cache (usually cheaper)
 * - **Cache write**: Tokens written to prompt cache (may have different pricing)
 *
 * ## Example Calculation
 *
 * For Claude Sonnet with input=$3/M, output=$15/M:
 * - 10,000 input tokens = 10000 * 3 / 1,000,000 = $0.03
 * - 1,000 output tokens = 1000 * 15 / 1,000,000 = $0.015
 * - Total = $0.045
 *
 * @param usage - Token counts from the API response
 * @param costConfig - Per-million-token pricing for each usage type
 * @returns Total cost in dollars
 */
export function calculateCost(
	usage: {
		input?: number;
		output?: number;
		cacheRead?: number;
		cacheWrite?: number;
	},
	costConfig: {
		input: number;
		output: number;
		cacheRead: number;
		cacheWrite: number;
	},
): number {
	// Each cost component: (tokens * dollars_per_million) / 1_000_000
	const inputCost = ((usage.input || 0) * costConfig.input) / 1_000_000;
	const outputCost = ((usage.output || 0) * costConfig.output) / 1_000_000;
	const cacheReadCost =
		((usage.cacheRead || 0) * costConfig.cacheRead) / 1_000_000;
	const cacheWriteCost =
		((usage.cacheWrite || 0) * costConfig.cacheWrite) / 1_000_000;

	return inputCost + outputCost + cacheReadCost + cacheWriteCost;
}

// ─────────────────────────────────────────────────────────────────────────────
// PII Policy Helpers
// ─────────────────────────────────────────────────────────────────────────────

export function formatPendingPii(snapshot: WorkflowStateSnapshot): string {
	if (snapshot.pendingPii.length === 0) {
		return "(none tracked)";
	}
	return snapshot.pendingPii
		.map(
			(artifact) =>
				`• ${artifact.label} (artifact: ${artifact.id}, source: ${artifact.sourceToolCallId})`,
		)
		.join("\n");
}

export function buildPiiPolicyResult(
	toolCall: ToolCall,
	snapshot: WorkflowStateSnapshot,
	clock: Clock,
): ToolResultMessage {
	const artifactSummary = formatPendingPii(snapshot);
	const orphanedSummary = snapshot.orphanedRedactions.length
		? `Orphaned redaction attempts: ${snapshot.orphanedRedactions.join(", ")}`
		: "";
	const guidanceText = `Policy block: unredacted PII is still pending, so "${toolCall.name}" cannot run.\n\nArtifacts requiring redaction:\n${artifactSummary}\n\n${orphanedSummary ? `${orphanedSummary}\n\n` : ""}Next steps: run \`redact_transcript\` (or your workflow's redaction tool) for each artifact above, then retry the egress action.`;
	return {
		role: "toolResult",
		toolCallId: toolCall.id,
		toolName: toolCall.name,
		content: [{ type: "text", text: guidanceText }],
		isError: true,
		timestamp: clock.now(),
	};
}
