apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maestro.fullname" . }}
  labels:
    {{- include "maestro.labels" . | nindent 4 }}
{{- $webApiKey := include "maestro.webApiKey" . }}
type: Opaque
{{- if $webApiKey }}
stringData:
  MAESTRO_WEB_API_KEY: {{ $webApiKey | quote }}
{{- else }}
stringData: {}
{{- end }}
