//! Session Entry Type Definitions
//!
//! This module defines the type system for session persistence using the JSONL format.
//! Each entry represents a distinct event in the session timeline and is serialized as
//! a single line in the session file.
//!
//! # Entry Type Hierarchy
//!
//! The [`SessionEntry`] enum is the top-level discriminated union that encompasses all
//! possible event types in a session. It uses serde's `tag` attribute to create a
//! type-discriminated JSON representation.
//!
//! ## Serde Tagged Enum Pattern
//!
//! Each entry is serialized with a `"type"` field that determines its variant:
//! ```json
//! {"type":"session","id":"abc123",...}
//! {"type":"message","timestamp":"2024-01-15T10:30:00Z",...}
//! {"type":"session_meta","title":"My Session",...}
//! ```
//!
//! The `#[serde(tag = "type", rename_all = "snake_case")]` attribute automatically:
//! - Adds a `"type"` discriminator field to each JSON object
//! - Converts variant names from `PascalCase` to `snake_case` (Session -> "session")
//! - Enables efficient deserialization by reading the type field first
//!
//! # Message Format
//!
//! Messages follow a role-based structure compatible with AI provider APIs:
//!
//! ## User Messages
//! ```json
//! {
//!   "role": "user",
//!   "content": "What is Rust?",
//!   "timestamp": 1705318200000
//! }
//! ```
//!
//! ## Assistant Messages
//! ```json
//! {
//!   "role": "assistant",
//!   "content": [
//!     {"type": "text", "text": "Rust is a systems programming language..."},
//!     {"type": "thinking", "text": "Consider explaining memory safety..."}
//!   ],
//!   "usage": {
//!     "input": 150,
//!     "output": 200,
//!     "cacheRead": 100,
//!     "cacheWrite": 50
//!   },
//!   "timestamp": 1705318201000
//! }
//! ```
//!
//! ## Tool Result Messages
//! ```json
//! {
//!   "role": "toolResult",
//!   "tool_call_id": "call_xyz",
//!   "tool_name": "read_file",
//!   "content": "File contents here...",
//!   "is_error": false,
//!   "timestamp": 1705318202000
//! }
//! ```
//!
//! # Content Block Types
//!
//! Assistant messages contain structured content blocks:
//!
//! - **Text**: Plain text responses
//! - **Thinking**: Internal reasoning (extended thinking feature)
//! - **`ToolCall`**: Function calls to external tools
//! - **Image**: Base64-encoded images
//!
//! # Metadata and Configuration
//!
//! Sessions track configuration changes over time:
//!
//! ## Session Metadata
//! User-facing metadata for organization:
//! - `title`: Display name for the session
//! - `summary`: Brief description of the conversation
//! - `tags`: Categorization labels
//! - `favorite`: Pin important sessions
//!
//! ## Configuration Changes
//! Tracked as separate entries:
//! - `ThinkingLevelChange`: Adjustments to extended thinking budget
//! - `ModelChange`: Switching between AI models mid-session
//! - `Compaction`: Context window compression events
//!
//! # Token Usage Tracking
//!
//! The [`TokenUsage`] struct tracks API consumption with cache awareness:
//! - `input`: Tokens sent to the model
//! - `output`: Tokens generated by the model
//! - `cache_read`: Tokens served from prompt cache (discounted)
//! - `cache_write`: Tokens written to cache for future use
//!
//! Cost is calculated per-token based on model pricing.
//!
//! # Serialization Details
//!
//! ## Optional Field Handling
//!
//! Fields marked with `#[serde(skip_serializing_if = "Option::is_none")]` are omitted
//! from JSON when `None`, reducing file size:
//! ```rust,ignore
//! #[derive(Serialize)]
//! struct Example {
//!     required: String,
//!     #[serde(skip_serializing_if = "Option::is_none")]
//!     optional: Option<String>,  // Omitted if None
//! }
//! ```
//!
//! ## Default Values
//!
//! Fields marked with `#[serde(default)]` use `Default::default()` when missing during
//! deserialization, enabling backward compatibility:
//! ```rust,ignore
//! #[derive(Deserialize)]
//! struct Example {
//!     #[serde(default)]
//!     new_field: bool,  // Defaults to false for old files
//! }
//! ```
//!
//! ## Field Renaming
//!
//! JavaScript-style camelCase is preserved for API compatibility:
//! ```rust,ignore
//! #[derive(Serialize)]
//! struct TokenUsage {
//!     #[serde(rename = "cacheRead")]
//!     cache_read: u64,  // Serializes as "cacheRead"
//! }
//! ```
//!
//! # Rust Type System Features
//!
//! ## Newtype Pattern for Type Safety
//!
//! String fields use owned `String` types rather than references because session data
//! must outlive the file read operation. This requires allocating owned data.
//!
//! ## Enum Variants with Data
//!
//! The `MessageContent` enum demonstrates Rust's powerful enum variants:
//! ```rust,ignore
//! pub enum MessageContent {
//!     Text(String),           // Tuple variant
//!     Blocks(Vec<ContentBlock>),  // Tuple variant with complex type
//! }
//! ```
//!
//! Serde's `#[serde(untagged)]` attribute makes this serialize as either a plain string
//! or an array, without a type discriminator:
//! ```json
//! "content": "Simple text"
//! // or
//! "content": [{"type":"text","text":"Block text"}]
//! ```
//!
//! # Statistics Aggregation
//!
//! The [`SessionStats`] struct is computed during session reading and not serialized.
//! It aggregates metrics across all message entries for efficient display:
//! ```rust,ignore
//! let stats = SessionStats {
//!     user_messages: 5,
//!     assistant_messages: 5,
//!     tool_calls: 12,
//!     total_input_tokens: 15000,
//!     total_output_tokens: 8000,
//!     total_cost: 0.15,
//! };
//! ```

use super::wire_format_generated::canonical_stop_reason;
use serde::{Deserialize, Deserializer, Serialize, Serializer};
use serde_json::Value;

fn deserialize_tool_result_content<'de, D>(deserializer: D) -> Result<String, D::Error>
where
    D: Deserializer<'de>,
{
    let value = Value::deserialize(deserializer)?;
    Ok(match value {
        Value::String(content) => content,
        Value::Array(blocks) => blocks
            .iter()
            .filter_map(|block| match block {
                Value::Object(object) => object.get("text").and_then(Value::as_str),
                _ => None,
            })
            .collect::<Vec<_>>()
            .join(""),
        Value::Null => String::new(),
        other => other.to_string(),
    })
}

fn serialize_stop_reason<S>(value: &Option<String>, serializer: S) -> Result<S::Ok, S::Error>
where
    S: Serializer,
{
    match value.as_deref() {
        Some(reason) => serializer.serialize_some(canonical_stop_reason(reason)),
        None => serializer.serialize_none(),
    }
}

/// Top-level discriminated union for all session event types.
///
/// Each variant represents a different kind of event that can occur during a session.
/// The `#[serde(tag = "type")]` attribute creates a type-discriminated JSON format where
/// each entry includes a `"type"` field to identify its variant.
///
/// # JSON Representation
///
/// ```json
/// {"type":"session","id":"abc123",...}        // SessionEntry::Session
/// {"type":"message","timestamp":"...",...}     // SessionEntry::Message
/// {"type":"attachment_extract","timestamp":"...",...} // SessionEntry::AttachmentExtract
/// {"type":"thinking_level_change",...}        // SessionEntry::ThinkingLevelChange
/// {"type":"model_change",...}                 // SessionEntry::ModelChange
/// {"type":"session_meta",...}                 // SessionEntry::SessionMeta
/// {"type":"compaction",...}                   // SessionEntry::Compaction
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum SessionEntry {
    /// Session header (always the first entry in a session file).
    ///
    /// Contains session ID, working directory, model configuration, and other
    /// initialization parameters.
    Session(SessionHeader),

    /// A conversation message entry.
    ///
    /// Wraps a timestamped message from user, assistant, or tool execution.
    Message(MessageEntry),

    /// Attachment extraction cache entry.
    ///
    /// Stores extracted text for attachments in append-only fashion.
    AttachmentExtract(AttachmentExtract),

    /// Thinking level configuration change.
    ///
    /// Recorded when the user adjusts the extended thinking budget during a session.
    ThinkingLevelChange(ThinkingLevelChange),

    /// Model switch event.
    ///
    /// Recorded when the user changes to a different AI model mid-session.
    ModelChange(ModelChange),

    /// Session metadata update.
    ///
    /// User-provided information like title, summary, tags, or favorite status.
    SessionMeta(SessionMeta),

    /// Context window compaction event.
    ///
    /// Recorded when the conversation history is summarized to fit within token limits.
    Compaction(CompactionEntry),
}

/// Session initialization parameters (first entry in every session file).
///
/// The header contains all the metadata needed to reconstruct the session context,
/// including the working directory, model configuration, and available tools.
///
/// # Example JSON
///
/// ```json
/// {
///   "type": "session",
///   "id": "550e8400-e29b-41d4-a716-446655440000",
///   "timestamp": "2024-01-15T10:30:00.000Z",
///   "cwd": "/home/user/project",
///   "model": "anthropic/claude-3-5-sonnet-20241022",
///   "thinking_level": "medium",
///   "tools": [
///     {"name": "read", "description": "Read a file"}
///   ]
/// }
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionHeader {
    /// Unique session identifier (typically a UUID v4).
    ///
    /// Used to reference this session in commands and file lookups.
    pub id: String,

    /// ISO 8601 timestamp of session creation.
    ///
    /// Format: `YYYY-MM-DDTHH:MM:SS.sssZ` (e.g., "2024-01-15T10:30:00.000Z")
    pub timestamp: String,

    /// Working directory where the session was started.
    ///
    /// Used to organize sessions by project and resolve relative file paths.
    pub cwd: String,

    /// Model identifier in `provider/model-id` format.
    ///
    /// Examples: "anthropic/claude-3-5-sonnet-20241022", "openai/gpt-4"
    pub model: String,

    /// Detailed model metadata (provider name, context window, etc.).
    ///
    /// Omitted from JSON if None.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "modelMetadata", alias = "model_metadata")]
    pub model_metadata: Option<ModelMetadata>,

    /// Extended thinking budget level.
    ///
    /// Defaults to `Medium` if not specified in the JSON.
    #[serde(default)]
    #[serde(rename = "thinkingLevel", alias = "thinking_level")]
    pub thinking_level: ThinkingLevel,

    /// Custom system prompt override.
    ///
    /// If provided, replaces the default system prompt. Omitted if None.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "systemPrompt", alias = "system_prompt")]
    pub system_prompt: Option<String>,

    /// List of tools available to the assistant.
    ///
    /// Empty list is omitted from JSON to reduce file size.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tools: Vec<ToolInfo>,

    /// Parent session ID if this session was branched.
    ///
    /// Used to track session forks for alternative conversation paths. Omitted if None.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "branchedFrom", alias = "branched_from")]
    pub branched_from: Option<String>,
}

/// Model metadata
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelMetadata {
    pub provider: String,
    #[serde(rename = "modelId", alias = "model_id")]
    pub model_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "providerName", alias = "provider_name")]
    pub provider_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "baseUrl", alias = "base_url")]
    pub base_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "contextWindow", alias = "context_window")]
    pub context_window: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "maxTokens", alias = "max_tokens")]
    pub max_tokens: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
}

/// Tool information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolInfo {
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

/// Extended thinking budget configuration.
///
/// Controls how much the AI model can use its internal reasoning feature (extended
/// thinking) before responding. Higher levels allow more thorough reasoning but
/// consume more tokens and take longer.
///
/// # Token Budgets
///
/// - **Off**: 0 tokens (thinking disabled)
/// - **Minimal**: 1,024 tokens
/// - **Low**: 4,096 tokens
/// - **Medium**: 10,000 tokens (default)
/// - **High**: 20,000 tokens
/// - **Max**: 50,000 tokens
///
/// # Serialization
///
/// Serializes to lowercase strings: "off", "minimal", "low", "medium", "high", "max"
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ThinkingLevel {
    /// Thinking disabled (0 tokens).
    Off,

    /// Minimal thinking budget (1,024 tokens).
    Minimal,

    /// Low thinking budget (4,096 tokens).
    Low,

    /// Medium thinking budget (10,000 tokens) - default level.
    #[default]
    Medium,

    /// High thinking budget (20,000 tokens).
    High,

    /// Maximum thinking budget (50,000 tokens).
    Max,
}

impl ThinkingLevel {
    #[must_use]
    pub fn label(&self) -> &'static str {
        match self {
            ThinkingLevel::Off => "Off",
            ThinkingLevel::Minimal => "Minimal",
            ThinkingLevel::Low => "Low",
            ThinkingLevel::Medium => "Medium",
            ThinkingLevel::High => "High",
            ThinkingLevel::Max => "Max",
        }
    }

    /// Convert to (enabled, budget) configuration
    #[must_use]
    pub fn to_config(&self) -> (bool, u32) {
        match self {
            ThinkingLevel::Off => (false, 0),
            ThinkingLevel::Minimal => (true, 1024),
            ThinkingLevel::Low => (true, 4096),
            ThinkingLevel::Medium => (true, 10000),
            ThinkingLevel::High => (true, 20000),
            ThinkingLevel::Max => (true, 50000),
        }
    }

    /// Parse from string
    #[must_use]
    pub fn parse(s: &str) -> Option<Self> {
        match s.to_lowercase().as_str() {
            "off" | "none" | "disabled" => Some(ThinkingLevel::Off),
            "minimal" | "min" => Some(ThinkingLevel::Minimal),
            "low" => Some(ThinkingLevel::Low),
            "medium" | "med" | "default" => Some(ThinkingLevel::Medium),
            "high" => Some(ThinkingLevel::High),
            "max" | "maximum" => Some(ThinkingLevel::Max),
            _ => None,
        }
    }
}

/// A message entry
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageEntry {
    pub timestamp: String,
    pub message: AppMessage,
}

/// Attachment extraction entry.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttachmentExtract {
    pub timestamp: String,
    #[serde(rename = "attachmentId")]
    pub attachment_id: String,
    #[serde(rename = "extractedText")]
    pub extracted_text: String,
}

/// Conversation message with role-based discrimination.
///
/// Messages are serialized with a `"role"` field that determines the variant, matching
/// the format used by AI provider APIs (Anthropic, `OpenAI`, etc.).
///
/// # Role Serialization
///
/// The `#[serde(tag = "role")]` attribute creates JSON like:
/// ```json
/// {"role":"user","content":"Hello",...}
/// {"role":"assistant","content":[{"type":"text","text":"Hi"}],...}
/// {"role":"toolResult","tool_call_id":"call_123",...}
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "role", rename_all = "camelCase")]
pub enum AppMessage {
    /// User-authored message (human input).
    ///
    /// Can contain plain text or structured content blocks (text + images).
    User {
        /// Message content (either a simple string or structured blocks).
        content: MessageContent,

        /// Optional file attachments.
        #[serde(skip_serializing_if = "Option::is_none")]
        attachments: Option<Vec<Attachment>>,

        /// Unix timestamp in milliseconds.
        ///
        /// Defaults to 0 if missing during deserialization.
        #[serde(default)]
        timestamp: u64,
    },

    /// Assistant-generated response.
    ///
    /// Contains structured content blocks (text, thinking, tool calls) along with
    /// token usage statistics and metadata.
    Assistant {
        /// Response content as a list of structured blocks.
        ///
        /// Can contain text, thinking, tool calls, or images.
        content: Vec<ContentBlock>,

        /// API name (e.g., "anthropic", "openai").
        ///
        /// Omitted if None.
        #[serde(skip_serializing_if = "Option::is_none")]
        api: Option<String>,

        /// Provider name (e.g., "Anthropic", "`OpenAI`").
        ///
        /// Omitted if None.
        #[serde(skip_serializing_if = "Option::is_none")]
        provider: Option<String>,

        /// Model identifier that generated this response.
        ///
        /// May differ from session model if the user switched models mid-session.
        /// Omitted if None.
        #[serde(skip_serializing_if = "Option::is_none")]
        model: Option<String>,

        /// Token consumption statistics.
        ///
        /// Includes input/output tokens, cache usage, and cost breakdown.
        /// Omitted if None.
        #[serde(skip_serializing_if = "Option::is_none")]
        usage: Option<TokenUsage>,

        /// Reason the model stopped generating.
        ///
        /// Common values: "`end_turn`", "`max_tokens`", "`stop_sequence`", "`tool_use`".
        /// Omitted if None.
        #[serde(
            rename = "stopReason",
            alias = "stop_reason",
            serialize_with = "serialize_stop_reason",
            skip_serializing_if = "Option::is_none"
        )]
        stop_reason: Option<String>,

        /// Unix timestamp in milliseconds.
        ///
        /// Defaults to 0 if missing.
        #[serde(default)]
        timestamp: u64,
    },

    /// Tool execution result.
    ///
    /// Sent back to the assistant after executing a tool call to provide the output.
    ToolResult {
        /// Unique identifier linking this result to the tool call.
        ///
        /// Matches the `id` field from the `ContentBlock::ToolCall`.
        #[serde(rename = "toolCallId", alias = "tool_call_id")]
        tool_call_id: String,

        /// Name of the tool that was executed.
        #[serde(rename = "toolName", alias = "tool_name")]
        tool_name: String,

        /// Tool output (success result or error message).
        #[serde(deserialize_with = "deserialize_tool_result_content")]
        content: String,

        /// Structured tool execution details.
        ///
        /// Can include timing, file paths, or other metadata. Omitted if None.
        #[serde(skip_serializing_if = "Option::is_none")]
        details: Option<serde_json::Value>,

        /// Whether this result represents an error.
        ///
        /// Defaults to false if missing.
        #[serde(rename = "isError", alias = "is_error", default)]
        is_error: bool,

        /// Unix timestamp in milliseconds.
        ///
        /// Defaults to 0 if missing.
        #[serde(default)]
        timestamp: u64,
    },
}

impl AppMessage {
    /// Get the role of this message
    #[must_use]
    pub fn role(&self) -> &'static str {
        match self {
            AppMessage::User { .. } => "user",
            AppMessage::Assistant { .. } => "assistant",
            AppMessage::ToolResult { .. } => "toolResult",
        }
    }

    /// Get the timestamp
    #[must_use]
    pub fn timestamp(&self) -> u64 {
        match self {
            AppMessage::User { timestamp, .. } => *timestamp,
            AppMessage::Assistant { timestamp, .. } => *timestamp,
            AppMessage::ToolResult { timestamp, .. } => *timestamp,
        }
    }

    /// Get text content (for display)
    #[must_use]
    pub fn text_content(&self) -> String {
        match self {
            AppMessage::User { content, .. } => match content {
                MessageContent::Text(s) => s.clone(),
                MessageContent::Blocks(blocks) => blocks
                    .iter()
                    .filter_map(|b| {
                        if let ContentBlock::Text { text } = b {
                            Some(text.as_str())
                        } else {
                            None
                        }
                    })
                    .collect::<Vec<_>>()
                    .join(""),
            },
            AppMessage::Assistant { content, .. } => content
                .iter()
                .filter_map(|b| {
                    if let ContentBlock::Text { text } = b {
                        Some(text.as_str())
                    } else {
                        None
                    }
                })
                .collect::<Vec<_>>()
                .join(""),
            AppMessage::ToolResult { content, .. } => content.clone(),
        }
    }
}

/// File attachment metadata for user messages.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Attachment {
    pub id: String,
    #[serde(rename = "type")]
    pub attachment_type: String,
    #[serde(rename = "fileName")]
    pub file_name: String,
    #[serde(rename = "mimeType")]
    pub mime_type: String,
    pub size: u64,
    pub content: String,
    #[serde(rename = "extractedText", skip_serializing_if = "Option::is_none")]
    pub extracted_text: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub preview: Option<String>,
}

/// Message content (can be string or blocks)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MessageContent {
    Text(String),
    Blocks(Vec<ContentBlock>),
}

/// Content block types
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ContentBlock {
    /// Plain text
    Text { text: String },
    /// Thinking content
    #[serde(rename = "thinking")]
    Thinking {
        #[serde(rename = "thinking", alias = "text")]
        text: String,
        #[serde(
            rename = "thinkingSignature",
            alias = "signature",
            skip_serializing_if = "Option::is_none"
        )]
        signature: Option<String>,
    },
    /// Tool call
    #[serde(rename = "toolCall", alias = "tool_call")]
    ToolCall {
        id: String,
        name: String,
        #[serde(rename = "arguments", alias = "args", default)]
        args: serde_json::Value,
    },
    /// Image (base64)
    Image {
        #[serde(skip_serializing_if = "Option::is_none")]
        source: Option<ImageSource>,
    },
}

/// Image source
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ImageSource {
    #[serde(rename = "type")]
    pub source_type: String,
    pub media_type: String,
    pub data: String,
}

/// Token consumption and cost tracking for assistant messages.
///
/// Tracks both token counts and associated costs, with special handling for
/// prompt caching which provides discounted rates for repeated context.
///
/// # Prompt Caching
///
/// - `cache_write`: Tokens written to cache on first use (full price)
/// - `cache_read`: Tokens read from cache on subsequent uses (90% discount)
///
/// Example: A 10,000 token system prompt costs full price the first time, but
/// only 10% of that price on cache hits.
///
/// # Field Naming
///
/// Uses camelCase for JSON compatibility with the TypeScript codebase:
/// - `cacheRead` instead of `cache_read`
/// - `cacheWrite` instead of `cache_write`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TokenUsage {
    /// Tokens sent to the model (prompt + user message).
    ///
    /// Defaults to 0 if missing.
    #[serde(default)]
    pub input: u64,

    /// Tokens generated by the model (response text).
    ///
    /// Defaults to 0 if missing.
    #[serde(default)]
    pub output: u64,

    /// Tokens served from prompt cache (discounted cost).
    ///
    /// Defaults to 0 if missing.
    #[serde(default, rename = "cacheRead")]
    pub cache_read: u64,

    /// Tokens written to prompt cache (full cost).
    ///
    /// Defaults to 0 if missing.
    #[serde(default, rename = "cacheWrite")]
    pub cache_write: u64,

    /// Detailed cost breakdown by token type.
    ///
    /// Omitted if None (older sessions may not have cost data).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cost: Option<TokenCost>,
}

impl TokenUsage {
    #[must_use]
    pub fn total(&self) -> u64 {
        self.input + self.output
    }

    #[must_use]
    pub fn total_cost(&self) -> f64 {
        self.cost.as_ref().map_or(0.0, |c| c.total)
    }
}

/// Token cost breakdown
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TokenCost {
    #[serde(default)]
    pub input: f64,
    #[serde(default)]
    pub output: f64,
    #[serde(default, rename = "cacheRead")]
    pub cache_read: f64,
    #[serde(default, rename = "cacheWrite")]
    pub cache_write: f64,
    #[serde(default)]
    pub total: f64,
}

/// Thinking level change entry
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThinkingLevelChange {
    pub timestamp: String,
    #[serde(rename = "thinkingLevel", alias = "thinking_level")]
    pub thinking_level: ThinkingLevel,
}

/// Model change entry
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelChange {
    pub timestamp: String,
    pub model: String,
    #[serde(
        rename = "modelMetadata",
        alias = "model_metadata",
        skip_serializing_if = "Option::is_none"
    )]
    pub model_metadata: Option<ModelMetadata>,
}

/// Session metadata entry
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SessionMeta {
    pub timestamp: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<String>,
    #[serde(default)]
    pub favorite: bool,
}

/// Context compaction entry
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompactionEntry {
    pub timestamp: String,
    pub summary: String,
    #[serde(rename = "firstKeptEntryIndex", alias = "first_kept_entry_index")]
    pub first_kept_entry_index: usize,
    #[serde(rename = "tokensBefore", alias = "tokens_before")]
    pub tokens_before: u64,
    #[serde(default)]
    pub auto: bool,
    #[serde(
        rename = "customInstructions",
        alias = "custom_instructions",
        skip_serializing_if = "Option::is_none"
    )]
    pub custom_instructions: Option<String>,
}

/// Computed session statistics (not serialized to JSONL).
///
/// Aggregates metrics across all messages in a session for display purposes.
/// These values are calculated during session reading and are not stored in
/// the session file itself.
///
/// # Usage
///
/// ```rust,ignore
/// let session = SessionReader::read_file(path)?;
/// println!("Total messages: {}", session.stats.total_messages());
/// println!("Token usage: {} in, {} out",
///     session.stats.total_input_tokens,
///     session.stats.total_output_tokens);
/// println!("Total cost: ${:.4}", session.stats.total_cost);
/// ```
#[derive(Debug, Clone, Default)]
pub struct SessionStats {
    /// Count of user messages in the session.
    pub user_messages: usize,

    /// Count of assistant messages in the session.
    pub assistant_messages: usize,

    /// Count of tool call requests made by the assistant.
    pub tool_calls: usize,

    /// Count of tool result messages sent back to the assistant.
    pub tool_results: usize,

    /// Sum of all input tokens across assistant messages.
    pub total_input_tokens: u64,

    /// Sum of all output tokens across assistant messages.
    pub total_output_tokens: u64,

    /// Sum of all costs across assistant messages (in USD).
    pub total_cost: f64,
}

impl SessionStats {
    #[must_use]
    pub fn total_messages(&self) -> usize {
        self.user_messages + self.assistant_messages + self.tool_results
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn repo_fixture(name: &str) -> String {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../..")
            .join("test/fixtures/session-wire")
            .join(name);
        std::fs::read_to_string(path).unwrap()
    }

    fn parse_fixture(name: &str) -> Vec<SessionEntry> {
        repo_fixture(name)
            .lines()
            .filter(|line| !line.trim().is_empty())
            .map(|line| serde_json::from_str(line).unwrap())
            .collect()
    }

    #[test]
    fn parse_session_header() {
        let json = r#"{"type":"session","id":"abc123","timestamp":"2024-01-15T10:30:00Z","cwd":"/tmp","model":"anthropic/claude-3","thinking_level":"medium"}"#;
        let entry: SessionEntry = serde_json::from_str(json).unwrap();
        match entry {
            SessionEntry::Session(header) => {
                assert_eq!(header.id, "abc123");
                assert_eq!(header.cwd, "/tmp");
            }
            _ => panic!("Expected Session entry"),
        }
    }

    #[test]
    fn parse_user_message() {
        let json = r#"{"type":"message","timestamp":"2024-01-15T10:30:00Z","message":{"role":"user","content":"Hello","timestamp":0}}"#;
        let entry: SessionEntry = serde_json::from_str(json).unwrap();
        match entry {
            SessionEntry::Message(msg) => {
                assert_eq!(msg.message.role(), "user");
            }
            _ => panic!("Expected Message entry"),
        }
    }

    #[test]
    fn parse_assistant_message() {
        let json = r#"{"type":"message","timestamp":"2024-01-15T10:30:00Z","message":{"role":"assistant","content":[{"type":"text","text":"Hi there!"}],"timestamp":0}}"#;
        let entry: SessionEntry = serde_json::from_str(json).unwrap();
        match entry {
            SessionEntry::Message(msg) => {
                assert_eq!(msg.message.role(), "assistant");
                assert_eq!(msg.message.text_content(), "Hi there!");
            }
            _ => panic!("Expected Message entry"),
        }
    }

    #[test]
    fn parse_typescript_assistant_blocks() {
        let json = r#"{"type":"message","timestamp":"2024-01-15T10:30:00Z","message":{"role":"assistant","api":"openai-responses","provider":"openai","model":"gpt-5.2","usage":{"input":10,"output":4,"cacheRead":2,"cacheWrite":1,"cost":{"input":0.1,"output":0.2,"cacheRead":0.01,"cacheWrite":0.02,"total":0.33}},"stopReason":"toolUse","timestamp":0,"content":[{"type":"thinking","thinking":"Need a file read","thinkingSignature":"sig-1"},{"type":"toolCall","id":"call_1","name":"read","arguments":{"path":"README.md"}}]}}"#;
        let entry: SessionEntry = serde_json::from_str(json).unwrap();

        let SessionEntry::Message(msg) = entry else {
            panic!("Expected Message entry");
        };
        let AppMessage::Assistant {
            content,
            stop_reason,
            usage,
            ..
        } = msg.message
        else {
            panic!("Expected assistant message");
        };

        assert_eq!(stop_reason.as_deref(), Some("toolUse"));
        assert_eq!(usage.unwrap().cache_read, 2);
        match &content[0] {
            ContentBlock::Thinking { text, signature } => {
                assert_eq!(text, "Need a file read");
                assert_eq!(signature.as_deref(), Some("sig-1"));
            }
            _ => panic!("Expected thinking block"),
        }
        match &content[1] {
            ContentBlock::ToolCall { id, name, args } => {
                assert_eq!(id, "call_1");
                assert_eq!(name, "read");
                assert_eq!(args["path"], "README.md");
            }
            _ => panic!("Expected tool call block"),
        }
    }

    #[test]
    fn parse_legacy_snake_case_assistant_blocks() {
        let json = r#"{"type":"message","timestamp":"2024-01-15T10:30:00Z","message":{"role":"assistant","stop_reason":"tool_use","content":[{"type":"thinking","text":"Need a file read","signature":"sig-1"},{"type":"tool_call","id":"call_1","name":"read","args":{"path":"README.md"}}],"timestamp":0}}"#;
        let entry: SessionEntry = serde_json::from_str(json).unwrap();

        let SessionEntry::Message(msg) = entry else {
            panic!("Expected Message entry");
        };
        let AppMessage::Assistant {
            content,
            stop_reason,
            ..
        } = msg.message
        else {
            panic!("Expected assistant message");
        };

        assert_eq!(stop_reason.as_deref(), Some("tool_use"));
        assert!(matches!(content[0], ContentBlock::Thinking { .. }));
        assert!(matches!(content[1], ContentBlock::ToolCall { .. }));
    }

    #[test]
    fn parse_typescript_tool_result_message() {
        let json = r#"{"type":"message","timestamp":"2024-01-15T10:30:00Z","message":{"role":"toolResult","toolCallId":"call_1","toolName":"read","content":[{"type":"text","text":"file contents"}],"details":{"path":"README.md"},"isError":false,"timestamp":0}}"#;
        let entry: SessionEntry = serde_json::from_str(json).unwrap();

        let SessionEntry::Message(msg) = entry else {
            panic!("Expected Message entry");
        };
        let AppMessage::ToolResult {
            tool_call_id,
            tool_name,
            content,
            is_error,
            ..
        } = msg.message
        else {
            panic!("Expected tool result message");
        };

        assert_eq!(tool_call_id, "call_1");
        assert_eq!(tool_name, "read");
        assert_eq!(content, "file contents");
        assert!(!is_error);
    }

    #[test]
    fn parse_shared_session_wire_fixtures() {
        for fixture in [
            "canonical-tool-session.jsonl",
            "legacy-rust-tool-session.jsonl",
        ] {
            let entries = parse_fixture(fixture);
            assert!(!entries.is_empty(), "fixture {fixture} should not be empty");
        }
    }

    #[test]
    fn serialize_rust_entries_prefers_canonical_session_wire_keys() {
        let entries = parse_fixture("legacy-rust-tool-session.jsonl");

        let session = serde_json::to_value(&entries[0]).unwrap();
        assert_eq!(session["thinkingLevel"], "medium");
        assert_eq!(session["modelMetadata"]["modelId"], "gpt-5.2");
        assert_eq!(session["systemPrompt"], "Persisted system");
        assert_eq!(session["branchedFrom"], "parent-session");
        assert!(session.get("thinking_level").is_none());
        assert!(session.get("model_metadata").is_none());
        assert!(session.get("system_prompt").is_none());
        assert!(session.get("branched_from").is_none());

        let assistant = serde_json::to_value(&entries[2]).unwrap();
        let assistant_message = &assistant["message"];
        assert_eq!(assistant_message["stopReason"], "toolUse");
        assert!(assistant_message.get("stop_reason").is_none());
        assert_eq!(
            assistant_message["content"][0]["thinking"],
            "Need a file read"
        );
        assert_eq!(
            assistant_message["content"][0]["thinkingSignature"],
            "sig-1"
        );
        assert_eq!(assistant_message["content"][1]["type"], "toolCall");
        assert_eq!(
            assistant_message["content"][1]["arguments"]["path"],
            "README.md"
        );
        assert!(assistant_message["content"][1].get("args").is_none());

        let tool_result = serde_json::to_value(&entries[3]).unwrap();
        let tool_result_message = &tool_result["message"];
        assert_eq!(tool_result_message["toolCallId"], "call-1");
        assert_eq!(tool_result_message["toolName"], "read");
        assert_eq!(tool_result_message["isError"], false);
        assert!(tool_result_message.get("tool_call_id").is_none());
        assert!(tool_result_message.get("tool_name").is_none());
        assert!(tool_result_message.get("is_error").is_none());

        let model_change = serde_json::to_value(&entries[4]).unwrap();
        assert_eq!(model_change["modelMetadata"]["modelId"], "gpt-5.2");
        assert!(model_change.get("model_metadata").is_none());

        let thinking_level_change = serde_json::to_value(&entries[5]).unwrap();
        assert_eq!(thinking_level_change["thinkingLevel"], "high");
        assert!(thinking_level_change.get("thinking_level").is_none());

        let compaction = serde_json::to_value(&entries[6]).unwrap();
        assert_eq!(compaction["firstKeptEntryIndex"], 0);
        assert_eq!(compaction["tokensBefore"], 1234);
        assert_eq!(compaction["customInstructions"], "keep tool context");
        assert!(compaction.get("first_kept_entry_index").is_none());
        assert!(compaction.get("tokens_before").is_none());
        assert!(compaction.get("custom_instructions").is_none());
    }

    #[test]
    fn thinking_level_serialize() {
        assert_eq!(
            serde_json::to_string(&ThinkingLevel::High).unwrap(),
            "\"high\""
        );
    }

    #[test]
    fn token_usage_total() {
        let usage = TokenUsage {
            input: 100,
            output: 50,
            ..Default::default()
        };
        assert_eq!(usage.total(), 150);
    }
}
