// Auto-generated by `scripts/session-wire-format-codegen.mjs`.
// Do not edit manually; update `src/session/wire-format.manifest.json` instead.
#![allow(dead_code)]

pub const SESSION_WIRE_FORMAT_VERSION: &str = "session-wire-format.v1";

pub const STOP_REASON_ALIASES: &[(&str, &str)] = &[
    ("tool_use", "toolUse"),
    ("tool_calls", "toolUse"),
    ("max_tokens", "length"),
    ("end_turn", "stop"),
    ("stop_sequence", "stop"),
];

#[must_use]
pub fn canonical_stop_reason(reason: &str) -> &str {
    match reason {
        "tool_use" => "toolUse",
        "tool_calls" => "toolUse",
        "max_tokens" => "length",
        "end_turn" => "stop",
        "stop_sequence" => "stop",
        other => other,
    }
}
