/**
 * Context Compaction - Pure Functions for Long Session Management
 *
 * This module provides pure functions for context compaction logic. Context
 * compaction summarizes older conversation history when approaching token limits,
 * allowing conversations to continue indefinitely while preserving important context.
 *
 * ## Architecture
 *
 * The compaction system follows a separation of concerns:
 * - **This module**: Pure functions for token calculation, cut point detection, and
 *   determining when compaction should trigger. No I/O or side effects.
 * - **SessionManager**: Handles persistence of compaction entries to session files.
 * - **ConversationCompactor**: Orchestrates the compaction process with TUI integration.
 *
 * ## Token-Based Cut Point Detection
 *
 * Instead of using a fixed message count, cut point detection uses actual token usage
 * from assistant messages. The algorithm walks backwards from the newest message,
 * calculating cumulative token differences until `keepRecentTokens` is exceeded.
 *
 * This approach:
 * - Preserves more context when messages are small
 * - Compacts more aggressively when messages are large
 * - Respects turn boundaries (never splits user/assistant/toolResult groups)
 *
 * ## Summarization Strategy
 *
 * When compacting, older messages are summarized using the LLM with a handoff-style
 * prompt. If a previous compaction exists, its summary is included as context for
 * the new summarization (cascading summaries).
 *
 * @module agent/compaction
 */

import type { SessionEntry } from "../session/types.js";
import type { AppMessage, AssistantMessage, Usage } from "./types.js";

// ============================================================================
// Types
// ============================================================================

/**
 * Configuration for compaction behavior.
 */
export interface CompactionSettings {
	/** Whether auto-compaction is enabled */
	enabled: boolean;
	/**
	 * Tokens to reserve for summary generation and safety margin.
	 * Default: 16384 (~13k for summary + ~3k safety margin)
	 */
	reserveTokens: number;
	/**
	 * Approximate number of recent tokens to preserve verbatim.
	 * Default: 20000 (recent context preserved without summarization)
	 */
	keepRecentTokens: number;
}

/**
 * Default compaction settings based on research into Claude Code, Codex, and OpenCode.
 */
export const DEFAULT_COMPACTION_SETTINGS: CompactionSettings = {
	enabled: true,
	reserveTokens: 16384,
	keepRecentTokens: 20000,
};

/**
 * Result of a compaction operation, ready to be persisted.
 */
export interface CompactionResult {
	/** Generated summary of compacted messages */
	summary: string;
	/** Index of first entry to keep (entries before this are summarized) */
	firstKeptEntryIndex: number;
	/** Token count before compaction (for metrics) */
	tokensBefore: number;
	/** Messages that were summarized */
	summarizedMessages: AppMessage[];
	/** Messages to keep verbatim */
	keptMessages: AppMessage[];
}

// ============================================================================
// Token Calculation
// ============================================================================

/**
 * Calculate total context tokens from usage metadata.
 *
 * This includes all token types that contribute to context window consumption:
 * - input: Tokens from user/system messages
 * - output: Tokens generated by the model
 * - cacheRead: Tokens read from prompt cache
 * - cacheWrite: Tokens written to prompt cache
 *
 * @param usage - Usage metadata from an assistant message
 * @returns Total context token count
 */
export function calculateContextTokens(usage: Usage): number {
	return usage.input + usage.output + usage.cacheRead + usage.cacheWrite;
}

/**
 * Extract usage metadata from a message if it's a non-aborted assistant message.
 *
 * @param msg - Any application message
 * @returns Usage metadata or null if not available/applicable
 */
function getAssistantUsage(msg: AppMessage): Usage | null {
	if (msg.role === "assistant") {
		const assistantMsg = msg as AssistantMessage;
		if (assistantMsg.stopReason !== "aborted" && assistantMsg.usage) {
			return assistantMsg.usage;
		}
	}
	return null;
}

/**
 * Find the last non-aborted assistant message usage from a message array.
 *
 * Used to determine current context window consumption. Walks backwards
 * to find the most recent valid usage metadata.
 *
 * @param messages - Array of application messages
 * @returns Usage metadata from the last assistant message, or null
 */
export function getLastAssistantUsage(messages: AppMessage[]): Usage | null {
	for (let i = messages.length - 1; i >= 0; i--) {
		const usage = getAssistantUsage(messages[i]);
		if (usage) return usage;
	}
	return null;
}

/**
 * Find the last non-aborted assistant message usage from session entries.
 *
 * @param entries - Array of session entries
 * @returns Usage metadata from the last assistant message, or null
 */
export function getLastAssistantUsageFromEntries(
	entries: SessionEntry[],
): Usage | null {
	for (let i = entries.length - 1; i >= 0; i--) {
		const entry = entries[i];
		if (entry.type === "message") {
			const usage = getAssistantUsage(entry.message as AppMessage);
			if (usage) return usage;
		}
	}
	return null;
}

// ============================================================================
// Compaction Trigger Detection
// ============================================================================

/**
 * Determine if compaction should trigger based on current context usage.
 *
 * Compaction triggers when context usage exceeds `contextWindow - reserveTokens`,
 * leaving enough room for summary generation plus a safety margin.
 *
 * @param contextTokens - Current context window usage in tokens
 * @param contextWindow - Model's total context window size
 * @param settings - Compaction configuration
 * @returns true if compaction should trigger
 */
export function shouldCompact(
	contextTokens: number,
	contextWindow: number,
	settings: CompactionSettings,
): boolean {
	if (!settings.enabled) return false;
	return contextTokens > contextWindow - settings.reserveTokens;
}

/**
 * Calculate context usage percentage.
 *
 * @param contextTokens - Current context window usage in tokens
 * @param contextWindow - Model's total context window size
 * @returns Percentage of context window used (0-100)
 */
export function calculateUsagePercent(
	contextTokens: number,
	contextWindow: number,
): number {
	if (contextWindow <= 0) return 0;
	return (contextTokens / contextWindow) * 100;
}

// ============================================================================
// Cut Point Detection
// ============================================================================

/**
 * Find indices of user messages (turn boundaries) in a message array.
 *
 * Turn boundaries are important because we never want to split a turn
 * (user message + assistant response + tool results). Cutting at a user
 * message ensures turn integrity.
 *
 * @param messages - Array of messages to scan
 * @param startIndex - First index to consider (inclusive)
 * @param endIndex - Last index to consider (exclusive)
 * @returns Array of indices where user messages appear
 */
function findTurnBoundaries(
	messages: AppMessage[],
	startIndex: number,
	endIndex: number,
): number[] {
	const boundaries: number[] = [];
	for (let i = startIndex; i < endIndex; i++) {
		if (messages[i].role === "user") {
			boundaries.push(i);
		}
	}
	return boundaries;
}

/**
 * Find the optimal cut point in messages that preserves `keepRecentTokens`.
 *
 * The algorithm:
 * 1. Find all turn boundaries (user message indices)
 * 2. Walk backwards collecting assistant token usage
 * 3. Find where cumulative token difference exceeds keepRecentTokens
 * 4. Return the nearest turn boundary at or before that point
 *
 * This ensures:
 * - Recent context is preserved based on actual token usage, not message count
 * - Turn integrity is maintained (user/assistant/toolResult groups stay together)
 * - More context is kept when messages are small, less when large
 *
 * @param messages - Array of messages to analyze
 * @param startIndex - First index to consider for cutting
 * @param endIndex - Last index to consider (exclusive)
 * @param keepRecentTokens - Approximate tokens to preserve
 * @returns Index of first message to keep (messages before this are summarized)
 */
export function findCutPoint(
	messages: AppMessage[],
	startIndex: number,
	endIndex: number,
	keepRecentTokens: number,
): number {
	const boundaries = findTurnBoundaries(messages, startIndex, endIndex);

	if (boundaries.length === 0) {
		return startIndex; // No user messages, keep everything in range
	}

	// Collect assistant usages walking backwards from endIndex
	const assistantUsages: Array<{ index: number; tokens: number }> = [];
	for (let i = endIndex - 1; i >= startIndex; i--) {
		const usage = getAssistantUsage(messages[i]);
		if (usage) {
			assistantUsages.push({
				index: i,
				tokens: calculateContextTokens(usage),
			});
		}
	}

	if (assistantUsages.length === 0) {
		// No usage info, keep last turn only
		return boundaries[boundaries.length - 1];
	}

	// Walk through and find where cumulative token difference exceeds keepRecentTokens
	const newestTokens = assistantUsages[0].tokens;
	let cutIndex = startIndex; // Default: keep everything in range

	for (let i = 1; i < assistantUsages.length; i++) {
		const tokenDiff = newestTokens - assistantUsages[i].tokens;
		if (tokenDiff >= keepRecentTokens) {
			// Find the turn boundary at or before the assistant we want to keep
			const lastKeptAssistantIndex = assistantUsages[i - 1].index;

			for (let b = boundaries.length - 1; b >= 0; b--) {
				if (boundaries[b] <= lastKeptAssistantIndex) {
					cutIndex = boundaries[b];
					break;
				}
			}
			break;
		}
	}

	return cutIndex;
}

/**
 * Adjust a cut boundary to preserve tool call/result integrity.
 *
 * Tool results must stay paired with their originating assistant message.
 * If a toolResult would be kept but its toolCall would be cut, this
 * moves the boundary back to include the toolCall.
 *
 * @param messages - Array of messages
 * @param boundary - Initial cut point
 * @returns Adjusted boundary that preserves tool integrity
 */
export function adjustBoundaryForToolResults(
	messages: AppMessage[],
	boundary: number,
): number {
	let adjusted = boundary;
	const seenToolCalls = new Set<string>();
	const missingToolCalls = new Set<string>();

	// Process assistant message to collect tool calls
	const processAssistantMessage = (message: AppMessage) => {
		if (message.role !== "assistant") return;
		const content = (message as AssistantMessage).content;
		if (!content) return;
		for (const part of content) {
			if (part?.type === "toolCall") {
				seenToolCalls.add(part.id);
				if (missingToolCalls.has(part.id)) {
					missingToolCalls.delete(part.id);
				}
			}
		}
	};

	// Process tool result to check for missing tool calls
	const processToolResultMessage = (message: AppMessage) => {
		if (message.role !== "toolResult") return;
		const toolCallId = (message as { toolCallId: string }).toolCallId;
		if (!seenToolCalls.has(toolCallId)) {
			missingToolCalls.add(toolCallId);
		}
	};

	// First pass: process messages we're keeping
	for (const message of messages.slice(adjusted)) {
		processAssistantMessage(message);
		processToolResultMessage(message);
	}

	// Walk backwards to find missing tool calls
	while (missingToolCalls.size > 0 && adjusted > 0) {
		adjusted -= 1;
		const candidate = messages[adjusted];
		processAssistantMessage(candidate);
		processToolResultMessage(candidate);
	}

	return adjusted;
}

// ============================================================================
// Summarization
// ============================================================================

/**
 * Default prompt for generating compaction summaries.
 *
 * Based on research into Claude Code, Codex (OpenAI), and OpenCode (SST).
 * Focused on creating actionable handoff summaries for the resuming LLM.
 */
export const SUMMARIZATION_PROMPT = `You are performing a CONTEXT CHECKPOINT COMPACTION. Create a handoff summary for another LLM that will resume the task.

Include:
- Current progress and key decisions made
- Important context, constraints, or user preferences
- Absolute file paths of any relevant files that were read or modified
- What remains to be done (clear next steps)
- Any critical data, examples, or references needed to continue

Be concise, structured, and focused on helping the next LLM seamlessly continue the work.`;

/**
 * Build the summarization prompt, optionally with custom instructions.
 *
 * @param customInstructions - Optional additional focus for the summary
 * @returns Complete summarization prompt
 */
export function buildSummarizationPrompt(customInstructions?: string): string {
	if (customInstructions) {
		return `${SUMMARIZATION_PROMPT}\n\nAdditional focus: ${customInstructions}`;
	}
	return SUMMARIZATION_PROMPT;
}

/**
 * Decorate a summary with handoff context.
 *
 * Adds a prefix that instructs the resuming LLM to build on existing work,
 * and a footer with compaction metadata.
 *
 * @param summaryText - The generated summary content
 * @param compactedCount - Number of messages that were compacted
 * @param fromModel - Whether the summary was generated by the LLM (vs local fallback)
 * @returns Decorated summary text
 */
export function decorateSummaryText(
	summaryText: string,
	compactedCount: number,
	fromModel: boolean,
): string {
	// OAI-style handoff prefix that tells the resuming model it's continuing work
	const handoffPrefix = fromModel
		? "Another language model started to solve this problem and produced a summary of its thinking process. You also have access to the state of the tools that were used by that language model. Use this to build on the work that has already been done and avoid duplicating work. Here is the summary produced by the other language model, use the information in this summary to assist with your own analysis:\n\n"
		: "_Local summary of prior discussion (model unavailable)._\n\n";

	return `${handoffPrefix}${summaryText}\n\n(Compacted ${compactedCount} messages on ${new Date().toLocaleString()})`;
}

/**
 * Build a simple local summary when LLM summarization fails.
 *
 * Creates a bullet-point summary of user/assistant exchanges without
 * calling the LLM. Used as fallback when the model is unavailable.
 *
 * @param messages - Messages to summarize
 * @param maxExchanges - Maximum number of exchanges to include
 * @returns Local summary text
 */
export function buildLocalSummary(
	messages: AppMessage[],
	maxExchanges = 32,
): string {
	const lines: string[] = [];
	let exchange = 1;

	for (const message of messages) {
		if (lines.length >= maxExchanges) break;

		const content = extractMessageText(message);
		if (!content) continue;

		const truncated = truncateText(content, 180);
		if (message.role === "user") {
			lines.push(`• User ${exchange}: ${truncated}`);
		} else if (message.role === "assistant") {
			lines.push(`  ↳ Assistant: ${truncated}`);
			exchange += 1;
		} else if (message.role === "toolResult") {
			const toolName = (message as { toolName?: string }).toolName || "unknown";
			lines.push(`  ↳ Tool ${toolName}: ${truncateText(content, 160)}`);
		}
	}

	if (!lines.length) {
		return "(conversation summary placeholder: no textual content to compact)";
	}

	return `Conversation summary generated at ${new Date().toLocaleString()}\n${lines.join("\n")}`;
}

/**
 * Extract text content from a message.
 *
 * @param message - Message to extract text from
 * @returns Combined text content or empty string
 */
function extractMessageText(message: AppMessage): string {
	if (typeof message.content === "string") {
		return message.content;
	}
	if (Array.isArray(message.content)) {
		return message.content
			.map((part) => {
				if (part.type === "text") return part.text;
				if (part.type === "thinking") return part.thinking;
				return "";
			})
			.filter(Boolean)
			.join(" ");
	}
	return "";
}

/**
 * Truncate text to a maximum length with ellipsis.
 *
 * @param text - Text to truncate
 * @param limit - Maximum length
 * @returns Truncated text with ellipsis if needed
 */
function truncateText(text: string, limit = 160): string {
	if (text.length <= limit) return text;
	return `${text.slice(0, limit - 1).trim()}…`;
}

// ============================================================================
// Compaction Preparation
// ============================================================================

/**
 * Prepare messages for compaction by finding the cut point and splitting.
 *
 * This is a pure function that determines what should be summarized vs kept,
 * without actually performing the summarization or I/O.
 *
 * @param messages - All messages in the conversation
 * @param settings - Compaction settings
 * @param previousSummary - Optional summary from a previous compaction (for cascading)
 * @returns Object with messages to summarize and messages to keep, or null if not enough history
 */
export function prepareCompaction(
	messages: AppMessage[],
	settings: CompactionSettings,
	previousSummary?: string,
): {
	messagesToSummarize: AppMessage[];
	keptMessages: AppMessage[];
	cutIndex: number;
} | null {
	const keepCount = 6; // Minimum messages to always keep
	if (messages.length <= keepCount + 1) {
		return null; // Not enough history to compact
	}

	// Find initial boundary
	let boundary = Math.max(0, messages.length - keepCount);

	// Use token-based cut point if we have usage data
	const lastUsage = getLastAssistantUsage(messages);
	if (lastUsage) {
		const tokenBasedCut = findCutPoint(
			messages,
			0,
			messages.length,
			settings.keepRecentTokens,
		);
		// Use the more conservative of the two (keep more messages)
		boundary = Math.max(boundary, tokenBasedCut);
	}

	// Adjust for tool result integrity
	boundary = adjustBoundaryForToolResults(messages, boundary);

	const older = messages.slice(0, boundary);
	if (!older.length) {
		return null; // No earlier messages to compact
	}

	// Prepare messages for summarization
	const messagesToSummarize: AppMessage[] = [];

	// Include previous summary if cascading
	if (previousSummary) {
		messagesToSummarize.push({
			role: "user",
			content: `Previous session summary:\n${previousSummary}`,
			timestamp: Date.now(),
		});
	}

	// Add older messages (limit to most recent 40 for summarization efficiency)
	const sliceSize = Math.min(40, older.length);
	messagesToSummarize.push(...older.slice(-sliceSize));

	return {
		messagesToSummarize,
		keptMessages: messages.slice(boundary),
		cutIndex: boundary,
	};
}

/**
 * Extract the most recent compaction summary from messages.
 *
 * Looks for a message that appears to be a compaction summary (contains
 * the characteristic handoff prefix or compaction footer).
 *
 * @param messages - Messages to search
 * @returns Previous summary text or undefined
 */
export function findPreviousSummary(
	messages: AppMessage[],
): string | undefined {
	for (const message of messages) {
		if (message.role === "assistant") {
			const text = extractMessageText(message);
			if (
				text.includes("Another language model started to solve this problem") ||
				text.includes("(Compacted") ||
				text.includes("_Local summary of prior discussion")
			) {
				return text;
			}
		}
	}
	return undefined;
}
