/**
 * Auto-generated by `scripts/headless-protocol-codegen.mjs`.
 * Do not edit manually; update `headless-protocol-payloads.manifest.json` instead.
 */

import { type Static, type TSchema, Type } from "@sinclair/typebox";
import {
	headlessApprovalModes,
	headlessConnectionRoles,
	headlessServerRequestTypes,
	headlessThinkingLevels,
	headlessUtilityCommandShellModes,
	headlessUtilityOperations,
} from "./headless-protocol-generated.js";

function stringLiteralUnion<const T extends readonly string[]>(values: T) {
	return Type.Unsafe<T[number]>(
		Type.Union(
			values.map((value) => Type.Literal(value)) as unknown as [
				TSchema,
				...TSchema[],
			],
		),
	);
}

export const HeadlessClientInfoSchema = Type.Object(
	{
		name: Type.String(),
		version: Type.Optional(Type.String()),
	},
	{ additionalProperties: false },
);

export const HeadlessClientCapabilitiesSchema = Type.Object(
	{
		server_requests: Type.Optional(
			Type.Array(stringLiteralUnion(headlessServerRequestTypes), {
				uniqueItems: true,
			}),
		),
		utility_operations: Type.Optional(
			Type.Array(stringLiteralUnion(headlessUtilityOperations), {
				uniqueItems: true,
			}),
		),
	},
	{ additionalProperties: false },
);

export const HeadlessToolResponseResultSchema = Type.Object(
	{
		success: Type.Boolean(),
		output: Type.String(),
		error: Type.Optional(Type.String()),
	},
	{ additionalProperties: false },
);

export const HeadlessTextContentSchema = Type.Object(
	{
		type: Type.Literal("text"),
		text: Type.String(),
	},
	{ additionalProperties: false },
);

export const HeadlessImageContentSchema = Type.Object(
	{
		type: Type.Literal("image"),
		data: Type.String(),
		mimeType: Type.String(),
	},
	{ additionalProperties: false },
);

export const HeadlessContentBlockSchema = Type.Union([
	HeadlessTextContentSchema,
	HeadlessImageContentSchema,
]);

export const HeadlessHelloMessageSchema = Type.Object(
	{
		type: Type.Literal("hello"),
		protocol_version: Type.Optional(Type.String()),
		client_info: Type.Optional(HeadlessClientInfoSchema),
		capabilities: Type.Optional(HeadlessClientCapabilitiesSchema),
		role: Type.Optional(stringLiteralUnion(headlessConnectionRoles)),
	},
	{ additionalProperties: false },
);

export const HeadlessInitMessageSchema = Type.Object(
	{
		type: Type.Literal("init"),
		system_prompt: Type.Optional(Type.String()),
		append_system_prompt: Type.Optional(Type.String()),
		thinking_level: Type.Optional(stringLiteralUnion(headlessThinkingLevels)),
		approval_mode: Type.Optional(stringLiteralUnion(headlessApprovalModes)),
	},
	{ additionalProperties: false },
);

export const HeadlessPromptMessageSchema = Type.Object(
	{
		type: Type.Literal("prompt"),
		content: Type.String(),
		attachments: Type.Optional(Type.Array(Type.String())),
	},
	{ additionalProperties: false },
);

export const HeadlessInterruptMessageSchema = Type.Object(
	{
		type: Type.Literal("interrupt"),
	},
	{ additionalProperties: false },
);

export const HeadlessToolResponseMessageSchema = Type.Object(
	{
		type: Type.Literal("tool_response"),
		call_id: Type.String(),
		approved: Type.Boolean(),
		result: Type.Optional(HeadlessToolResponseResultSchema),
	},
	{ additionalProperties: false },
);

export const HeadlessClientToolResultMessageSchema = Type.Object(
	{
		type: Type.Literal("client_tool_result"),
		call_id: Type.String(),
		content: Type.Array(HeadlessContentBlockSchema),
		is_error: Type.Boolean(),
	},
	{ additionalProperties: false },
);

export const HeadlessServerRequestResponseMessageSchema = Type.Object(
	{
		type: Type.Literal("server_request_response"),
		request_id: Type.String(),
		request_type: stringLiteralUnion(headlessServerRequestTypes),
		approved: Type.Optional(Type.Boolean()),
		result: Type.Optional(HeadlessToolResponseResultSchema),
		content: Type.Optional(Type.Array(HeadlessContentBlockSchema)),
		is_error: Type.Optional(Type.Boolean()),
	},
	{ additionalProperties: false },
);

export const HeadlessUtilityCommandStartMessageSchema = Type.Object(
	{
		type: Type.Literal("utility_command_start"),
		command_id: Type.String(),
		command: Type.String(),
		cwd: Type.Optional(Type.String()),
		env: Type.Optional(Type.Record(Type.String(), Type.String())),
		shell_mode: Type.Optional(
			stringLiteralUnion(headlessUtilityCommandShellModes),
		),
		allow_stdin: Type.Optional(Type.Boolean()),
	},
	{ additionalProperties: false },
);

export const HeadlessUtilityCommandTerminateMessageSchema = Type.Object(
	{
		type: Type.Literal("utility_command_terminate"),
		command_id: Type.String(),
		force: Type.Optional(Type.Boolean()),
	},
	{ additionalProperties: false },
);

export const HeadlessUtilityCommandStdinMessageSchema = Type.Object(
	{
		type: Type.Literal("utility_command_stdin"),
		command_id: Type.String(),
		content: Type.String(),
		eof: Type.Optional(Type.Boolean()),
	},
	{ additionalProperties: false },
);

export const HeadlessUtilityFileSearchMessageSchema = Type.Object(
	{
		type: Type.Literal("utility_file_search"),
		search_id: Type.String(),
		query: Type.String(),
		cwd: Type.Optional(Type.String()),
		limit: Type.Optional(Type.Number()),
	},
	{ additionalProperties: false },
);

export const HeadlessUtilityFileWatchStartMessageSchema = Type.Object(
	{
		type: Type.Literal("utility_file_watch_start"),
		watch_id: Type.String(),
		root_dir: Type.Optional(Type.String()),
		include_patterns: Type.Optional(Type.Array(Type.String())),
		exclude_patterns: Type.Optional(Type.Array(Type.String())),
		debounce_ms: Type.Optional(Type.Number()),
	},
	{ additionalProperties: false },
);

export const HeadlessUtilityFileWatchStopMessageSchema = Type.Object(
	{
		type: Type.Literal("utility_file_watch_stop"),
		watch_id: Type.String(),
	},
	{ additionalProperties: false },
);

export const HeadlessCancelMessageSchema = Type.Object(
	{
		type: Type.Literal("cancel"),
	},
	{ additionalProperties: false },
);

export const HeadlessShutdownMessageSchema = Type.Object(
	{
		type: Type.Literal("shutdown"),
	},
	{ additionalProperties: false },
);

export const headlessToAgentMessageSchemasByType = {
	hello: HeadlessHelloMessageSchema,
	init: HeadlessInitMessageSchema,
	prompt: HeadlessPromptMessageSchema,
	interrupt: HeadlessInterruptMessageSchema,
	tool_response: HeadlessToolResponseMessageSchema,
	client_tool_result: HeadlessClientToolResultMessageSchema,
	server_request_response: HeadlessServerRequestResponseMessageSchema,
	utility_command_start: HeadlessUtilityCommandStartMessageSchema,
	utility_command_terminate: HeadlessUtilityCommandTerminateMessageSchema,
	utility_command_stdin: HeadlessUtilityCommandStdinMessageSchema,
	utility_file_search: HeadlessUtilityFileSearchMessageSchema,
	utility_file_watch_start: HeadlessUtilityFileWatchStartMessageSchema,
	utility_file_watch_stop: HeadlessUtilityFileWatchStopMessageSchema,
	cancel: HeadlessCancelMessageSchema,
	shutdown: HeadlessShutdownMessageSchema,
} as const;

export const HeadlessToAgentMessageSchema = Type.Union([
	HeadlessHelloMessageSchema,
	HeadlessInitMessageSchema,
	HeadlessPromptMessageSchema,
	HeadlessInterruptMessageSchema,
	HeadlessToolResponseMessageSchema,
	HeadlessClientToolResultMessageSchema,
	HeadlessServerRequestResponseMessageSchema,
	HeadlessUtilityCommandStartMessageSchema,
	HeadlessUtilityCommandTerminateMessageSchema,
	HeadlessUtilityCommandStdinMessageSchema,
	HeadlessUtilityFileSearchMessageSchema,
	HeadlessUtilityFileWatchStartMessageSchema,
	HeadlessUtilityFileWatchStopMessageSchema,
	HeadlessCancelMessageSchema,
	HeadlessShutdownMessageSchema,
]);

export type HeadlessToAgentMessageInput = Static<
	typeof HeadlessToAgentMessageSchema
>;
