/**
 * Auto-generated by `scripts/headless-protocol-codegen.mjs`.
 * Do not edit manually; update `headless-protocol.manifest.json` instead.
 */

export const headlessProtocolVersion = "2026-04-02" as const;

export const headlessServerRequestTypes = [
	"approval",
	"client_tool",
	"user_input",
] as const;
export type HeadlessServerRequestType =
	(typeof headlessServerRequestTypes)[number];

export const headlessServerRequestResolutions = [
	"approved",
	"denied",
	"completed",
	"failed",
	"answered",
	"cancelled",
] as const;
export type HeadlessServerRequestResolution =
	(typeof headlessServerRequestResolutions)[number];

export const headlessServerRequestResolvedBy = [
	"user",
	"policy",
	"client",
	"runtime",
] as const;
export type HeadlessServerRequestResolvedBy =
	(typeof headlessServerRequestResolvedBy)[number];

export const headlessConnectionRoles = ["viewer", "controller"] as const;
export type HeadlessConnectionRole = (typeof headlessConnectionRoles)[number];

export const headlessThinkingLevels = [
	"off",
	"minimal",
	"low",
	"medium",
	"high",
	"ultra",
] as const;
export type HeadlessThinkingLevel = (typeof headlessThinkingLevels)[number];

export const headlessApprovalModes = ["auto", "prompt", "fail"] as const;
export type HeadlessApprovalMode = (typeof headlessApprovalModes)[number];

export const headlessErrorTypes = [
	"transient",
	"fatal",
	"tool",
	"cancelled",
	"protocol",
] as const;
export type HeadlessErrorType = (typeof headlessErrorTypes)[number];

export const headlessUtilityOperations = ["command_exec"] as const;
export type HeadlessUtilityOperation =
	(typeof headlessUtilityOperations)[number];

export const headlessUtilityCommandStreams = ["stdout", "stderr"] as const;
export type HeadlessUtilityCommandStream =
	(typeof headlessUtilityCommandStreams)[number];

export const headlessUtilityCommandShellModes = ["shell", "direct"] as const;
export type HeadlessUtilityCommandShellMode =
	(typeof headlessUtilityCommandShellModes)[number];
