/**
 * Auto-generated by `scripts/headless-protocol-codegen.mjs`.
 * Do not edit manually; update `headless-protocol-payloads.manifest.json` instead.
 */

import { type Static, type TSchema, Type } from "@sinclair/typebox";
import {
	headlessApprovalModes,
	headlessConnectionRoles,
	headlessErrorTypes,
	headlessNotificationTypes,
	headlessServerRequestResolutions,
	headlessServerRequestResolvedBy,
	headlessServerRequestTypes,
	headlessThinkingLevels,
	headlessToolRetryDecisionActions,
	headlessUtilityCommandShellModes,
	headlessUtilityCommandStreams,
	headlessUtilityCommandTerminalModes,
	headlessUtilityFileWatchChangeTypes,
	headlessUtilityOperations,
} from "./headless-protocol-generated.js";

function stringLiteralUnion<const T extends readonly string[]>(values: T) {
	return Type.Unsafe<T[number]>(
		Type.Union(
			values.map((value) => Type.Literal(value)) as unknown as [
				TSchema,
				...TSchema[],
			],
		),
	);
}

export const HeadlessClientInfoSchema = Type.Object(
	{
		name: Type.String(),
		version: Type.Optional(Type.String()),
	},
	{ additionalProperties: false },
);

export const HeadlessClientCapabilitiesSchema = Type.Object(
	{
		server_requests: Type.Optional(
			Type.Array(stringLiteralUnion(headlessServerRequestTypes), {
				uniqueItems: true,
			}),
		),
		utility_operations: Type.Optional(
			Type.Array(stringLiteralUnion(headlessUtilityOperations), {
				uniqueItems: true,
			}),
		),
	},
	{ additionalProperties: false },
);

export const HeadlessOptOutNotificationsSchema = Type.Array(
	stringLiteralUnion(headlessNotificationTypes),
	{ uniqueItems: true },
);

export const HeadlessToolResponseResultSchema = Type.Object(
	{
		success: Type.Boolean(),
		output: Type.String(),
		error: Type.Optional(Type.String()),
	},
	{ additionalProperties: false },
);

export const HeadlessTextContentSchema = Type.Object(
	{
		type: Type.Literal("text"),
		text: Type.String(),
	},
	{ additionalProperties: false },
);

export const HeadlessImageContentSchema = Type.Object(
	{
		type: Type.Literal("image"),
		data: Type.String(),
		mimeType: Type.String(),
	},
	{ additionalProperties: false },
);

export const HeadlessContentBlockSchema = Type.Union([
	HeadlessTextContentSchema,
	HeadlessImageContentSchema,
]);

export const HeadlessHelloMessageSchema = Type.Object(
	{
		type: Type.Literal("hello"),
		protocol_version: Type.Optional(Type.String()),
		client_info: Type.Optional(HeadlessClientInfoSchema),
		capabilities: Type.Optional(HeadlessClientCapabilitiesSchema),
		role: Type.Optional(stringLiteralUnion(headlessConnectionRoles)),
		opt_out_notifications: Type.Optional(
			Type.Array(stringLiteralUnion(headlessNotificationTypes)),
		),
	},
	{ additionalProperties: false },
);

export const HeadlessInitMessageSchema = Type.Object(
	{
		type: Type.Literal("init"),
		system_prompt: Type.Optional(Type.String()),
		append_system_prompt: Type.Optional(Type.String()),
		thinking_level: Type.Optional(stringLiteralUnion(headlessThinkingLevels)),
		approval_mode: Type.Optional(stringLiteralUnion(headlessApprovalModes)),
	},
	{ additionalProperties: false },
);

export const HeadlessPromptMessageSchema = Type.Object(
	{
		type: Type.Literal("prompt"),
		content: Type.String(),
		attachments: Type.Optional(Type.Array(Type.String())),
	},
	{ additionalProperties: false },
);

export const HeadlessInterruptMessageSchema = Type.Object(
	{
		type: Type.Literal("interrupt"),
	},
	{ additionalProperties: false },
);

export const HeadlessToolResponseMessageSchema = Type.Object(
	{
		type: Type.Literal("tool_response"),
		call_id: Type.String(),
		approved: Type.Boolean(),
		result: Type.Optional(HeadlessToolResponseResultSchema),
	},
	{ additionalProperties: false },
);

export const HeadlessClientToolResultMessageSchema = Type.Object(
	{
		type: Type.Literal("client_tool_result"),
		call_id: Type.String(),
		content: Type.Array(HeadlessContentBlockSchema),
		is_error: Type.Boolean(),
	},
	{ additionalProperties: false },
);

export const HeadlessServerRequestResponseMessageSchema = Type.Object(
	{
		type: Type.Literal("server_request_response"),
		request_id: Type.String(),
		request_type: stringLiteralUnion(headlessServerRequestTypes),
		approved: Type.Optional(Type.Boolean()),
		result: Type.Optional(HeadlessToolResponseResultSchema),
		decision_action: Type.Optional(
			stringLiteralUnion(headlessToolRetryDecisionActions),
		),
		reason: Type.Optional(Type.String()),
		content: Type.Optional(Type.Array(HeadlessContentBlockSchema)),
		is_error: Type.Optional(Type.Boolean()),
	},
	{ additionalProperties: false },
);

export const HeadlessUtilityCommandStartMessageSchema = Type.Object(
	{
		type: Type.Literal("utility_command_start"),
		command_id: Type.String(),
		command: Type.String(),
		cwd: Type.Optional(Type.String()),
		env: Type.Optional(Type.Record(Type.String(), Type.String())),
		shell_mode: Type.Optional(
			stringLiteralUnion(headlessUtilityCommandShellModes),
		),
		terminal_mode: Type.Optional(
			stringLiteralUnion(headlessUtilityCommandTerminalModes),
		),
		allow_stdin: Type.Optional(Type.Boolean()),
		columns: Type.Optional(Type.Number()),
		rows: Type.Optional(Type.Number()),
	},
	{ additionalProperties: false },
);

export const HeadlessUtilityCommandTerminateMessageSchema = Type.Object(
	{
		type: Type.Literal("utility_command_terminate"),
		command_id: Type.String(),
		force: Type.Optional(Type.Boolean()),
	},
	{ additionalProperties: false },
);

export const HeadlessUtilityCommandStdinMessageSchema = Type.Object(
	{
		type: Type.Literal("utility_command_stdin"),
		command_id: Type.String(),
		content: Type.String(),
		eof: Type.Optional(Type.Boolean()),
	},
	{ additionalProperties: false },
);

export const HeadlessUtilityCommandResizeMessageSchema = Type.Object(
	{
		type: Type.Literal("utility_command_resize"),
		command_id: Type.String(),
		columns: Type.Number(),
		rows: Type.Number(),
	},
	{ additionalProperties: false },
);

export const HeadlessUtilityFileSearchMessageSchema = Type.Object(
	{
		type: Type.Literal("utility_file_search"),
		search_id: Type.String(),
		query: Type.String(),
		cwd: Type.Optional(Type.String()),
		limit: Type.Optional(Type.Number()),
	},
	{ additionalProperties: false },
);

export const HeadlessUtilityFileReadMessageSchema = Type.Object(
	{
		type: Type.Literal("utility_file_read"),
		read_id: Type.String(),
		path: Type.String(),
		cwd: Type.Optional(Type.String()),
		offset: Type.Optional(Type.Number()),
		limit: Type.Optional(Type.Number()),
	},
	{ additionalProperties: false },
);

export const HeadlessUtilityFileWatchStartMessageSchema = Type.Object(
	{
		type: Type.Literal("utility_file_watch_start"),
		watch_id: Type.String(),
		root_dir: Type.Optional(Type.String()),
		include_patterns: Type.Optional(Type.Array(Type.String())),
		exclude_patterns: Type.Optional(Type.Array(Type.String())),
		debounce_ms: Type.Optional(Type.Number()),
	},
	{ additionalProperties: false },
);

export const HeadlessUtilityFileWatchStopMessageSchema = Type.Object(
	{
		type: Type.Literal("utility_file_watch_stop"),
		watch_id: Type.String(),
	},
	{ additionalProperties: false },
);

export const HeadlessCancelMessageSchema = Type.Object(
	{
		type: Type.Literal("cancel"),
	},
	{ additionalProperties: false },
);

export const HeadlessShutdownMessageSchema = Type.Object(
	{
		type: Type.Literal("shutdown"),
	},
	{ additionalProperties: false },
);

export const headlessToAgentMessageSchemasByType = {
	hello: HeadlessHelloMessageSchema,
	init: HeadlessInitMessageSchema,
	prompt: HeadlessPromptMessageSchema,
	interrupt: HeadlessInterruptMessageSchema,
	tool_response: HeadlessToolResponseMessageSchema,
	client_tool_result: HeadlessClientToolResultMessageSchema,
	server_request_response: HeadlessServerRequestResponseMessageSchema,
	utility_command_start: HeadlessUtilityCommandStartMessageSchema,
	utility_command_terminate: HeadlessUtilityCommandTerminateMessageSchema,
	utility_command_stdin: HeadlessUtilityCommandStdinMessageSchema,
	utility_command_resize: HeadlessUtilityCommandResizeMessageSchema,
	utility_file_search: HeadlessUtilityFileSearchMessageSchema,
	utility_file_read: HeadlessUtilityFileReadMessageSchema,
	utility_file_watch_start: HeadlessUtilityFileWatchStartMessageSchema,
	utility_file_watch_stop: HeadlessUtilityFileWatchStopMessageSchema,
	cancel: HeadlessCancelMessageSchema,
	shutdown: HeadlessShutdownMessageSchema,
} as const;

export const HeadlessHelloOkMessageSchema = Type.Object(
	{
		type: Type.Literal("hello_ok"),
		protocol_version: Type.String(),
		connection_id: Type.Optional(Type.String()),
		client_protocol_version: Type.Optional(Type.String()),
		client_info: Type.Optional(HeadlessClientInfoSchema),
		capabilities: Type.Optional(HeadlessClientCapabilitiesSchema),
		opt_out_notifications: Type.Optional(HeadlessOptOutNotificationsSchema),
		role: Type.Optional(stringLiteralUnion(headlessConnectionRoles)),
		controller_connection_id: Type.Optional(
			Type.Union([Type.String(), Type.Null()]),
		),
		lease_expires_at: Type.Optional(Type.Union([Type.String(), Type.Null()])),
	},
	{ additionalProperties: false },
);

export const HeadlessReadyMessageSchema = Type.Object(
	{
		type: Type.Literal("ready"),
		protocol_version: Type.String(),
		model: Type.String(),
		provider: Type.String(),
		session_id: Type.Union([Type.String(), Type.Null()]),
	},
	{ additionalProperties: false },
);

export const HeadlessResponseStartMessageSchema = Type.Object(
	{
		type: Type.Literal("response_start"),
		response_id: Type.String(),
	},
	{ additionalProperties: false },
);

export const HeadlessResponseChunkMessageSchema = Type.Object(
	{
		type: Type.Literal("response_chunk"),
		response_id: Type.String(),
		content: Type.String(),
		is_thinking: Type.Boolean(),
	},
	{ additionalProperties: false },
);

export const HeadlessResponseEndUsageSchema = Type.Object(
	{
		input_tokens: Type.Number(),
		output_tokens: Type.Number(),
		cache_read_tokens: Type.Number(),
		cache_write_tokens: Type.Number(),
		total_tokens: Type.Number(),
		total_cost_usd: Type.Number(),
		model_id: Type.String(),
		provider: Type.String(),
	},
	{ additionalProperties: false },
);

export const HeadlessToolsSummarySchema = Type.Object(
	{
		tools_used: Type.Array(Type.String()),
		calls_succeeded: Type.Number(),
		calls_failed: Type.Number(),
		summary_labels: Type.Optional(Type.Array(Type.String())),
	},
	{ additionalProperties: false },
);

export const HeadlessResponseEndMessageSchema = Type.Object(
	{
		type: Type.Literal("response_end"),
		response_id: Type.String(),
		usage: HeadlessResponseEndUsageSchema,
		tools_summary: HeadlessToolsSummarySchema,
		duration_ms: Type.Number(),
		ttft_ms: Type.Optional(Type.Number()),
	},
	{ additionalProperties: false },
);

export const HeadlessToolCallMessageSchema = Type.Object(
	{
		type: Type.Literal("tool_call"),
		call_id: Type.String(),
		tool: Type.String(),
		args: Type.Unknown(),
		requires_approval: Type.Boolean(),
	},
	{ additionalProperties: false },
);

export const HeadlessToolStartMessageSchema = Type.Object(
	{
		type: Type.Literal("tool_start"),
		call_id: Type.String(),
	},
	{ additionalProperties: false },
);

export const HeadlessToolOutputMessageSchema = Type.Object(
	{
		type: Type.Literal("tool_output"),
		call_id: Type.String(),
		content: Type.String(),
	},
	{ additionalProperties: false },
);

export const HeadlessToolEndMessageSchema = Type.Object(
	{
		type: Type.Literal("tool_end"),
		call_id: Type.String(),
		success: Type.Boolean(),
	},
	{ additionalProperties: false },
);

export const HeadlessClientToolRequestMessageSchema = Type.Object(
	{
		type: Type.Literal("client_tool_request"),
		call_id: Type.String(),
		tool: Type.String(),
		args: Type.Unknown(),
	},
	{ additionalProperties: false },
);

export const HeadlessServerRequestMessageSchema = Type.Object(
	{
		type: Type.Literal("server_request"),
		request_id: Type.String(),
		request_type: stringLiteralUnion(headlessServerRequestTypes),
		call_id: Type.String(),
		tool: Type.String(),
		args: Type.Unknown(),
		reason: Type.String(),
	},
	{ additionalProperties: false },
);

export const HeadlessServerRequestResolvedMessageSchema = Type.Object(
	{
		type: Type.Literal("server_request_resolved"),
		request_id: Type.String(),
		request_type: stringLiteralUnion(headlessServerRequestTypes),
		call_id: Type.String(),
		resolution: stringLiteralUnion(headlessServerRequestResolutions),
		reason: Type.Optional(Type.String()),
		resolved_by: stringLiteralUnion(headlessServerRequestResolvedBy),
	},
	{ additionalProperties: false },
);

export const HeadlessUtilityCommandStartedMessageSchema = Type.Object(
	{
		type: Type.Literal("utility_command_started"),
		command_id: Type.String(),
		command: Type.String(),
		cwd: Type.Optional(Type.String()),
		shell_mode: stringLiteralUnion(headlessUtilityCommandShellModes),
		terminal_mode: stringLiteralUnion(headlessUtilityCommandTerminalModes),
		pid: Type.Optional(Type.Number()),
		columns: Type.Optional(Type.Number()),
		rows: Type.Optional(Type.Number()),
		owner_connection_id: Type.Optional(Type.String()),
	},
	{ additionalProperties: false },
);

export const HeadlessUtilityCommandResizedMessageSchema = Type.Object(
	{
		type: Type.Literal("utility_command_resized"),
		command_id: Type.String(),
		columns: Type.Number(),
		rows: Type.Number(),
	},
	{ additionalProperties: false },
);

export const HeadlessUtilityCommandOutputMessageSchema = Type.Object(
	{
		type: Type.Literal("utility_command_output"),
		command_id: Type.String(),
		stream: stringLiteralUnion(headlessUtilityCommandStreams),
		content: Type.String(),
	},
	{ additionalProperties: false },
);

export const HeadlessUtilityCommandExitedMessageSchema = Type.Object(
	{
		type: Type.Literal("utility_command_exited"),
		command_id: Type.String(),
		success: Type.Boolean(),
		exit_code: Type.Optional(Type.Union([Type.Number(), Type.Null()])),
		signal: Type.Optional(Type.Union([Type.String(), Type.Null()])),
		reason: Type.Optional(Type.String()),
	},
	{ additionalProperties: false },
);

export const HeadlessUtilityFileSearchMatchSchema = Type.Object(
	{
		path: Type.String(),
		score: Type.Number(),
	},
	{ additionalProperties: false },
);

export const HeadlessUtilityFileSearchResultsMessageSchema = Type.Object(
	{
		type: Type.Literal("utility_file_search_results"),
		search_id: Type.String(),
		query: Type.String(),
		cwd: Type.String(),
		results: Type.Array(HeadlessUtilityFileSearchMatchSchema),
		truncated: Type.Boolean(),
	},
	{ additionalProperties: false },
);

export const HeadlessUtilityFileReadResultMessageSchema = Type.Object(
	{
		type: Type.Literal("utility_file_read_result"),
		read_id: Type.String(),
		path: Type.String(),
		relative_path: Type.String(),
		cwd: Type.String(),
		content: Type.String(),
		start_line: Type.Number(),
		end_line: Type.Number(),
		total_lines: Type.Number(),
		truncated: Type.Boolean(),
	},
	{ additionalProperties: false },
);

export const HeadlessUtilityFileWatchStartedMessageSchema = Type.Object(
	{
		type: Type.Literal("utility_file_watch_started"),
		watch_id: Type.String(),
		root_dir: Type.String(),
		include_patterns: Type.Optional(Type.Array(Type.String())),
		exclude_patterns: Type.Optional(Type.Array(Type.String())),
		debounce_ms: Type.Number(),
		owner_connection_id: Type.Optional(Type.String()),
	},
	{ additionalProperties: false },
);

export const HeadlessUtilityFileWatchEventMessageSchema = Type.Object(
	{
		type: Type.Literal("utility_file_watch_event"),
		watch_id: Type.String(),
		change_type: stringLiteralUnion(headlessUtilityFileWatchChangeTypes),
		path: Type.String(),
		relative_path: Type.String(),
		timestamp: Type.Number(),
		is_directory: Type.Boolean(),
	},
	{ additionalProperties: false },
);

export const HeadlessUtilityFileWatchStoppedMessageSchema = Type.Object(
	{
		type: Type.Literal("utility_file_watch_stopped"),
		watch_id: Type.String(),
		reason: Type.Optional(Type.String()),
	},
	{ additionalProperties: false },
);

export const HeadlessErrorMessageSchema = Type.Object(
	{
		type: Type.Literal("error"),
		request_id: Type.Optional(Type.String()),
		message: Type.String(),
		fatal: Type.Boolean(),
		error_type: stringLiteralUnion(headlessErrorTypes),
	},
	{ additionalProperties: false },
);

export const HeadlessStatusMessageSchema = Type.Object(
	{
		type: Type.Literal("status"),
		message: Type.String(),
	},
	{ additionalProperties: false },
);

export const HeadlessCompactionMessageSchema = Type.Object(
	{
		type: Type.Literal("compaction"),
		summary: Type.String(),
		first_kept_entry_index: Type.Number(),
		tokens_before: Type.Number(),
		auto: Type.Boolean(),
		custom_instructions: Type.Optional(Type.String()),
		timestamp: Type.String(),
	},
	{ additionalProperties: false },
);

export const HeadlessSessionInfoMessageSchema = Type.Object(
	{
		type: Type.Literal("session_info"),
		session_id: Type.Union([Type.String(), Type.Null()]),
		cwd: Type.String(),
		git_branch: Type.Union([Type.String(), Type.Null()]),
	},
	{ additionalProperties: false },
);

export const HeadlessConnectionStateSchema = Type.Object(
	{
		connection_id: Type.String(),
		role: stringLiteralUnion(headlessConnectionRoles),
		client_protocol_version: Type.Optional(Type.String()),
		client_info: Type.Optional(HeadlessClientInfoSchema),
		capabilities: Type.Optional(HeadlessClientCapabilitiesSchema),
		opt_out_notifications: Type.Optional(
			Type.Array(stringLiteralUnion(headlessNotificationTypes)),
		),
		subscription_count: Type.Number(),
		attached_subscription_count: Type.Number(),
		controller_lease_granted: Type.Boolean(),
		lease_expires_at: Type.Optional(Type.Union([Type.String(), Type.Null()])),
	},
	{ additionalProperties: false },
);

export const HeadlessConnectionInfoMessageSchema = Type.Object(
	{
		type: Type.Literal("connection_info"),
		connection_id: Type.Optional(Type.String()),
		client_protocol_version: Type.Optional(Type.String()),
		client_info: Type.Optional(HeadlessClientInfoSchema),
		capabilities: Type.Optional(HeadlessClientCapabilitiesSchema),
		opt_out_notifications: Type.Optional(
			Type.Array(stringLiteralUnion(headlessNotificationTypes)),
		),
		role: Type.Optional(stringLiteralUnion(headlessConnectionRoles)),
		connection_count: Type.Optional(Type.Number()),
		controller_connection_id: Type.Optional(
			Type.Union([Type.String(), Type.Null()]),
		),
		lease_expires_at: Type.Optional(Type.Union([Type.String(), Type.Null()])),
		connections: Type.Optional(Type.Array(HeadlessConnectionStateSchema)),
	},
	{ additionalProperties: false },
);

export const headlessFromAgentMessageSchemasByType = {
	hello_ok: HeadlessHelloOkMessageSchema,
	ready: HeadlessReadyMessageSchema,
	response_start: HeadlessResponseStartMessageSchema,
	response_chunk: HeadlessResponseChunkMessageSchema,
	response_end: HeadlessResponseEndMessageSchema,
	tool_call: HeadlessToolCallMessageSchema,
	tool_start: HeadlessToolStartMessageSchema,
	tool_output: HeadlessToolOutputMessageSchema,
	tool_end: HeadlessToolEndMessageSchema,
	client_tool_request: HeadlessClientToolRequestMessageSchema,
	server_request: HeadlessServerRequestMessageSchema,
	server_request_resolved: HeadlessServerRequestResolvedMessageSchema,
	utility_command_started: HeadlessUtilityCommandStartedMessageSchema,
	utility_command_resized: HeadlessUtilityCommandResizedMessageSchema,
	utility_command_output: HeadlessUtilityCommandOutputMessageSchema,
	utility_command_exited: HeadlessUtilityCommandExitedMessageSchema,
	utility_file_search_results: HeadlessUtilityFileSearchResultsMessageSchema,
	utility_file_read_result: HeadlessUtilityFileReadResultMessageSchema,
	utility_file_watch_started: HeadlessUtilityFileWatchStartedMessageSchema,
	utility_file_watch_event: HeadlessUtilityFileWatchEventMessageSchema,
	utility_file_watch_stopped: HeadlessUtilityFileWatchStoppedMessageSchema,
	error: HeadlessErrorMessageSchema,
	status: HeadlessStatusMessageSchema,
	compaction: HeadlessCompactionMessageSchema,
	session_info: HeadlessSessionInfoMessageSchema,
	connection_info: HeadlessConnectionInfoMessageSchema,
} as const;

export const HeadlessToAgentMessageSchema = Type.Union([
	HeadlessHelloMessageSchema,
	HeadlessInitMessageSchema,
	HeadlessPromptMessageSchema,
	HeadlessInterruptMessageSchema,
	HeadlessToolResponseMessageSchema,
	HeadlessClientToolResultMessageSchema,
	HeadlessServerRequestResponseMessageSchema,
	HeadlessUtilityCommandStartMessageSchema,
	HeadlessUtilityCommandTerminateMessageSchema,
	HeadlessUtilityCommandStdinMessageSchema,
	HeadlessUtilityCommandResizeMessageSchema,
	HeadlessUtilityFileSearchMessageSchema,
	HeadlessUtilityFileReadMessageSchema,
	HeadlessUtilityFileWatchStartMessageSchema,
	HeadlessUtilityFileWatchStopMessageSchema,
	HeadlessCancelMessageSchema,
	HeadlessShutdownMessageSchema,
]);

export type HeadlessToAgentMessageInput = Static<
	typeof HeadlessToAgentMessageSchema
>;

export const HeadlessFromAgentMessageSchema = Type.Union([
	HeadlessHelloOkMessageSchema,
	HeadlessReadyMessageSchema,
	HeadlessResponseStartMessageSchema,
	HeadlessResponseChunkMessageSchema,
	HeadlessResponseEndMessageSchema,
	HeadlessToolCallMessageSchema,
	HeadlessToolStartMessageSchema,
	HeadlessToolOutputMessageSchema,
	HeadlessToolEndMessageSchema,
	HeadlessClientToolRequestMessageSchema,
	HeadlessServerRequestMessageSchema,
	HeadlessServerRequestResolvedMessageSchema,
	HeadlessUtilityCommandStartedMessageSchema,
	HeadlessUtilityCommandResizedMessageSchema,
	HeadlessUtilityCommandOutputMessageSchema,
	HeadlessUtilityCommandExitedMessageSchema,
	HeadlessUtilityFileSearchResultsMessageSchema,
	HeadlessUtilityFileReadResultMessageSchema,
	HeadlessUtilityFileWatchStartedMessageSchema,
	HeadlessUtilityFileWatchEventMessageSchema,
	HeadlessUtilityFileWatchStoppedMessageSchema,
	HeadlessErrorMessageSchema,
	HeadlessStatusMessageSchema,
	HeadlessCompactionMessageSchema,
	HeadlessSessionInfoMessageSchema,
	HeadlessConnectionInfoMessageSchema,
]);

export type HeadlessFromAgentMessageInput = Static<
	typeof HeadlessFromAgentMessageSchema
>;

export const HeadlessPendingToolStateSchema = Type.Object(
	{
		call_id: Type.String(),
		request_id: Type.Optional(Type.String()),
		tool: Type.String(),
		args: Type.Unknown(),
	},
	{ additionalProperties: false },
);

export const HeadlessActiveToolStateSchema = Type.Object(
	{
		call_id: Type.String(),
		tool: Type.String(),
		output: Type.String(),
	},
	{ additionalProperties: false },
);

export const HeadlessStreamingResponseStateSchema = Type.Object(
	{
		response_id: Type.String(),
		text: Type.String(),
		thinking: Type.String(),
		usage: Type.Optional(HeadlessResponseEndUsageSchema),
	},
	{ additionalProperties: false },
);

export const HeadlessActiveUtilityCommandStateSchema = Type.Object(
	{
		command_id: Type.String(),
		command: Type.String(),
		cwd: Type.Optional(Type.String()),
		shell_mode: stringLiteralUnion(headlessUtilityCommandShellModes),
		terminal_mode: stringLiteralUnion(headlessUtilityCommandTerminalModes),
		pid: Type.Optional(Type.Number()),
		columns: Type.Optional(Type.Number()),
		rows: Type.Optional(Type.Number()),
		owner_connection_id: Type.Optional(Type.String()),
		output: Type.String(),
	},
	{ additionalProperties: false },
);

export const HeadlessActiveFileWatchStateSchema = Type.Object(
	{
		watch_id: Type.String(),
		root_dir: Type.String(),
		include_patterns: Type.Optional(Type.Array(Type.String())),
		exclude_patterns: Type.Optional(Type.Array(Type.String())),
		debounce_ms: Type.Number(),
		owner_connection_id: Type.Optional(Type.String()),
	},
	{ additionalProperties: false },
);

export const HeadlessRuntimeStateSchema = Type.Object(
	{
		protocol_version: Type.Optional(Type.String()),
		client_protocol_version: Type.Optional(Type.String()),
		client_info: Type.Optional(HeadlessClientInfoSchema),
		capabilities: Type.Optional(HeadlessClientCapabilitiesSchema),
		opt_out_notifications: Type.Optional(
			Type.Array(stringLiteralUnion(headlessNotificationTypes)),
		),
		connection_role: Type.Optional(stringLiteralUnion(headlessConnectionRoles)),
		connection_count: Type.Number(),
		subscriber_count: Type.Number(),
		controller_subscription_id: Type.Optional(
			Type.Union([Type.String(), Type.Null()]),
		),
		controller_connection_id: Type.Optional(
			Type.Union([Type.String(), Type.Null()]),
		),
		connections: Type.Array(HeadlessConnectionStateSchema),
		model: Type.Optional(Type.String()),
		provider: Type.Optional(Type.String()),
		session_id: Type.Optional(Type.Union([Type.String(), Type.Null()])),
		cwd: Type.Optional(Type.String()),
		git_branch: Type.Optional(Type.Union([Type.String(), Type.Null()])),
		current_response: Type.Optional(HeadlessStreamingResponseStateSchema),
		pending_approvals: Type.Array(HeadlessPendingToolStateSchema),
		pending_client_tools: Type.Array(HeadlessPendingToolStateSchema),
		pending_user_inputs: Type.Array(HeadlessPendingToolStateSchema),
		pending_tool_retries: Type.Array(HeadlessPendingToolStateSchema),
		active_tools: Type.Array(HeadlessActiveToolStateSchema),
		active_utility_commands: Type.Array(
			HeadlessActiveUtilityCommandStateSchema,
		),
		active_file_watches: Type.Array(HeadlessActiveFileWatchStateSchema),
		tracked_tools: Type.Array(HeadlessPendingToolStateSchema),
		last_error: Type.Optional(Type.String()),
		last_error_type: Type.Optional(stringLiteralUnion(headlessErrorTypes)),
		last_status: Type.Optional(Type.String()),
		last_response_duration_ms: Type.Optional(Type.Number()),
		last_ttft_ms: Type.Optional(Type.Number()),
		is_ready: Type.Boolean(),
		is_responding: Type.Boolean(),
	},
	{ additionalProperties: false },
);

export const HeadlessRuntimeSnapshotSchema = Type.Object(
	{
		protocolVersion: Type.String(),
		session_id: Type.String(),
		cursor: Type.Number(),
		last_init: Type.Union([HeadlessInitMessageSchema, Type.Null()]),
		state: HeadlessRuntimeStateSchema,
	},
	{ additionalProperties: false },
);

export const HeadlessRuntimeSnapshotEnvelopeSchema = Type.Object(
	{
		type: Type.Literal("snapshot"),
		snapshot: HeadlessRuntimeSnapshotSchema,
	},
	{ additionalProperties: false },
);

export const HeadlessRuntimeEventEnvelopeSchema = Type.Object(
	{
		type: Type.Literal("message"),
		cursor: Type.Number(),
		message: HeadlessFromAgentMessageSchema,
	},
	{ additionalProperties: false },
);

export const HeadlessRuntimeHeartbeatEnvelopeSchema = Type.Object(
	{
		type: Type.Literal("heartbeat"),
		cursor: Type.Number(),
	},
	{ additionalProperties: false },
);

export const HeadlessRuntimeResetEnvelopeSchema = Type.Object(
	{
		type: Type.Literal("reset"),
		reason: Type.Union([Type.Literal("lagged"), Type.Literal("replay_gap")]),
		snapshot: HeadlessRuntimeSnapshotSchema,
	},
	{ additionalProperties: false },
);

export const HeadlessRuntimeStreamEnvelopeSchema = Type.Union([
	HeadlessRuntimeSnapshotEnvelopeSchema,
	HeadlessRuntimeEventEnvelopeSchema,
	HeadlessRuntimeHeartbeatEnvelopeSchema,
	HeadlessRuntimeResetEnvelopeSchema,
]);

export const HeadlessRuntimeSubscriptionSnapshotSchema = Type.Object(
	{
		connection_id: Type.String(),
		subscription_id: Type.String(),
		opt_out_notifications: Type.Optional(HeadlessOptOutNotificationsSchema),
		role: stringLiteralUnion(headlessConnectionRoles),
		controller_lease_granted: Type.Boolean(),
		controller_subscription_id: Type.Union([Type.String(), Type.Null()]),
		controller_connection_id: Type.Union([Type.String(), Type.Null()]),
		lease_expires_at: Type.Union([Type.String(), Type.Null()]),
		heartbeat_interval_ms: Type.Number(),
		snapshot: HeadlessRuntimeSnapshotSchema,
	},
	{ additionalProperties: false },
);

export const HeadlessRuntimeHeartbeatSnapshotSchema = Type.Object(
	{
		connection_id: Type.String(),
		controller_lease_granted: Type.Boolean(),
		controller_connection_id: Type.Union([Type.String(), Type.Null()]),
		lease_expires_at: Type.Union([Type.String(), Type.Null()]),
		heartbeat_interval_ms: Type.Number(),
	},
	{ additionalProperties: false },
);
