export const EVALOPS_ACCESS_TOKEN_ENV_VARS = [
	"MAESTRO_EVALOPS_ACCESS_TOKEN",
	"EVALOPS_TOKEN",
] as const;

export const EVALOPS_ORGANIZATION_ID_ENV_VARS = [
	"MAESTRO_EVALOPS_ORG_ID",
	"EVALOPS_ORGANIZATION_ID",
	"EVALOPS_ORG_ID",
	"MAESTRO_ENTERPRISE_ORG_ID",
] as const;

export const EVALOPS_WORKSPACE_ID_ENV_VARS = [
	"MAESTRO_EVALOPS_WORKSPACE_ID",
	"EVALOPS_WORKSPACE_ID",
] as const;
