/**
 * Database migration runner for Composer
 *
 * Uses drizzle-orm's migrate function to apply SQL migrations
 * from the migrations folder generated by drizzle-kit.
 */

import { existsSync, readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { sql } from "drizzle-orm";
import { createLogger } from "../utils/logger.js";
import { getDb, isDatabaseConfigured } from "./client.js";

const logger = createLogger("db:migrate");

const __dirname = dirname(fileURLToPath(import.meta.url));
const MIGRATIONS_DIR = join(__dirname, "migrations");

interface MigrationJournal {
	version: string;
	dialect: string;
	entries: Array<{
		idx: number;
		version: string;
		when: number;
		tag: string;
		breakpoints: boolean;
	}>;
}

interface MigrationRecord {
	tag: string;
	applied_at: Date;
}

/**
 * Get the list of migrations from the journal
 */
function getMigrationEntries(): MigrationJournal["entries"] {
	const journalPath = join(MIGRATIONS_DIR, "meta", "_journal.json");

	if (!existsSync(journalPath)) {
		logger.warn("No migration journal found", { path: journalPath });
		return [];
	}

	try {
		const journal: MigrationJournal = JSON.parse(
			readFileSync(journalPath, "utf-8"),
		);
		return journal.entries;
	} catch (error) {
		logger.error(
			"Failed to read migration journal",
			error instanceof Error ? error : undefined,
		);
		return [];
	}
}

/**
 * Get the SQL content for a migration
 */
function getMigrationSql(tag: string): string | null {
	const migrationPath = join(MIGRATIONS_DIR, `${tag}.sql`);

	if (!existsSync(migrationPath)) {
		logger.error("Migration file not found", undefined, {
			path: migrationPath,
		});
		return null;
	}

	return readFileSync(migrationPath, "utf-8");
}

/**
 * Ensure the migrations tracking table exists
 */
async function ensureMigrationsTable(): Promise<void> {
	const db = getDb();

	await db.execute(sql`
		CREATE TABLE IF NOT EXISTS _composer_migrations (
			id SERIAL PRIMARY KEY,
			tag VARCHAR(255) NOT NULL UNIQUE,
			applied_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
		)
	`);
}

/**
 * Get applied migrations from the database
 */
async function getAppliedMigrations(): Promise<Set<string>> {
	const db = getDb();

	try {
		const results = await db.execute(sql`
			SELECT tag FROM _composer_migrations ORDER BY id
		`);

		const tags = new Set<string>();
		for (const row of results as unknown as Array<{ tag: string }>) {
			tags.add(row.tag);
		}
		return tags;
	} catch {
		// Table might not exist yet
		return new Set();
	}
}

/**
 * Mark a migration as applied
 */
async function markMigrationApplied(tag: string): Promise<void> {
	const db = getDb();

	await db.execute(sql`
		INSERT INTO _composer_migrations (tag) VALUES (${tag})
		ON CONFLICT (tag) DO NOTHING
	`);
}

/**
 * Remove a migration from the applied list (for rollback)
 */
async function markMigrationRolledBack(tag: string): Promise<void> {
	const db = getDb();

	await db.execute(sql`
		DELETE FROM _composer_migrations WHERE tag = ${tag}
	`);
}

/**
 * Parse and execute migration SQL with statement breakpoints
 *
 * drizzle-kit uses `--> statement-breakpoint` comments to separate statements
 */
async function executeMigrationSql(sqlContent: string): Promise<void> {
	const db = getDb();

	// Split on the breakpoint markers
	const statements = sqlContent
		.split("--> statement-breakpoint")
		.map((s) => s.trim())
		.filter((s) => s.length > 0);

	for (const statement of statements) {
		await db.execute(sql.raw(statement));
	}
}

/**
 * Run pending migrations
 *
 * Returns the number of migrations applied.
 */
export async function migrate(): Promise<number> {
	if (!isDatabaseConfigured()) {
		logger.warn("Database not configured, skipping migrations");
		return 0;
	}

	logger.info("Starting database migrations");

	await ensureMigrationsTable();
	const appliedMigrations = await getAppliedMigrations();
	const migrationEntries = getMigrationEntries();

	let applied = 0;

	for (const entry of migrationEntries) {
		if (appliedMigrations.has(entry.tag)) {
			logger.debug("Migration already applied", { tag: entry.tag });
			continue;
		}

		const sqlContent = getMigrationSql(entry.tag);
		if (!sqlContent) {
			throw new Error(`Migration file not found for tag: ${entry.tag}`);
		}

		logger.info("Applying migration", { tag: entry.tag });

		try {
			await executeMigrationSql(sqlContent);
			await markMigrationApplied(entry.tag);
			applied++;
			logger.info("Migration applied successfully", { tag: entry.tag });
		} catch (error) {
			logger.error(
				`Migration failed: ${entry.tag}`,
				error instanceof Error ? error : undefined,
			);
			throw error;
		}
	}

	if (applied === 0) {
		logger.info("No pending migrations");
	} else {
		logger.info("Migrations completed", { appliedCount: applied });
	}

	return applied;
}

/**
 * Get migration status
 */
export async function getMigrationStatus(): Promise<{
	pending: string[];
	applied: string[];
}> {
	if (!isDatabaseConfigured()) {
		return { pending: [], applied: [] };
	}

	await ensureMigrationsTable();
	const appliedMigrations = await getAppliedMigrations();
	const migrationEntries = getMigrationEntries();

	const pending: string[] = [];
	const applied: string[] = [];

	for (const entry of migrationEntries) {
		if (appliedMigrations.has(entry.tag)) {
			applied.push(entry.tag);
		} else {
			pending.push(entry.tag);
		}
	}

	return { pending, applied };
}

/**
 * Rollback the last applied migration.
 *
 * WARNING: This only removes the migration from the tracking table.
 * It does NOT undo schema changes. For that, you need to manually
 * write and execute reverse SQL or restore from backup.
 *
 * Returns the tag of the rolled back migration, or null if none.
 */
export async function rollbackLast(): Promise<string | null> {
	if (!isDatabaseConfigured()) {
		logger.warn("Database not configured, cannot rollback");
		return null;
	}

	await ensureMigrationsTable();
	const appliedMigrations = await getAppliedMigrations();
	const migrationEntries = getMigrationEntries();

	// Find the last applied migration
	let lastApplied: string | null = null;
	for (const entry of migrationEntries) {
		if (appliedMigrations.has(entry.tag)) {
			lastApplied = entry.tag;
		}
	}

	if (!lastApplied) {
		logger.info("No migrations to rollback");
		return null;
	}

	logger.warn("Rolling back migration", { tag: lastApplied });
	logger.warn(
		"WARNING: This only removes the migration record. Schema changes are NOT reversed.",
	);

	await markMigrationRolledBack(lastApplied);

	logger.info("Migration rolled back", { tag: lastApplied });
	return lastApplied;
}

/**
 * Force mark a migration as applied without running it.
 * Useful for marking manually applied migrations.
 */
export async function forceMarkApplied(tag: string): Promise<void> {
	if (!isDatabaseConfigured()) {
		throw new Error("Database not configured");
	}

	await ensureMigrationsTable();
	await markMigrationApplied(tag);
	logger.info("Migration force-marked as applied", { tag });
}

/**
 * CLI entry point for running migrations
 *
 * Usage:
 *   bun run src/db/migrate.ts              - Run pending migrations
 *   bun run src/db/migrate.ts status       - Show migration status
 *   bun run src/db/migrate.ts rollback     - Rollback last migration
 *   bun run src/db/migrate.ts force <tag>  - Force mark a migration as applied
 */
export async function runMigrationsCli(): Promise<void> {
	const args = process.argv.slice(2);
	const command = args[0] || "migrate";

	try {
		switch (command) {
			case "migrate": {
				const applied = await migrate();
				console.log(`Applied ${applied} migration(s)`);
				break;
			}

			case "status": {
				const status = await getMigrationStatus();
				console.log("Migration Status:");
				console.log(`  Applied: ${status.applied.length}`);
				for (const tag of status.applied) {
					console.log(`    ✓ ${tag}`);
				}
				console.log(`  Pending: ${status.pending.length}`);
				for (const tag of status.pending) {
					console.log(`    ○ ${tag}`);
				}
				break;
			}

			case "rollback": {
				const rolledBack = await rollbackLast();
				if (rolledBack) {
					console.log(`Rolled back: ${rolledBack}`);
					console.log(
						"WARNING: Schema changes were NOT reversed. Manual cleanup may be needed.",
					);
				} else {
					console.log("No migrations to rollback");
				}
				break;
			}

			case "force": {
				const tag = args[1];
				if (!tag) {
					console.error("Usage: migrate force <tag>");
					process.exit(1);
				}
				await forceMarkApplied(tag);
				console.log(`Force-marked as applied: ${tag}`);
				break;
			}

			default:
				console.error(`Unknown command: ${command}`);
				console.error("Usage:");
				console.error("  migrate           - Run pending migrations");
				console.error("  migrate status    - Show migration status");
				console.error("  migrate rollback  - Rollback last migration");
				console.error(
					"  migrate force <tag> - Force mark migration as applied",
				);
				process.exit(1);
		}

		process.exit(0);
	} catch (error) {
		console.error("Migration failed:", error);
		process.exit(1);
	}
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
	runMigrationsCli();
}
