/**
 * Database migration runner for Composer
 *
 * Uses drizzle-orm's migrate function to apply SQL migrations
 * from the migrations folder generated by drizzle-kit.
 */

import { existsSync, readFileSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { sql } from "drizzle-orm";
import { createLogger } from "../utils/logger.js";
import { getDb, isDatabaseConfigured } from "./client.js";

const logger = createLogger("db:migrate");

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const MIGRATIONS_DIR = join(__dirname, "migrations");

interface MigrationJournal {
	version: string;
	dialect: string;
	entries: Array<{
		idx: number;
		version: string;
		when: number;
		tag: string;
		breakpoints: boolean;
	}>;
}

interface MigrationRecord {
	tag: string;
	applied_at: Date;
}

export interface InitialSchemaMarker {
	kind: "constraint" | "index" | "table" | "type";
	name: string;
	exists: boolean;
}

export interface InitialSchemaState {
	exists: boolean;
	partial: boolean;
	present: string[];
	missing: string[];
}

type InitialSchemaMarkerDefinition = Pick<InitialSchemaMarker, "kind" | "name">;

// Full 0000_initial baseline, except audit_hash_cache objects repaired by 0007.
export const INITIAL_SCHEMA_BASELINE_MARKERS = [
	{ kind: "type", name: "alert_severity" },
	{ kind: "type", name: "audit_status" },
	{ kind: "type", name: "model_approval_status" },
	{ kind: "type", name: "user_role" },
	{ kind: "type", name: "webhook_delivery_status" },
	{ kind: "table", name: "alerts" },
	{ kind: "table", name: "api_keys" },
	{ kind: "table", name: "audit_logs" },
	{ kind: "table", name: "directory_access_rules" },
	{ kind: "table", name: "distributed_locks" },
	{ kind: "table", name: "model_approvals" },
	{ kind: "table", name: "org_memberships" },
	{ kind: "table", name: "organizations" },
	{ kind: "table", name: "permissions" },
	{ kind: "table", name: "revoked_tokens" },
	{ kind: "table", name: "role_permissions" },
	{ kind: "table", name: "roles" },
	{ kind: "table", name: "session_messages" },
	{ kind: "table", name: "sessions" },
	{ kind: "table", name: "totp_rate_limits" },
	{ kind: "table", name: "totp_used_codes" },
	{ kind: "table", name: "user_revocation_timestamps" },
	{ kind: "table", name: "users" },
	{ kind: "table", name: "webhook_deliveries" },
	{ kind: "constraint", name: "organizations_slug_unique" },
	{ kind: "constraint", name: "revoked_tokens_token_hash_unique" },
	{ kind: "constraint", name: "totp_rate_limits_user_id_unique" },
	{
		kind: "constraint",
		name: "user_revocation_timestamps_user_id_unique",
	},
	{ kind: "constraint", name: "users_email_unique" },
	{ kind: "constraint", name: "alerts_org_id_organizations_id_fk" },
	{ kind: "constraint", name: "alerts_user_id_users_id_fk" },
	{ kind: "constraint", name: "api_keys_org_id_organizations_id_fk" },
	{ kind: "constraint", name: "api_keys_user_id_users_id_fk" },
	{ kind: "constraint", name: "audit_logs_org_id_organizations_id_fk" },
	{ kind: "constraint", name: "audit_logs_user_id_users_id_fk" },
	{ kind: "constraint", name: "audit_logs_session_id_sessions_id_fk" },
	{
		kind: "constraint",
		name: "directory_access_rules_org_id_organizations_id_fk",
	},
	{ kind: "constraint", name: "model_approvals_org_id_organizations_id_fk" },
	{ kind: "constraint", name: "model_approvals_approved_by_users_id_fk" },
	{ kind: "constraint", name: "org_memberships_org_id_organizations_id_fk" },
	{ kind: "constraint", name: "org_memberships_user_id_users_id_fk" },
	{ kind: "constraint", name: "org_memberships_role_id_roles_id_fk" },
	{ kind: "constraint", name: "revoked_tokens_user_id_users_id_fk" },
	{ kind: "constraint", name: "revoked_tokens_org_id_organizations_id_fk" },
	{ kind: "constraint", name: "revoked_tokens_revoked_by_users_id_fk" },
	{ kind: "constraint", name: "role_permissions_role_id_roles_id_fk" },
	{
		kind: "constraint",
		name: "role_permissions_permission_id_permissions_id_fk",
	},
	{ kind: "constraint", name: "roles_org_id_organizations_id_fk" },
	{ kind: "constraint", name: "session_messages_session_id_sessions_id_fk" },
	{ kind: "constraint", name: "sessions_org_id_organizations_id_fk" },
	{ kind: "constraint", name: "sessions_user_id_users_id_fk" },
	{ kind: "constraint", name: "totp_rate_limits_user_id_users_id_fk" },
	{ kind: "constraint", name: "totp_used_codes_user_id_users_id_fk" },
	{
		kind: "constraint",
		name: "user_revocation_timestamps_user_id_users_id_fk",
	},
	{
		kind: "constraint",
		name: "user_revocation_timestamps_revoked_by_users_id_fk",
	},
	{ kind: "constraint", name: "users_default_org_id_organizations_id_fk" },
	{ kind: "constraint", name: "webhook_deliveries_org_id_organizations_id_fk" },
	{ kind: "index", name: "alert_org_user_idx" },
	{ kind: "index", name: "alert_type_idx" },
	{ kind: "index", name: "alert_unread_idx" },
	{ kind: "index", name: "api_key_org_user_idx" },
	{ kind: "index", name: "api_key_prefix_idx" },
	{ kind: "index", name: "audit_log_org_user_idx" },
	{ kind: "index", name: "audit_log_action_idx" },
	{ kind: "index", name: "audit_log_resource_idx" },
	{ kind: "index", name: "audit_log_session_idx" },
	{ kind: "index", name: "audit_log_trace_idx" },
	{ kind: "index", name: "audit_log_org_created_idx" },
	{ kind: "index", name: "dir_access_org_idx" },
	{ kind: "index", name: "distributed_lock_expires_idx" },
	{ kind: "index", name: "model_approval_org_model_idx" },
	{ kind: "index", name: "model_approval_status_idx" },
	{ kind: "index", name: "org_membership_org_user_idx" },
	{ kind: "index", name: "org_membership_user_idx" },
	{ kind: "index", name: "org_slug_idx" },
	{ kind: "index", name: "org_active_idx" },
	{ kind: "index", name: "permission_resource_action_idx" },
	{ kind: "index", name: "revoked_token_hash_idx" },
	{ kind: "index", name: "revoked_token_user_idx" },
	{ kind: "index", name: "revoked_token_expires_idx" },
	{ kind: "index", name: "role_permission_pk" },
	{ kind: "index", name: "role_org_name_idx" },
	{ kind: "index", name: "session_message_session_idx" },
	{ kind: "index", name: "session_message_pii_idx" },
	{ kind: "index", name: "session_org_user_idx" },
	{ kind: "index", name: "session_user_idx" },
	{ kind: "index", name: "session_created_idx" },
	{ kind: "index", name: "totp_rate_limit_user_idx" },
	{ kind: "index", name: "totp_rate_limit_locked_idx" },
	{ kind: "index", name: "totp_used_code_user_idx" },
	{ kind: "index", name: "totp_used_code_window_idx" },
	{ kind: "index", name: "user_revocation_user_idx" },
	{ kind: "index", name: "user_email_idx" },
	{ kind: "index", name: "user_active_idx" },
	{ kind: "index", name: "webhook_delivery_org_status_idx" },
	{ kind: "index", name: "webhook_delivery_retry_idx" },
] as const;

function firstRow(results: unknown): Record<string, unknown> | null {
	const rows = Array.from(results as Iterable<Record<string, unknown>>);
	return rows[0] ?? null;
}

function sqlBoolean(value: unknown): boolean {
	return value === true || value === "true" || value === 1 || value === "1";
}

/**
 * Get the list of migrations from the journal
 */
function getMigrationEntries(): MigrationJournal["entries"] {
	const journalPath = join(MIGRATIONS_DIR, "meta", "_journal.json");

	if (!existsSync(journalPath)) {
		logger.warn("No migration journal found", { path: journalPath });
		return [];
	}

	try {
		const journal: MigrationJournal = JSON.parse(
			readFileSync(journalPath, "utf-8"),
		);
		return journal.entries;
	} catch (error) {
		logger.error(
			"Failed to read migration journal",
			error instanceof Error ? error : undefined,
		);
		return [];
	}
}

/**
 * Get the SQL content for a migration
 */
function getMigrationSql(tag: string): string | null {
	const migrationPath = join(MIGRATIONS_DIR, `${tag}.sql`);

	if (!existsSync(migrationPath)) {
		logger.error("Migration file not found", undefined, {
			path: migrationPath,
		});
		return null;
	}

	return readFileSync(migrationPath, "utf-8");
}

/**
 * Ensure the migrations tracking table exists
 */
async function ensureMigrationsTable(): Promise<void> {
	const db = getDb();

	await db.execute(sql`
		CREATE TABLE IF NOT EXISTS _composer_migrations (
			id SERIAL PRIMARY KEY,
			tag VARCHAR(255) NOT NULL UNIQUE,
			applied_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
		)
	`);
}

/**
 * Get applied migrations from the database
 */
async function getAppliedMigrations(): Promise<Set<string>> {
	const db = getDb();

	try {
		const results = await db.execute(sql`
			SELECT tag FROM _composer_migrations ORDER BY id
		`);

		const tags = new Set<string>();
		const rows = Array.from(results) as Array<Record<string, unknown>>;
		for (const row of rows) {
			const tag = row.tag;
			if (typeof tag === "string") {
				tags.add(tag);
			}
		}
		return tags;
	} catch {
		// Table might not exist yet
		return new Set();
	}
}

/**
 * Mark a migration as applied
 */
async function markMigrationApplied(tag: string): Promise<void> {
	const db = getDb();

	await db.execute(sql`
		INSERT INTO _composer_migrations (tag) VALUES (${tag})
		ON CONFLICT (tag) DO NOTHING
	`);
}

async function relationExists(relationName: string): Promise<boolean> {
	const db = getDb();

	const result = await db.execute(sql`
		SELECT to_regclass(${`public.${relationName}`}) IS NOT NULL AS exists
	`);

	return sqlBoolean(firstRow(result)?.exists);
}

async function constraintExists(constraintName: string): Promise<boolean> {
	const db = getDb();

	const result = await db.execute(sql`
		SELECT EXISTS (
			SELECT 1
			FROM pg_constraint c
			JOIN pg_namespace n ON n.oid = c.connamespace
			WHERE n.nspname = 'public' AND c.conname = ${constraintName}
		) AS exists
	`);

	return sqlBoolean(firstRow(result)?.exists);
}

async function enumTypeExists(typeName: string): Promise<boolean> {
	const db = getDb();

	const result = await db.execute(sql`
		SELECT EXISTS (
			SELECT 1
			FROM pg_type t
			JOIN pg_namespace n ON n.oid = t.typnamespace
			WHERE n.nspname = 'public' AND t.typname = ${typeName}
		) AS exists
	`);

	return sqlBoolean(firstRow(result)?.exists);
}

function markerLabel(marker: InitialSchemaMarkerDefinition): string {
	return `${marker.kind}:${marker.name}`;
}

export function classifyInitialSchemaMarkers(
	markers: InitialSchemaMarker[],
): InitialSchemaState {
	const present = markers.filter((marker) => marker.exists).map(markerLabel);
	const missing = markers.filter((marker) => !marker.exists).map(markerLabel);

	return {
		exists: missing.length === 0,
		partial: present.length > 0 && missing.length > 0,
		present,
		missing,
	};
}

async function getInitialSchemaState(): Promise<InitialSchemaState> {
	const markers = await Promise.all(
		INITIAL_SCHEMA_BASELINE_MARKERS.map(async (marker) => {
			if (marker.kind === "constraint") {
				return {
					...marker,
					exists: await constraintExists(marker.name),
				};
			}

			if (marker.kind === "type") {
				return { ...marker, exists: await enumTypeExists(marker.name) };
			}

			return { ...marker, exists: await relationExists(marker.name) };
		}),
	);

	return classifyInitialSchemaMarkers(markers);
}

async function reconcileLegacyMigrationRecords(
	migrationEntries: MigrationJournal["entries"],
	appliedMigrations: Set<string>,
): Promise<void> {
	for (const entry of migrationEntries) {
		if (entry.tag !== "0000_initial" || appliedMigrations.has(entry.tag)) {
			continue;
		}

		const initialSchemaState = await getInitialSchemaState();
		if (initialSchemaState.partial) {
			throw new Error(
				`Detected a partial legacy initial schema before ${entry.tag}; refusing to mark it applied or replay it. Missing markers: ${initialSchemaState.missing.join(", ")}`,
			);
		}
		if (!initialSchemaState.exists) {
			continue;
		}

		logger.warn(
			"Detected existing initial schema for untracked migration; marking as applied",
			{ tag: entry.tag, presentMarkers: initialSchemaState.present },
		);
		await markMigrationApplied(entry.tag);
		appliedMigrations.add(entry.tag);
	}
}

/**
 * Remove a migration from the applied list (for rollback)
 */
async function markMigrationRolledBack(tag: string): Promise<void> {
	const db = getDb();

	await db.execute(sql`
		DELETE FROM _composer_migrations WHERE tag = ${tag}
	`);
}

/**
 * Parse and execute migration SQL with statement breakpoints
 *
 * drizzle-kit uses `--> statement-breakpoint` comments to separate statements
 */
async function executeMigrationSql(sqlContent: string): Promise<void> {
	const db = getDb();

	// Split on the breakpoint markers
	const statements = sqlContent
		.split("--> statement-breakpoint")
		.map((s) => s.trim())
		.filter((s) => s.length > 0);

	for (const statement of statements) {
		await db.execute(sql.raw(statement));
	}
}

/**
 * Run pending migrations
 *
 * Returns the number of migrations applied.
 */
export async function migrate(): Promise<number> {
	if (!isDatabaseConfigured()) {
		logger.warn("Database not configured, skipping migrations");
		return 0;
	}

	logger.info("Starting database migrations");

	await ensureMigrationsTable();
	const appliedMigrations = await getAppliedMigrations();
	const migrationEntries = getMigrationEntries();
	await reconcileLegacyMigrationRecords(migrationEntries, appliedMigrations);

	let applied = 0;

	for (const entry of migrationEntries) {
		if (appliedMigrations.has(entry.tag)) {
			logger.debug("Migration already applied", { tag: entry.tag });
			continue;
		}

		const sqlContent = getMigrationSql(entry.tag);
		if (!sqlContent) {
			throw new Error(`Migration file not found for tag: ${entry.tag}`);
		}

		logger.info("Applying migration", { tag: entry.tag });

		try {
			await executeMigrationSql(sqlContent);
			await markMigrationApplied(entry.tag);
			applied++;
			logger.info("Migration applied successfully", { tag: entry.tag });
		} catch (error) {
			logger.error(
				`Migration failed: ${entry.tag}`,
				error instanceof Error ? error : undefined,
			);
			throw error;
		}
	}

	if (applied === 0) {
		logger.info("No pending migrations");
	} else {
		logger.info("Migrations completed", { appliedCount: applied });
	}

	return applied;
}

/**
 * Get migration status
 */
export async function getMigrationStatus(): Promise<{
	pending: string[];
	applied: string[];
}> {
	if (!isDatabaseConfigured()) {
		return { pending: [], applied: [] };
	}

	await ensureMigrationsTable();
	const appliedMigrations = await getAppliedMigrations();
	const migrationEntries = getMigrationEntries();

	const pending: string[] = [];
	const applied: string[] = [];

	for (const entry of migrationEntries) {
		if (appliedMigrations.has(entry.tag)) {
			applied.push(entry.tag);
		} else {
			pending.push(entry.tag);
		}
	}

	return { pending, applied };
}

/**
 * Rollback the last applied migration.
 *
 * WARNING: This only removes the migration from the tracking table.
 * It does NOT undo schema changes. For that, you need to manually
 * write and execute reverse SQL or restore from backup.
 *
 * Returns the tag of the rolled back migration, or null if none.
 */
export async function rollbackLast(): Promise<string | null> {
	if (!isDatabaseConfigured()) {
		logger.warn("Database not configured, cannot rollback");
		return null;
	}

	await ensureMigrationsTable();
	const appliedMigrations = await getAppliedMigrations();
	const migrationEntries = getMigrationEntries();

	// Find the last applied migration
	let lastApplied: string | null = null;
	for (const entry of migrationEntries) {
		if (appliedMigrations.has(entry.tag)) {
			lastApplied = entry.tag;
		}
	}

	if (!lastApplied) {
		logger.info("No migrations to rollback");
		return null;
	}

	logger.warn("Rolling back migration", { tag: lastApplied });
	logger.warn(
		"WARNING: This only removes the migration record. Schema changes are NOT reversed.",
	);

	await markMigrationRolledBack(lastApplied);

	logger.info("Migration rolled back", { tag: lastApplied });
	return lastApplied;
}

/**
 * Force mark a migration as applied without running it.
 * Useful for marking manually applied migrations.
 */
export async function forceMarkApplied(tag: string): Promise<void> {
	if (!isDatabaseConfigured()) {
		throw new Error("Database not configured");
	}

	await ensureMigrationsTable();
	await markMigrationApplied(tag);
	logger.info("Migration force-marked as applied", { tag });
}

/**
 * CLI entry point for running migrations
 *
 * Usage:
 *   bun run src/db/migrate.ts              - Run pending migrations
 *   bun run src/db/migrate.ts status       - Show migration status
 *   bun run src/db/migrate.ts rollback     - Rollback last migration
 *   bun run src/db/migrate.ts force <tag>  - Force mark a migration as applied
 */
export async function runMigrationsCli(): Promise<void> {
	const args = process.argv.slice(2);
	const command = args[0] || "migrate";

	try {
		switch (command) {
			case "migrate": {
				const applied = await migrate();
				console.log(`Applied ${applied} migration(s)`);
				break;
			}

			case "status": {
				const status = await getMigrationStatus();
				console.log("Migration Status:");
				console.log(`  Applied: ${status.applied.length}`);
				for (const tag of status.applied) {
					console.log(`    ✓ ${tag}`);
				}
				console.log(`  Pending: ${status.pending.length}`);
				for (const tag of status.pending) {
					console.log(`    ○ ${tag}`);
				}
				break;
			}

			case "rollback": {
				const rolledBack = await rollbackLast();
				if (rolledBack) {
					console.log(`Rolled back: ${rolledBack}`);
					console.log(
						"WARNING: Schema changes were NOT reversed. Manual cleanup may be needed.",
					);
				} else {
					console.log("No migrations to rollback");
				}
				break;
			}

			case "force": {
				const tag = args[1];
				if (!tag) {
					console.error("Usage: migrate force <tag>");
					process.exit(1);
				}
				await forceMarkApplied(tag);
				console.log(`Force-marked as applied: ${tag}`);
				break;
			}

			default:
				console.error(`Unknown command: ${command}`);
				console.error("Usage:");
				console.error("  migrate           - Run pending migrations");
				console.error("  migrate status    - Show migration status");
				console.error("  migrate rollback  - Rollback last migration");
				console.error(
					"  migrate force <tag> - Force mark migration as applied",
				);
				process.exit(1);
		}

		process.exit(0);
	} catch (error) {
		console.error("Migration failed:", error);
		process.exit(1);
	}
}

// Run if called directly
if (process.argv[1] && __filename === resolve(process.argv[1])) {
	runMigrationsCli();
}
