import type { ThemeJson } from "./theme-schema.js";

export const embeddedThemes: Record<
	"dark" | "light" | "high-contrast",
	ThemeJson
> = {
	dark: {
		$schema: "./theme-schema.json",
		name: "dark",
		vars: {
			// Primary palette
			sky: "#7dd3fc",
			amber: "#fbbf24",
			violet: "#c084fc",
			// Semantic colors (softer variants)
			softGreen: "#86efac",
			softRed: "#fca5a5",
			softYellow: "#fde047",
			softBlue: "#93c5fd",
			// Text hierarchy
			textSecondary: "#94a3b8",
			textMuted: "#64748b",
			// Borders
			borderDim: "#334155",
			borderSubtle: "#475569",
			// Legacy/compat
			cyan: "#7dd3fc",
			blue: "#60a5fa",
			green: "#86efac",
			red: "#fca5a5",
			yellow: "#fde047",
			coral: "#fb923c",
			gray: "#94a3b8",
			dimGray: "#64748b",
			darkGray: "#475569",
			accent: "#7dd3fc",
			userMsgBg: "#1e293b",
			toolPendingBg: "#1e293b",
			toolSuccessBg: "#14532d20",
			toolErrorBg: "#7f1d1d20",
		},
		colors: {
			accent: "sky",
			accentWarm: "amber",
			border: "softBlue",
			borderAccent: "sky",
			borderMuted: "borderDim",
			success: "softGreen",
			error: "softRed",
			warning: "softYellow",
			muted: "textSecondary",
			dim: "textMuted",
			text: "",
			userMessageBg: "userMsgBg",
			userMessageText: "",
			toolPendingBg: "toolPendingBg",
			toolSuccessBg: "toolSuccessBg",
			toolErrorBg: "toolErrorBg",
			toolTitle: "",
			toolOutput: "textSecondary",
			mdHeading: "amber",
			mdLink: "softBlue",
			mdLinkUrl: "textMuted",
			mdCode: "sky",
			mdCodeBlock: "softGreen",
			mdCodeBlockBorder: "borderSubtle",
			mdQuote: "softBlue",
			mdQuoteBorder: "sky",
			mdHr: "borderSubtle",
			mdListBullet: "sky",
			toolDiffAdded: "softGreen",
			toolDiffRemoved: "softRed",
			toolDiffContext: "textMuted",
			syntaxComment: "textMuted",
			syntaxKeyword: "violet",
			syntaxFunction: "softBlue",
			syntaxVariable: "",
			syntaxString: "softGreen",
			syntaxNumber: "amber",
			syntaxType: "sky",
			syntaxOperator: "",
			syntaxPunctuation: "textSecondary",
			thinkingOff: "borderDim",
			thinkingMinimal: "textMuted",
			thinkingLow: "softBlue",
			thinkingMedium: "sky",
			thinkingHigh: "violet",
		},
	},
	light: {
		$schema: "./theme-schema.json",
		name: "light",
		vars: {
			// Primary palette (darker for light backgrounds)
			sky: "#0284c7",
			amber: "#d97706",
			violet: "#7c3aed",
			// Semantic colors
			softGreen: "#15803d",
			softRed: "#dc2626",
			softYellow: "#ca8a04",
			softBlue: "#2563eb",
			// Text hierarchy
			textSecondary: "#64748b",
			textMuted: "#94a3b8",
			// Borders
			borderDim: "#e2e8f0",
			borderSubtle: "#cbd5e1",
			// Legacy/compat
			teal: "#0d9488",
			blue: "#2563eb",
			green: "#15803d",
			red: "#dc2626",
			yellow: "#ca8a04",
			coral: "#ea580c",
			mediumGray: "#64748b",
			dimGray: "#94a3b8",
			lightGray: "#e2e8f0",
			userMsgBg: "#f1f5f9",
			toolPendingBg: "#f8fafc",
			toolSuccessBg: "#f0fdf4",
			toolErrorBg: "#fef2f2",
		},
		colors: {
			accent: "sky",
			accentWarm: "amber",
			border: "softBlue",
			borderAccent: "sky",
			borderMuted: "borderDim",
			success: "softGreen",
			error: "softRed",
			warning: "softYellow",
			muted: "textSecondary",
			dim: "textMuted",
			text: "",
			userMessageBg: "userMsgBg",
			userMessageText: "",
			toolPendingBg: "toolPendingBg",
			toolSuccessBg: "toolSuccessBg",
			toolErrorBg: "toolErrorBg",
			toolTitle: "",
			toolOutput: "textSecondary",
			mdHeading: "amber",
			mdLink: "softBlue",
			mdLinkUrl: "textMuted",
			mdCode: "sky",
			mdCodeBlock: "softGreen",
			mdCodeBlockBorder: "borderSubtle",
			mdQuote: "textSecondary",
			mdQuoteBorder: "borderSubtle",
			mdHr: "borderSubtle",
			mdListBullet: "sky",
			toolDiffAdded: "softGreen",
			toolDiffRemoved: "softRed",
			toolDiffContext: "textMuted",
			syntaxComment: "textMuted",
			syntaxKeyword: "violet",
			syntaxFunction: "softBlue",
			syntaxVariable: "",
			syntaxString: "softGreen",
			syntaxNumber: "amber",
			syntaxType: "sky",
			syntaxOperator: "",
			syntaxPunctuation: "textSecondary",
			thinkingOff: "borderDim",
			thinkingMinimal: "textMuted",
			thinkingLow: "softBlue",
			thinkingMedium: "sky",
			thinkingHigh: "violet",
		},
	},
	"high-contrast": {
		$schema: "./theme-schema.json",
		name: "high-contrast",
		vars: {
			// High contrast primary palette
			brightCyan: "#00ffff",
			brightYellow: "#ffff00",
			brightMagenta: "#ff00ff",
			// High contrast semantic colors
			brightGreen: "#00ff00",
			brightRed: "#ff0000",
			brightWhite: "#ffffff",
			brightBlue: "#0080ff",
			// Text hierarchy - maximum contrast
			textPrimary: "#ffffff",
			textSecondary: "#e0e0e0",
			// Borders - visible
			borderBright: "#808080",
			borderDim: "#404040",
			// Backgrounds
			userMsgBg: "#1a1a2e",
			toolPendingBg: "#1a1a2e",
			toolSuccessBg: "#002200",
			toolErrorBg: "#220000",
		},
		colors: {
			accent: "brightCyan",
			accentWarm: "brightYellow",
			border: "brightBlue",
			borderAccent: "brightCyan",
			borderMuted: "borderBright",
			success: "brightGreen",
			error: "brightRed",
			warning: "brightYellow",
			muted: "textSecondary",
			dim: "textSecondary",
			text: "textPrimary",
			userMessageBg: "userMsgBg",
			userMessageText: "textPrimary",
			toolPendingBg: "toolPendingBg",
			toolSuccessBg: "toolSuccessBg",
			toolErrorBg: "toolErrorBg",
			toolTitle: "textPrimary",
			toolOutput: "textSecondary",
			mdHeading: "brightYellow",
			mdLink: "brightCyan",
			mdLinkUrl: "brightBlue",
			mdCode: "brightCyan",
			mdCodeBlock: "brightGreen",
			mdCodeBlockBorder: "borderBright",
			mdQuote: "textSecondary",
			mdQuoteBorder: "borderBright",
			mdHr: "borderBright",
			mdListBullet: "brightCyan",
			toolDiffAdded: "brightGreen",
			toolDiffRemoved: "brightRed",
			toolDiffContext: "textSecondary",
			syntaxComment: "textSecondary",
			syntaxKeyword: "brightMagenta",
			syntaxFunction: "brightCyan",
			syntaxVariable: "textPrimary",
			syntaxString: "brightGreen",
			syntaxNumber: "brightYellow",
			syntaxType: "brightBlue",
			syntaxOperator: "textPrimary",
			syntaxPunctuation: "textSecondary",
			thinkingOff: "borderDim",
			thinkingMinimal: "textSecondary",
			thinkingLow: "brightBlue",
			thinkingMedium: "brightCyan",
			thinkingHigh: "brightMagenta",
		},
	},
};
