/**
 * Auto-generated by `scripts/session-wire-format-codegen.mjs`.
 * Do not edit manually; update `src/session/wire-format.manifest.json` instead.
 */

export const sessionWireFormatVersion = "session-wire-format.v1" as const;

export const sessionWireStopReasonAliases = {
	tool_use: "toolUse",
	tool_calls: "toolUse",
	max_tokens: "length",
	end_turn: "stop",
	stop_sequence: "stop",
} as const;

export const sessionWireFieldAliases = {
	modelMetadata: {
		model_id: "modelId",
		provider_name: "providerName",
		base_url: "baseUrl",
		context_window: "contextWindow",
		max_tokens: "maxTokens",
	},
	session: {
		model_metadata: "modelMetadata",
		thinking_level: "thinkingLevel",
		system_prompt: "systemPrompt",
		prompt_metadata: "promptMetadata",
		branched_from: "branchedFrom",
		parent_session: "parentSession",
	},
	sessionMeta: {
		resume_summary: "resumeSummary",
		memory_extraction_hash: "memoryExtractionHash",
	},
	attachmentExtract: {
		attachment_id: "attachmentId",
		extracted_text: "extractedText",
	},
	assistantMessage: {
		stop_reason: "stopReason",
	},
	toolResultMessage: {
		tool_call_id: "toolCallId",
		tool_name: "toolName",
		is_error: "isError",
	},
	thinkingLevelChange: {
		thinking_level: "thinkingLevel",
	},
	modelChange: {
		model_metadata: "modelMetadata",
	},
	compaction: {
		first_kept_entry_id: "firstKeptEntryId",
		first_kept_entry_index: "firstKeptEntryIndex",
		tokens_before: "tokensBefore",
		custom_instructions: "customInstructions",
	},
	branchSummary: {
		from_id: "fromId",
		from_hook: "fromHook",
	},
	custom: {
		custom_type: "customType",
	},
	customMessage: {
		custom_type: "customType",
	},
	label: {
		target_id: "targetId",
	},
} as const;

export const sessionWireContentBlockTypeAliases = {
	tool_call: "toolCall",
} as const;

export const sessionWireContentBlockFieldAliases = {
	toolCall: {
		args: "arguments",
	},
	thinking: {
		text: "thinking",
		signature: "thinkingSignature",
	},
} as const;

export const sessionWireCompactionContextEntryTypes = [
	"message",
	"custom_message",
	"branch_summary",
] as const;

export const sessionWireCompactionContextExcludedMessageRoles = [
	"toolResult",
] as const;

type SessionWireAliasSource = Readonly<Record<string, unknown>>;

function getSessionWireAlias<T extends SessionWireAliasSource>(
	aliases: T,
	key: string,
): T[keyof T] | undefined {
	return Object.prototype.hasOwnProperty.call(aliases, key)
		? aliases[key as keyof T]
		: undefined;
}

export function canonicalSessionWireStopReason(reason: string): string {
	return getSessionWireAlias(sessionWireStopReasonAliases, reason) ?? reason;
}

export function canonicalSessionWireContentBlockType(type: string): string {
	return getSessionWireAlias(sessionWireContentBlockTypeAliases, type) ?? type;
}

export function getSessionWireContentBlockFieldAliases(type: string) {
	return getSessionWireAlias(sessionWireContentBlockFieldAliases, type);
}

export function isSessionWireCompactionContextEntryType(type: string): boolean {
	return sessionWireCompactionContextEntryTypes.includes(
		type as (typeof sessionWireCompactionContextEntryTypes)[number],
	);
}

export function isSessionWireCompactionExcludedMessageRole(
	role: string,
): boolean {
	return sessionWireCompactionContextExcludedMessageRoles.includes(
		role as (typeof sessionWireCompactionContextExcludedMessageRoles)[number],
	);
}
