import type { SessionEntry } from "../../session/types.js";
import type { AppMessage, AssistantMessage, Usage } from "../types.js";

/**
 * Configuration for compaction behavior.
 */
export interface CompactionSettings {
	/** Whether auto-compaction is enabled */
	enabled: boolean;
	/**
	 * Tokens to reserve for summary generation and safety margin.
	 * Default: 16384 (~13k for summary + ~3k safety margin)
	 */
	reserveTokens: number;
	/**
	 * Approximate number of recent tokens to preserve verbatim.
	 * Default: 20000 (recent context preserved without summarization)
	 */
	keepRecentTokens: number;
}

/**
 * Default compaction settings based on research into Claude Code, Codex, and OpenCode.
 */
export const DEFAULT_COMPACTION_SETTINGS: CompactionSettings = {
	enabled: true,
	reserveTokens: 16384,
	keepRecentTokens: 20000,
};

/**
 * Calculate total context tokens from usage metadata.
 *
 * This includes all token types that contribute to context window consumption:
 * - input: Tokens from user/system messages
 * - output: Tokens generated by the model
 * - cacheRead: Tokens read from prompt cache
 * - cacheWrite: Tokens written to prompt cache
 *
 * @param usage - Usage metadata from an assistant message
 * @returns Total context token count
 */
export function calculateContextTokens(usage: Usage): number {
	return usage.input + usage.output + usage.cacheRead + usage.cacheWrite;
}

/**
 * Extract usage metadata from a message if it's a non-aborted assistant message.
 *
 * @param msg - Any application message
 * @returns Usage metadata or null if not available/applicable
 */
function getAssistantUsage(msg: AppMessage): Usage | null {
	if (msg.role === "assistant") {
		const assistantMsg = msg as AssistantMessage;
		if (
			assistantMsg.stopReason !== "aborted" &&
			assistantMsg.stopReason !== "error" &&
			assistantMsg.usage
		) {
			return assistantMsg.usage;
		}
	}
	return null;
}

/**
 * Find the last non-aborted assistant message usage from a message array.
 *
 * Used to determine current context window consumption. Walks backwards
 * to find the most recent valid usage metadata.
 *
 * @param messages - Array of application messages
 * @returns Usage metadata from the last assistant message, or null
 */
export function getLastAssistantUsage(messages: AppMessage[]): Usage | null {
	for (let i = messages.length - 1; i >= 0; i--) {
		const usage = getAssistantUsage(messages[i]!);
		if (usage) return usage;
	}
	return null;
}

/**
 * Find the last non-aborted assistant message usage from session entries.
 *
 * @param entries - Array of session entries
 * @returns Usage metadata from the last assistant message, or null
 */
export function getLastAssistantUsageFromEntries(
	entries: SessionEntry[],
): Usage | null {
	for (let i = entries.length - 1; i >= 0; i--) {
		const entry = entries[i];
		if (!entry) continue;
		if (entry.type === "message") {
			const usage = getAssistantUsage(entry.message as AppMessage);
			if (usage) return usage;
		}
	}
	return null;
}

// ============================================================================
// Compaction Trigger Detection
// ============================================================================

/**
 * Determine if compaction should trigger based on current context usage.
 *
 * Compaction triggers when context usage exceeds `contextWindow - reserveTokens`,
 * leaving enough room for summary generation plus a safety margin.
 *
 * @param contextTokens - Current context window usage in tokens
 * @param contextWindow - Model's total context window size
 * @param settings - Compaction configuration
 * @returns true if compaction should trigger
 */
export function shouldCompact(
	contextTokens: number,
	contextWindow: number,
	settings: CompactionSettings,
): boolean {
	if (!settings.enabled) return false;
	return contextTokens > contextWindow - settings.reserveTokens;
}

/**
 * Calculate context usage percentage.
 *
 * @param contextTokens - Current context window usage in tokens
 * @param contextWindow - Model's total context window size
 * @returns Percentage of context window used (0-100)
 */
export function calculateUsagePercent(
	contextTokens: number,
	contextWindow: number,
): number {
	if (contextWindow <= 0) return 0;
	return (contextTokens / contextWindow) * 100;
}

// ============================================================================
// Cut Point Detection
// ============================================================================

/**
 * Result of finding a cut point, including split turn information.
 */
export interface CutPointResult {
	/** Index of first message to keep (messages before this are summarized) */
	firstKeptIndex: number;
	/** Index of user message that starts the turn being split, or -1 if not splitting */
	turnStartIndex: number;
	/** Whether this cut splits a turn (cut point is not a user message) */
	isSplitTurn: boolean;
}

/**
 * Find indices of user messages (turn boundaries) in a message array.
 *
 * Turn boundaries are important because we never want to split a turn
 * (user message + assistant response + tool results). Cutting at a user
 * message ensures turn integrity.
 *
 * @param messages - Array of messages to scan
 * @param startIndex - First index to consider (inclusive)
 * @param endIndex - Last index to consider (exclusive)
 * @returns Array of indices where user messages appear
 */
export function findTurnBoundaries(
	messages: AppMessage[],
	startIndex: number,
	endIndex: number,
): number[] {
	const boundaries: number[] = [];
	for (let i = startIndex; i < endIndex; i++) {
		if (messages[i]!.role === "user") {
			boundaries.push(i);
		}
	}
	return boundaries;
}

/**
 * Find the user message that starts the turn containing the given index.
 *
 * @param messages - Array of messages
 * @param entryIndex - Index of the message to find the turn start for
 * @param startIndex - First index to consider (inclusive)
 * @returns Index of the user message that starts this turn, or -1 if not found
 */
export function findTurnStartIndex(
	messages: AppMessage[],
	entryIndex: number,
	startIndex: number,
): number {
	for (let i = entryIndex; i >= startIndex; i--) {
		if (messages[i]!.role === "user") {
			return i;
		}
	}
	return -1;
}

/**
 * Find the optimal cut point in messages that preserves `keepRecentTokens`.
 *
 * The algorithm:
 * 1. Find all turn boundaries (user message indices)
 * 2. Walk backwards collecting assistant token usage
 * 3. Find where cumulative token difference exceeds keepRecentTokens
 * 4. Return the nearest turn boundary at or before that point
 *
 * This ensures:
 * - Recent context is preserved based on actual token usage, not message count
 * - Turn integrity is maintained (user/assistant/toolResult groups stay together)
 * - More context is kept when messages are small, less when large
 *
 * @param messages - Array of messages to analyze
 * @param startIndex - First index to consider for cutting
 * @param endIndex - Last index to consider (exclusive)
 * @param keepRecentTokens - Approximate tokens to preserve
 * @returns Index of first message to keep (messages before this are summarized)
 */
export function findCutPoint(
	messages: AppMessage[],
	startIndex: number,
	endIndex: number,
	keepRecentTokens: number,
): number {
	const boundaries = findTurnBoundaries(messages, startIndex, endIndex);

	if (boundaries.length === 0) {
		return startIndex; // No user messages, keep everything in range
	}

	// Collect assistant usages walking backwards from endIndex
	const assistantUsages: Array<{ index: number; tokens: number }> = [];
	for (let i = endIndex - 1; i >= startIndex; i--) {
		const usage = getAssistantUsage(messages[i]!);
		if (usage) {
			assistantUsages.push({
				index: i,
				tokens: calculateContextTokens(usage),
			});
		}
	}

	if (assistantUsages.length === 0) {
		// No usage info, keep last turn only
		return boundaries[boundaries.length - 1]!;
	}

	// Walk through and find where cumulative token difference exceeds keepRecentTokens
	const newestTokens = assistantUsages[0]!.tokens;
	let cutIndex = startIndex; // Default: keep everything in range

	for (let i = 1; i < assistantUsages.length; i++) {
		const tokenDiff = newestTokens - assistantUsages[i]!.tokens;
		if (tokenDiff >= keepRecentTokens) {
			// Find the turn boundary at or before the assistant we want to keep
			const lastKeptAssistantIndex = assistantUsages[i - 1]!.index;

			for (let b = boundaries.length - 1; b >= 0; b--) {
				const boundary = boundaries[b];
				if (boundary !== undefined && boundary <= lastKeptAssistantIndex) {
					cutIndex = boundary;
					break;
				}
			}
			break;
		}
	}

	return cutIndex;
}

/**
 * Find valid cut points (user or assistant messages, not tool results).
 * Tool results must stay with their preceding tool call.
 *
 * @param messages - Array of messages to scan
 * @param startIndex - First index to consider (inclusive)
 * @param endIndex - Last index to consider (exclusive)
 * @returns Array of indices where valid cut points exist
 */
function findValidCutPoints(
	messages: AppMessage[],
	startIndex: number,
	endIndex: number,
): number[] {
	const cutPoints: number[] = [];
	for (let i = startIndex; i < endIndex; i++) {
		const role = messages[i]!.role;
		// user and assistant are valid cut points
		// toolResult must stay with its preceding tool call
		if (role === "user" || role === "assistant") {
			cutPoints.push(i);
		}
	}
	return cutPoints;
}

/**
 * Find the optimal cut point with split turn information.
 *
 * Similar to findCutPoint but:
 * - Can cut at assistant messages (not just user messages)
 * - Returns information about whether we're splitting a turn
 *
 * This allows for more aggressive compaction when turns are very large,
 * while providing the context needed to summarize the split turn prefix.
 *
 * @param messages - Array of messages to analyze
 * @param startIndex - First index to consider for cutting
 * @param endIndex - Last index to consider (exclusive)
 * @param keepRecentTokens - Approximate tokens to preserve
 * @returns CutPointResult with index and split turn information
 */
export function findCutPointWithSplitInfo(
	messages: AppMessage[],
	startIndex: number,
	endIndex: number,
	keepRecentTokens: number,
): CutPointResult {
	const cutPoints = findValidCutPoints(messages, startIndex, endIndex);

	if (cutPoints.length === 0) {
		return {
			firstKeptIndex: startIndex,
			turnStartIndex: -1,
			isSplitTurn: false,
		};
	}

	// Estimate message sizes for token-based cutting
	let accumulatedTokens = 0;
	let cutIndex = startIndex;

	for (let i = endIndex - 1; i >= startIndex; i--) {
		const usage = getAssistantUsage(messages[i]!);
		if (usage) {
			accumulatedTokens = calculateContextTokens(usage);
			// Using cumulative tokens from the last assistant message
			if (accumulatedTokens >= keepRecentTokens) {
				// Find the closest valid cut point at or after this index
				for (const cp of cutPoints) {
					if (cp >= i) {
						cutIndex = cp;
						break;
					}
				}
				break;
			}
		}
	}

	// If no cut point found via tokens, use last assistant's token-based cut
	if (cutIndex === startIndex) {
		// Fall back to original algorithm
		cutIndex = findCutPoint(messages, startIndex, endIndex, keepRecentTokens);
	}

	// Determine if this is a split turn
	const isUserMessage = messages[cutIndex]?.role === "user";
	const turnStartIndex = isUserMessage
		? -1
		: findTurnStartIndex(messages, cutIndex, startIndex);

	return {
		firstKeptIndex: cutIndex,
		turnStartIndex,
		isSplitTurn: !isUserMessage && turnStartIndex !== -1,
	};
}

/**
 * Adjust a cut boundary to preserve tool call/result integrity.
 *
 * Tool results must stay paired with their originating assistant message.
 * If a toolResult would be kept but its toolCall would be cut, this
 * moves the boundary back to include the toolCall.
 *
 * @param messages - Array of messages
 * @param boundary - Initial cut point
 * @returns Adjusted boundary that preserves tool integrity
 */
export function adjustBoundaryForToolResults(
	messages: AppMessage[],
	boundary: number,
): number {
	let adjusted = boundary;
	const seenToolCalls = new Set<string>();
	const missingToolCalls = new Set<string>();

	// Process assistant message to collect tool calls
	const processAssistantMessage = (message: AppMessage) => {
		if (message.role !== "assistant") return;
		const content = (message as AssistantMessage).content;
		if (!content) return;
		for (const part of content) {
			if (part?.type === "toolCall") {
				seenToolCalls.add(part.id);
				if (missingToolCalls.has(part.id)) {
					missingToolCalls.delete(part.id);
				}
			}
		}
	};

	// Process tool result to check for missing tool calls
	const processToolResultMessage = (message: AppMessage) => {
		if (message.role !== "toolResult") return;
		const toolCallId = (message as { toolCallId: string }).toolCallId;
		if (!seenToolCalls.has(toolCallId)) {
			missingToolCalls.add(toolCallId);
		}
	};

	// First pass: process messages we're keeping
	for (const message of messages.slice(adjusted)) {
		processAssistantMessage(message);
		processToolResultMessage(message);
	}

	// Walk backwards to find missing tool calls
	while (missingToolCalls.size > 0 && adjusted > 0) {
		adjusted -= 1;
		const candidate = messages[adjusted]!;
		processAssistantMessage(candidate);
		processToolResultMessage(candidate);
	}

	return adjusted;
}
