import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { test } from "node:test";

import {
	isCompleteErrorDenyReport,
	lockfilePackageSet,
	newDependencyEdgeTargets,
	newPackages,
	parseDenyDiagnostics,
	newDependencyFindings,
	preexistingDependencyFindings,
	scopedDependencyFindings,
} from "./check-new-deps-supply-chain.mjs";

const SUPPLY_CHAIN_SCRIPT_URL = new URL(
	"./run-buildkite-supply-chain.sh",
	import.meta.url,
);
const SUPPLY_CHAIN_SCRIPT = existsSync(SUPPLY_CHAIN_SCRIPT_URL)
	? readFileSync(SUPPLY_CHAIN_SCRIPT_URL, "utf8")
	: null;
const SAMPLE_LOCKFILE = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "addr2line"
version = "0.25.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "deadbeef"
dependencies = [
 "gimli",
]

[[package]]
name = "lopdf"
version = "0.34.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "deadbeef"
`;

test("Buildkite supply-chain validation is strict and shared with the public projection", () => {
	assert.ok(SUPPLY_CHAIN_SCRIPT, "Buildkite supply-chain script must exist");
	assert.match(SUPPLY_CHAIN_SCRIPT, /cargo deny fetch db/);
	assert.match(SUPPLY_CHAIN_SCRIPT, /cargo deny check --disable-fetch/);
	assert.match(SUPPLY_CHAIN_SCRIPT, /check-new-deps-supply-chain\.test\.mjs/);
	assert.match(SUPPLY_CHAIN_SCRIPT, /BUILDKITE_PULL_REQUEST_BASE_BRANCH/);
	assert.match(SUPPLY_CHAIN_SCRIPT, /supply-chain-policy-approved/);
	assert.match(SUPPLY_CHAIN_SCRIPT, /pr\.head\?\.sha !== process\.env\.BUILDKITE_COMMIT/);
	assert.match(SUPPLY_CHAIN_SCRIPT, /event\.event === "committed"/);
	assert.match(SUPPLY_CHAIN_SCRIPT, /approvalIndex <= headCommitIndex/);
	assert.match(SUPPLY_CHAIN_SCRIPT, /gh api --paginate --slurp/);
	assert.match(SUPPLY_CHAIN_SCRIPT, /--base-lockfile \/tmp\/base-Cargo\.lock/);
	assert.match(SUPPLY_CHAIN_SCRIPT, /--fail-on-preexisting/);
});

test("lockfilePackageSet parses [[package]] stanzas into source-qualified identities", () => {
	const packages = lockfilePackageSet(SAMPLE_LOCKFILE);
	assert.equal(packages.size, 2);
	assert.ok(
		packages.has(
			"addr2line@0.25.1 (registry+https://github.com/rust-lang/crates.io-index)",
		),
	);
	assert.ok(
		packages.has(
			"lopdf@0.34.0 (registry+https://github.com/rust-lang/crates.io-index)",
		),
	);
});

test("a same-version source swap reads as a changed dependency", () => {
	const base = lockfilePackageSet(SAMPLE_LOCKFILE);
	const head = lockfilePackageSet(
		SAMPLE_LOCKFILE.replace(
			'name = "lopdf"\nversion = "0.34.0"\nsource = "registry+https://github.com/rust-lang/crates.io-index"',
			'name = "lopdf"\nversion = "0.34.0"\nsource = "git+https://example.com/lopdf?rev=abc123#abc123"',
		),
	);
	// Sanity: the fixture edit above only touched lopdf's stanza.
	const added = newPackages(base, head);
	assert.deepEqual([...added], ["lopdf@0.34.0 (git+https://example.com/lopdf?rev=abc123#abc123)"]);
	// ...and a cargo-deny finding against lopdf@0.34.0 blocks on it.
	const blocking = newDependencyFindings(
		[{ code: "unknown-git", message: "git source not allowed", crates: ["lopdf@0.34.0"] }],
		added,
	);
	assert.equal(blocking.length, 1);
});

test("newPackages finds only what changed between base and head", () => {
	const base = new Set(["a@1.0.0", "b@2.0.0"]);
	const head = new Set(["a@1.0.0", "b@2.1.0", "c@1.0.0"]);
	const added = newPackages(base, head);
	assert.deepEqual([...added].sort(), ["b@2.1.0", "c@1.0.0"]);
});

test("newPackages returns empty set when nothing changed", () => {
	const base = new Set(["a@1.0.0"]);
	const head = new Set(["a@1.0.0"]);
	assert.equal(newPackages(base, head).size, 0);
});

test("a new edge to an existing package is treated as a changed dependency", () => {
	const head = SAMPLE_LOCKFILE.replace(
		'dependencies = [\n "gimli",\n]',
		'dependencies = [\n "gimli",\n "lopdf",\n]',
	);
	const changed = newDependencyEdgeTargets(SAMPLE_LOCKFILE, head);
	assert.deepEqual(
		[...changed],
		["lopdf@0.34.0 (registry+https://github.com/rust-lang/crates.io-index)"],
	);
	assert.equal(
		newDependencyFindings(
			[{ code: "vulnerability", message: "m1", crates: ["lopdf@0.34.0"] }],
			changed,
		).length,
		1,
	);
});

test("a version-qualified edge selects the matching existing package version", () => {
	const base = `${SAMPLE_LOCKFILE}
[[package]]
name = "parent"
version = "1.0.0"

[[package]]
name = "rand"
version = "0.8.7"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "rand"
version = "0.9.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
`;
	const head = base.replace(
		'name = "parent"\nversion = "1.0.0"',
		'name = "parent"\nversion = "1.0.0"\ndependencies = [\n "rand 0.8.7",\n]',
	);

	assert.deepEqual(
		[...newDependencyEdgeTargets(base, head)],
		["rand@0.8.7 (registry+https://github.com/rust-lang/crates.io-index)"],
	);
});

test("parseDenyDiagnostics keeps only error-severity diagnostics", () => {
	const lines = [
		JSON.stringify({
			type: "diagnostic",
			fields: {
				code: "vulnerability",
				severity: "error",
				message: "Stack overflow in lopdf",
				graphs: [{ Krate: { name: "lopdf", version: "0.34.0" } }],
			},
		}),
		JSON.stringify({
			type: "diagnostic",
			fields: {
				code: "duplicate",
				severity: "warning",
				message: "found 2 duplicate entries for crate 'winnow'",
				graphs: [{ Krate: { name: "winnow", version: "0.7.15" } }],
			},
		}),
		"", // blank lines must be tolerated
		"not json at all", // stray non-JSON lines must be tolerated
	];
	const findings = parseDenyDiagnostics(lines.join("\n"));
	assert.equal(findings.length, 1);
	assert.equal(findings[0].code, "vulnerability");
	assert.deepEqual(findings[0].crates, ["lopdf@0.34.0"]);
});

test("structured report validation rejects malformed and incomplete output", () => {
	assert.equal(isCompleteErrorDenyReport("cargo-deny crashed"), false);
	assert.equal(
		isCompleteErrorDenyReport(
			JSON.stringify({
				type: "diagnostic",
				fields: { severity: "warning", message: "warning only" },
			}),
		),
		false,
	);
	assert.equal(
		isCompleteErrorDenyReport(
			JSON.stringify({
				type: "diagnostic",
				fields: { severity: "error", message: "operational failure" },
			}),
		),
		false,
	);
	const validError = JSON.stringify({
		type: "diagnostic",
		fields: {
			severity: "error",
			message: "denied dependency",
			graphs: [{ Krate: { name: "lopdf", version: "0.34.0" } }],
		},
	});
	assert.equal(
		isCompleteErrorDenyReport(validError),
		true,
	);
	assert.equal(isCompleteErrorDenyReport(`${validError}\n{"type":`), false);
});

test("newDependencyFindings only keeps findings whose crate is new", () => {
	const findings = [
		{ code: "vulnerability", message: "m1", crates: ["lopdf@0.34.0"] },
		{ code: "unmaintained", message: "m2", crates: ["paste@1.0.15"] },
	];
	const added = new Set(["lopdf@0.34.0"]);
	const blocking = newDependencyFindings(findings, added);
	assert.equal(blocking.length, 1);
	assert.equal(blocking[0].code, "vulnerability");
});

test("newDependencyFindings returns nothing when no finding touches a new dependency", () => {
	const findings = [
		{ code: "unmaintained", message: "m2", crates: ["paste@1.0.15"] },
	];
	const added = new Set(["some-other-crate@1.0.0"]);
	assert.equal(newDependencyFindings(findings, added).length, 0);
});

test("preexistingDependencyFindings keeps findings outside the changed dependency graph", () => {
	const findings = [
		{ code: "unknown-git", message: "new source", crates: ["example-git-crate@0.1.0"] },
		{ code: "vulnerability", message: "old issue", crates: ["lopdf@0.34.0"] },
	];
	const changed = new Set(["example-git-crate@0.1.0 (git+https://github.com/example/example-git-crate?rev=abc#abc)"]);
	const preexisting = preexistingDependencyFindings(findings, changed);
	assert.equal(preexisting.length, 1);
	assert.equal(preexisting[0].code, "vulnerability");
});

test("dependency activation inputs fail closed for feature-only changes", () => {
	const findings = [
		{ code: "unmaintained", message: "m1", crates: ["notify@8.2.0"] },
	];
	assert.equal(scopedDependencyFindings(findings, new Set(), false).length, 0);
	assert.equal(scopedDependencyFindings(findings, new Set(), true).length, 1);
});
