//! Shared model capability metadata for CLI and TUI surfaces.
//!
//! The catalog follows the "always-fresh snapshot" approach:
//!
//! 1. A bundled snapshot (`model_catalog_data.json`, embedded via
//!    `include_str!`) is regenerated from <https://models.dev/api.json> by
//!    `scripts/fetch-model-catalog.mjs` and committed, so offline builds and
//!    fresh installs always have current data with zero build-time network.
//! 2. At runtime a non-blocking background task refreshes a cached copy at
//!    `~/.composer/models-catalog.json` at most every [`REFRESH_TTL_SECS`].
//!    The cache overlays the bundled snapshot only when it is at least as
//!    fresh as the bundled `generated_at`; stale or malformed caches lose to
//!    the bundled snapshot, so fresh installs always win.
//! 3. Unknown model ids are not in the catalog at all and keep passing
//!    through to the provider registry unchanged.

use std::collections::{BTreeMap, HashMap};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::LazyLock;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};

use crate::ai::{ProviderProtocol, ProviderRegistry};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ModelProtocol {
    Anthropic,
    #[serde(rename = "openai-chat")]
    OpenAiChat,
    #[serde(rename = "openai-responses")]
    OpenAiResponses,
    Google,
    CodexAppServer,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VerificationState {
    Catalog,
    Verified,
    Unavailable,
    Unknown,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ModelVerification {
    pub state: VerificationState,
    pub source: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
}

impl ModelVerification {
    #[must_use]
    pub fn catalog() -> Self {
        Self {
            state: VerificationState::Catalog,
            source: "builtin-catalog".to_owned(),
            detail: None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ModelCapabilities {
    pub protocol: ModelProtocol,
    pub tools: bool,
    pub vision: bool,
    pub reasoning: bool,
    pub streaming: bool,
    pub context_tokens: u32,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ModelInfo {
    pub id: String,
    pub name: String,
    pub provider: String,
    pub description: String,
    pub capabilities: ModelCapabilities,
    pub verification: ModelVerification,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ResolvedModelInspection {
    pub provider: String,
    pub protocol: String,
    pub base_url: Option<String>,
    pub auth_configured: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub capabilities: Option<ModelCapabilities>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelInspection {
    pub id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub catalog: Option<ModelInfo>,
    pub resolved: ResolvedModelInspection,
    pub sources: BTreeMap<String, String>,
}

/// Upstream community catalog (MIT-licensed) that feeds both the bundled
/// snapshot and the runtime refresh.
const MODELS_DEV_API_URL: &str = "https://models.dev/api.json";
/// How long a cached refresh check stays valid before another background
/// refresh is spawned.
const REFRESH_TTL_SECS: u64 = 4 * 60 * 60;
/// Hard timeout for the background refresh request; must never stall startup.
const REFRESH_TIMEOUT_SECS: u64 = 15;
/// Providers mirrored into the catalog, in the order they are merged.
pub(crate) const CATALOG_PROVIDERS: &[&str] = &["anthropic", "google", "openai", "xai"];

const BUNDLED_CATALOG_JSON: &str = include_str!("model_catalog_data.json");

/// Committed snapshot regenerated by `scripts/fetch-model-catalog.mjs`.
#[derive(Debug, Clone, Deserialize)]
struct BundledCatalog {
    generated_at: u64,
    models: Vec<ModelInfo>,
}

/// Runtime overlay persisted at `~/.composer/models-catalog.json`.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
struct CachedCatalog {
    /// Last refresh attempt (success or failure), unix epoch seconds.
    #[serde(default)]
    checked_at: u64,
    /// Last successful fetch, unix epoch seconds. Compared against the bundled
    /// snapshot's `generated_at` for the staleness guard.
    #[serde(default)]
    fetched_at: u64,
    /// Raw HTTP `Last-Modified` header from the fetch, kept for debugging.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    last_modified: Option<String>,
    #[serde(default)]
    models: Vec<ModelInfo>,
}

static BUNDLED_CATALOG: LazyLock<BundledCatalog> = LazyLock::new(|| {
    serde_json::from_str(BUNDLED_CATALOG_JSON).expect("bundled model catalog JSON must parse")
});

fn now_epoch_secs() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_or(0, |elapsed| elapsed.as_secs())
}

/// Hand-maintained default model per catalog provider. Ids must exist in the
/// bundled snapshot; regeneration keeps dead ids out of the catalog itself.
#[must_use]
pub fn default_model_for_provider(provider: &str) -> Option<&'static str> {
    match provider.trim().to_ascii_lowercase().as_str() {
        "anthropic" | "claude" => Some("claude-sonnet-4-6"),
        "openai" => Some("gpt-5.5"),
        "google" | "gemini" => Some("gemini-2.5-pro"),
        "xai" | "grok" => Some("grok-4.5"),
        _ => None,
    }
}

/// Model catalog used by `maestro models` and the model selector: the runtime
/// cache overlaid on the bundled snapshot when the cache wins the staleness
/// guard, else the bundled snapshot. Never fails and never blocks on network.
#[must_use]
pub fn available_models() -> Vec<ModelInfo> {
    maybe_spawn_background_refresh();
    let cache = catalog_cache_path().and_then(|path| load_cache(&path));
    select_models(&BUNDLED_CATALOG, cache.as_ref()).to_vec()
}

/// Inspect the exact native model/provider resolution while retaining per-field
/// provenance and never returning credential material.
pub fn inspect_model(id: &str) -> anyhow::Result<ModelInspection> {
    inspect_model_with_env(id, &std::env::vars().collect())
}

fn inspect_model_with_env(
    id: &str,
    env: &HashMap<String, String>,
) -> anyhow::Result<ModelInspection> {
    let catalog = find_model(id);
    let resolved = ProviderRegistry::resolve(id, env)?;
    let mut sources = BTreeMap::new();
    let cache_wins = catalog_cache_path()
        .and_then(|path| load_cache(&path))
        .is_some_and(|cache| {
            !cache.models.is_empty() && cache.fetched_at >= BUNDLED_CATALOG.generated_at
        });
    sources.insert(
        "catalog".to_string(),
        if catalog.is_none() {
            "uncataloged"
        } else if cache_wins {
            "runtime-cache"
        } else {
            "bundled"
        }
        .to_string(),
    );
    sources.insert(
        "provider".to_string(),
        if id.contains('/') {
            "model-id-prefix"
        } else {
            "model-family-inference"
        }
        .to_string(),
    );
    sources.insert(
        "auth".to_string(),
        resolved
            .auth_source
            .as_ref()
            .map_or_else(|| "none".to_string(), |name| format!("environment:{name}")),
    );
    let base_url_source = resolved
        .provider
        .base_url_env
        .iter()
        .find(|name| {
            env.get(**name)
                .is_some_and(|value| !value.trim().is_empty())
        })
        .map_or_else(
            || {
                if resolved.provider.default_base_url.is_some() {
                    "builtin".to_string()
                } else {
                    "none".to_string()
                }
            },
            |name| format!("environment:{name}"),
        );
    sources.insert("baseUrl".to_string(), base_url_source);
    sources.insert(
        "capabilities".to_string(),
        if catalog.is_some() {
            "catalog"
        } else {
            "unavailable"
        }
        .to_string(),
    );

    Ok(ModelInspection {
        id: id.to_string(),
        resolved: ResolvedModelInspection {
            provider: resolved.provider.id.to_string(),
            protocol: protocol_name(resolved.provider.protocol).to_string(),
            base_url: resolved.base_url.as_deref().map(redact_endpoint),
            auth_configured: resolved.credential.is_some(),
            capabilities: catalog.as_ref().map(|catalog| catalog.capabilities.clone()),
        },
        catalog,
        sources,
    })
}

fn redact_endpoint(value: &str) -> String {
    let Ok(mut url) = url::Url::parse(value) else {
        return "[configured endpoint]".to_string();
    };
    let _ = url.set_username("");
    let _ = url.set_password(None);
    url.set_path("/");
    url.set_query(None);
    url.set_fragment(None);
    url.to_string()
}

/// Bundled snapshot only; used where the runtime overlay must not leak in.
#[must_use]
pub fn bundled_models() -> &'static [ModelInfo] {
    &BUNDLED_CATALOG.models
}

/// Cache wins only when it carries models and is at least as fresh as the
/// bundled snapshot; anything else falls back to the bundled snapshot.
fn select_models<'a>(
    bundled: &'a BundledCatalog,
    cache: Option<&'a CachedCatalog>,
) -> &'a [ModelInfo] {
    match cache {
        Some(cache) if !cache.models.is_empty() && cache.fetched_at >= bundled.generated_at => {
            &cache.models
        }
        _ => &bundled.models,
    }
}

fn catalog_cache_path() -> Option<PathBuf> {
    crate::path_utils::legacy_composer_home_dir().map(|dir| dir.join("models-catalog.json"))
}

fn load_cache(path: &Path) -> Option<CachedCatalog> {
    let contents = std::fs::read_to_string(path).ok()?;
    serde_json::from_str(&contents).ok()
}

/// Spawn a one-shot background refresh when the cache is missing or its last
/// check is older than the TTL. No-ops without a tokio runtime and never runs
/// more than once per process; startup paths never block or fail on it.
fn maybe_spawn_background_refresh() {
    static REFRESH_STARTED: AtomicBool = AtomicBool::new(false);

    let stale = catalog_cache_path().is_none_or(|path| {
        load_cache(&path).is_none_or(|cache| {
            now_epoch_secs().saturating_sub(cache.checked_at) > REFRESH_TTL_SECS
        })
    });
    if !stale {
        return;
    }
    let Ok(handle) = tokio::runtime::Handle::try_current() else {
        return;
    };
    if REFRESH_STARTED.swap(true, Ordering::SeqCst) {
        return;
    }
    handle.spawn(async {
        let _ = refresh_catalog_cache().await;
    });
}

/// Fetch models.dev, apply the same mapping as the fetcher script, and
/// atomically replace the cache. On failure only `checked_at` is bumped so
/// the old data stays in use without hammering the upstream on every start.
async fn refresh_catalog_cache() -> anyhow::Result<()> {
    let Some(path) = catalog_cache_path() else {
        return Ok(());
    };
    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(REFRESH_TIMEOUT_SECS))
        .user_agent(concat!("maestro-tui/", env!("CARGO_PKG_VERSION")))
        .build()?;
    let result = fetch_remote_catalog(&client).await;
    let checked_at = now_epoch_secs();
    match result {
        Ok((models, last_modified)) => {
            let cache = CachedCatalog {
                checked_at,
                fetched_at: checked_at,
                last_modified,
                models,
            };
            write_cache_atomic(&path, &cache).await?;
        }
        Err(error) => {
            let mut cache = load_cache(&path).unwrap_or_default();
            cache.checked_at = checked_at;
            let _ = write_cache_atomic(&path, &cache).await;
            return Err(error);
        }
    }
    Ok(())
}

async fn fetch_remote_catalog(
    client: &reqwest::Client,
) -> anyhow::Result<(Vec<ModelInfo>, Option<String>)> {
    let response = client.get(MODELS_DEV_API_URL).send().await?;
    let response = response.error_for_status()?;
    let last_modified = response
        .headers()
        .get(reqwest::header::LAST_MODIFIED)
        .and_then(|value| value.to_str().ok())
        .map(str::to_owned);
    let payload: serde_json::Value = response.json().await?;
    let models = map_models_dev_catalog(&payload)?;
    if models.is_empty() {
        anyhow::bail!("models.dev payload produced an empty catalog");
    }
    Ok((models, last_modified))
}

/// Write the cache via a sibling temp file + rename so readers never observe
/// a partially written catalog.
async fn write_cache_atomic(path: &Path, cache: &CachedCatalog) -> anyhow::Result<()> {
    let path = path.to_path_buf();
    let contents = serde_json::to_vec_pretty(cache)?;
    tokio::task::spawn_blocking(move || crate::path_utils::atomic_private_write(&path, &contents))
        .await??;
    Ok(())
}

/// Map a models.dev `api.json` payload into catalog entries, applying the
/// same rules as `scripts/fetch-model-catalog.mjs`: keep tool-capable,
/// non-deprecated models with a positive context limit for the providers
/// Maestro routes natively.
fn map_models_dev_catalog(payload: &serde_json::Value) -> anyhow::Result<Vec<ModelInfo>> {
    let mut models = Vec::new();
    for provider in CATALOG_PROVIDERS {
        let provider_models = payload
            .get(*provider)
            .and_then(|provider| provider.get("models"))
            .and_then(serde_json::Value::as_object)
            .ok_or_else(|| anyhow::anyhow!("models.dev payload is missing provider {provider}"))?;
        for (id, model) in provider_models {
            if model.get("tool_call").and_then(serde_json::Value::as_bool) != Some(true) {
                continue;
            }
            if model.get("status").and_then(serde_json::Value::as_str) == Some("deprecated") {
                continue;
            }
            let context_tokens = model
                .get("limit")
                .and_then(|limit| limit.get("context"))
                .and_then(serde_json::Value::as_u64)
                .and_then(|context| u32::try_from(context).ok())
                .unwrap_or(0);
            if context_tokens == 0 {
                continue;
            }
            models.push(map_models_dev_model(provider, id, model, context_tokens));
        }
    }
    models.sort_by(|left, right| {
        left.provider
            .cmp(&right.provider)
            .then_with(|| left.id.cmp(&right.id))
    });
    Ok(models)
}

fn map_models_dev_model(
    provider: &str,
    id: &str,
    model: &serde_json::Value,
    context_tokens: u32,
) -> ModelInfo {
    let name = model
        .get("name")
        .and_then(serde_json::Value::as_str)
        .filter(|name| !name.is_empty())
        .unwrap_or(id)
        .to_owned();
    let description = model
        .get("description")
        .and_then(serde_json::Value::as_str)
        .filter(|description| !description.is_empty())
        .unwrap_or(&name)
        .to_owned();
    let vision = model
        .get("modalities")
        .and_then(|modalities| modalities.get("input"))
        .and_then(serde_json::Value::as_array)
        .is_some_and(|inputs| inputs.iter().any(|input| input.as_str() == Some("image")));
    ModelInfo {
        id: id.to_owned(),
        name,
        provider: provider.to_owned(),
        description,
        capabilities: ModelCapabilities {
            protocol: catalog_protocol(provider, id),
            tools: true,
            vision,
            reasoning: model.get("reasoning").and_then(serde_json::Value::as_bool) == Some(true),
            streaming: true,
            context_tokens,
        },
        verification: ModelVerification {
            state: VerificationState::Catalog,
            source: "models.dev".to_owned(),
            detail: None,
        },
    }
}

fn catalog_protocol(provider: &str, model_id: &str) -> ModelProtocol {
    match provider {
        "anthropic" => ModelProtocol::Anthropic,
        "google" => ModelProtocol::Google,
        // Mirror of `uses_responses_api` in `ai::openai`: Codex and gpt-5.x/o3
        // models use the Responses API, everything else chat completions.
        "openai" if uses_responses_api(model_id) => ModelProtocol::OpenAiResponses,
        _ => ModelProtocol::OpenAiChat,
    }
}

fn uses_responses_api(model_id: &str) -> bool {
    model_id.contains("codex") || model_id.starts_with("gpt-5") || model_id.starts_with("o3")
}

#[must_use]
pub fn find_model(id: &str) -> Option<ModelInfo> {
    let (provider, bare_id) = id
        .split_once('/')
        .map_or((None, id), |(provider, model)| (Some(provider), model));
    let model = available_models()
        .into_iter()
        .find(|model| model.id == bare_id)?;
    if provider.is_some_and(|provider| {
        ProviderRegistry::descriptor(provider)
            .is_none_or(|descriptor| descriptor.id != model.provider)
    }) {
        return None;
    }
    Some(model)
}

#[must_use]
pub fn has_provider_mismatch(id: &str) -> bool {
    let Some((provider, bare_id)) = id.split_once('/') else {
        return false;
    };
    let Some(model) = available_models()
        .into_iter()
        .find(|model| model.id == bare_id)
    else {
        return false;
    };
    ProviderRegistry::descriptor(provider).is_none_or(|descriptor| descriptor.id != model.provider)
}

/// Verify registry routing and credential presence without network access.
#[must_use]
pub fn verify_model_offline(model_id: &str) -> ModelVerification {
    let env = std::env::vars().collect();
    match ProviderRegistry::resolve(model_id, &env) {
        Ok(provider) if provider.credential.is_some() => ModelVerification {
            state: VerificationState::Verified,
            source: "environment".to_owned(),
            detail: provider.auth_source,
        },
        Ok(provider) => ModelVerification {
            state: VerificationState::Unavailable,
            source: "environment".to_owned(),
            detail: Some(format!(
                "{} credentials not found ({})",
                provider.provider.id,
                provider.provider.auth_env.join(", ")
            )),
        },
        Err(error) => ModelVerification {
            state: VerificationState::Unknown,
            source: "provider-registry".to_owned(),
            detail: Some(error.to_string()),
        },
    }
}

#[must_use]
pub fn protocol_name(protocol: ProviderProtocol) -> &'static str {
    match protocol {
        ProviderProtocol::Anthropic => "anthropic",
        ProviderProtocol::OpenAi => "openai",
        ProviderProtocol::OpenAiCompatible => "openai-compatible",
        ProviderProtocol::Google => "google",
        ProviderProtocol::Codex => "codex-app-server",
        ProviderProtocol::AzureOpenAi => "azure-openai",
        ProviderProtocol::Bedrock => "bedrock",
        ProviderProtocol::Managed => "managed",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn catalog_model(id: &str) -> ModelInfo {
        bundled_models()
            .iter()
            .find(|model| model.id == id)
            .unwrap_or_else(|| panic!("{id} must be in the bundled catalog"))
            .clone()
    }

    fn cache_with(fetched_at: u64, models: Vec<ModelInfo>) -> CachedCatalog {
        CachedCatalog {
            checked_at: fetched_at,
            fetched_at,
            last_modified: None,
            models,
        }
    }

    #[test]
    fn bundled_snapshot_parses_and_is_healthy() {
        assert!(BUNDLED_CATALOG.generated_at > 0);
        assert!(bundled_models().len() >= 50);
        for model in bundled_models() {
            assert!(
                model.capabilities.tools,
                "{} must be tool-capable",
                model.id
            );
            assert!(
                model.capabilities.context_tokens > 0,
                "{} must declare a context window",
                model.id
            );
            assert!(
                CATALOG_PROVIDERS.contains(&model.provider.as_str()),
                "{} has unexpected provider {}",
                model.id,
                model.provider
            );
            assert!(
                !model.id.contains('/'),
                "catalog id {} must not contain a provider qualifier",
                model.id
            );
        }
    }

    #[test]
    fn bundled_snapshot_drops_deprecated_ids() {
        for dead in [
            "gpt-5.1-codex-max",
            "gemini-2.0-flash",
            "claude-sonnet-4-5-20250514",
        ] {
            assert!(
                find_model(dead).is_none(),
                "deprecated id {dead} must not survive regeneration"
            );
        }
    }

    #[test]
    fn default_models_exist_in_catalog() {
        for provider in ["anthropic", "openai", "google", "xai"] {
            let default = default_model_for_provider(provider).expect("default model");
            let model = catalog_model(default);
            assert_eq!(model.provider, provider);
        }
        assert_eq!(default_model_for_provider("nope"), None);
    }

    #[test]
    fn model_inspection_reports_provenance_without_secret_values() {
        let mut env = std::collections::HashMap::new();
        env.insert(
            "OPENAI_API_KEY".to_string(),
            "super-secret-value".to_string(),
        );
        env.insert(
            "OPENAI_BASE_URL".to_string(),
            "https://user:password@gateway.example.test/v1/path-secret?token=secret".to_string(),
        );
        let inspection = inspect_model_with_env("openai/gpt-5.5", &env).unwrap();
        let json = serde_json::to_string(&inspection).unwrap();
        assert!(!json.contains("super-secret-value"));
        assert!(!json.contains("password"));
        assert!(!json.contains("path-secret"));
        assert!(!json.contains("token=secret"));
        assert_eq!(
            inspection.resolved.base_url.as_deref(),
            Some("https://gateway.example.test/")
        );
        assert_eq!(inspection.sources["auth"], "environment:OPENAI_API_KEY");
        assert_eq!(inspection.sources["baseUrl"], "environment:OPENAI_BASE_URL");
        assert_eq!(inspection.resolved.provider, "openai");
    }

    #[test]
    fn model_inspection_resolves_uncataloged_models() {
        let inspection =
            inspect_model_with_env("openai/future-custom-model", &HashMap::new()).unwrap();

        assert!(inspection.catalog.is_none());
        assert!(inspection.resolved.capabilities.is_none());
        assert_eq!(inspection.resolved.provider, "openai");
        assert_eq!(inspection.sources["catalog"], "uncataloged");
        assert_eq!(inspection.sources["capabilities"], "unavailable");
    }

    #[test]
    fn mapping_filters_deprecated_and_tool_less_models() {
        let payload = serde_json::json!({
            "anthropic": {"models": {
                "claude-good": {"name": "Good", "tool_call": true, "reasoning": true,
                    "limit": {"context": 200_000}, "modalities": {"input": ["text", "image"]}},
                "claude-old": {"name": "Old", "tool_call": true, "status": "deprecated",
                    "limit": {"context": 200_000}},
                "claude-no-tools": {"name": "NoTools", "tool_call": false,
                    "limit": {"context": 200_000}},
                "claude-no-context": {"name": "NoCtx", "tool_call": true,
                    "limit": {"context": 0}}
            }},
            "openai": {"models": {}},
            "google": {"models": {}},
            "xai": {"models": {}}
        });
        let models = map_models_dev_catalog(&payload).expect("mapping");
        assert_eq!(models.len(), 1);
        assert_eq!(models[0].id, "claude-good");
        assert!(models[0].capabilities.vision);
        assert!(models[0].capabilities.reasoning);
        assert_eq!(models[0].capabilities.protocol, ModelProtocol::Anthropic);
    }

    #[test]
    fn mapping_assigns_protocols() {
        let payload = serde_json::json!({
            "anthropic": {"models": {}},
            "google": {"models": {
                "gemini-9-pro": {"tool_call": true, "limit": {"context": 1_000_000}}
            }},
            "openai": {"models": {
                "gpt-5.5": {"tool_call": true, "limit": {"context": 400_000}},
                "gpt-5.3-codex": {"tool_call": true, "limit": {"context": 400_000}},
                "o3": {"tool_call": true, "limit": {"context": 200_000}},
                "gpt-4o": {"tool_call": true, "limit": {"context": 128_000}}
            }},
            "xai": {"models": {
                "grok-9": {"tool_call": true, "limit": {"context": 131_072}}
            }}
        });
        let models = map_models_dev_catalog(&payload).expect("mapping");
        let protocol_of = |id: &str| {
            models
                .iter()
                .find(|model| model.id == id)
                .map(|model| model.capabilities.protocol)
                .unwrap_or_else(|| panic!("{id} mapped"))
        };
        assert_eq!(protocol_of("gpt-5.5"), ModelProtocol::OpenAiResponses);
        assert_eq!(protocol_of("gpt-5.3-codex"), ModelProtocol::OpenAiResponses);
        assert_eq!(protocol_of("o3"), ModelProtocol::OpenAiResponses);
        assert_eq!(protocol_of("gpt-4o"), ModelProtocol::OpenAiChat);
        assert_eq!(protocol_of("grok-9"), ModelProtocol::OpenAiChat);
        assert_eq!(protocol_of("gemini-9-pro"), ModelProtocol::Google);
    }

    #[test]
    fn overlay_precedence_follows_staleness_guard() {
        let bundled = BundledCatalog {
            generated_at: 1_000,
            models: vec![catalog_model("gpt-5.5")],
        };
        let newer = cache_with(1_000, vec![catalog_model("gpt-4o")]);
        assert_eq!(select_models(&bundled, Some(&newer))[0].id, "gpt-4o");

        let older = cache_with(999, vec![catalog_model("gpt-4o")]);
        assert_eq!(select_models(&bundled, Some(&older))[0].id, "gpt-5.5");

        let empty = cache_with(5_000, Vec::new());
        assert_eq!(select_models(&bundled, Some(&empty))[0].id, "gpt-5.5");

        assert_eq!(select_models(&bundled, None)[0].id, "gpt-5.5");
    }

    #[test]
    fn malformed_cache_falls_back_to_bundled() {
        let temp = tempfile::tempdir().expect("tempdir");
        let path = temp.path().join("models-catalog.json");
        std::fs::write(&path, "{ not json").expect("write malformed cache");
        assert!(load_cache(&path).is_none());

        std::fs::write(&path, "{\"checked_at\": 1}").expect("write partial cache");
        let cache = load_cache(&path).expect("partial cache still parses with defaults");
        assert!(cache.models.is_empty());
    }

    #[test]
    fn atomic_cache_write_replaces_existing_cache() {
        let temp = tempfile::tempdir().expect("tempdir");
        let path = temp.path().join("nested").join("models-catalog.json");
        let runtime = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .expect("runtime");
        runtime
            .block_on(write_cache_atomic(
                &path,
                &cache_with(21, vec![catalog_model("gpt-4o")]),
            ))
            .expect("initial write");
        runtime
            .block_on(write_cache_atomic(
                &path,
                &cache_with(42, vec![catalog_model("gpt-5.5")]),
            ))
            .expect("replacement write");

        let loaded = load_cache(&path).expect("cache loads");
        assert_eq!(loaded.fetched_at, 42);
        assert_eq!(loaded.models[0].id, "gpt-5.5");
        assert_eq!(
            std::fs::read_dir(path.parent().expect("cache parent"))
                .expect("read cache parent")
                .count(),
            1,
            "temporary file must be renamed away"
        );
    }

    #[test]
    fn catalog_exposes_capabilities_separately_from_verification() {
        let model = find_model("openai/gpt-5.5").expect("catalog model");
        assert!(model.capabilities.tools);
        assert!(model.capabilities.reasoning);
        assert_eq!(model.capabilities.protocol, ModelProtocol::OpenAiResponses);
        assert_eq!(model.verification.state, VerificationState::Catalog);
        assert_eq!(model.capabilities.context_tokens, 1_050_000);
    }

    #[test]
    fn catalog_rejects_provider_model_mismatches() {
        assert!(find_model("anthropic/gpt-4o").is_none());
        assert!(has_provider_mismatch("anthropic/gpt-4o"));
        assert!(find_model("anthropic/claude-sonnet-4-6").is_some());
        assert!(!has_provider_mismatch("anthropic/claude-sonnet-4-6"));
        assert!(find_model("claude/claude-sonnet-4-6").is_some());
        assert!(!has_provider_mismatch("openai/custom-model"));
    }

    #[test]
    fn unknown_ids_pass_through_to_provider_registry() {
        // Not in the catalog, but routing must keep working unchanged.
        assert!(find_model("openai/gpt-99-turbo").is_none());
        assert!(!has_provider_mismatch("openai/gpt-99-turbo"));
        let env = std::collections::HashMap::new();
        let resolved = ProviderRegistry::resolve("openai/gpt-99-turbo", &env)
            .expect("unknown ids still resolve to their provider");
        assert_eq!(resolved.provider.id, "openai");
        let bare = ProviderRegistry::resolve("gpt-99-turbo", &env)
            .expect("bare unknown ids fall back to the default provider");
        assert_eq!(bare.provider.id, "openai");
    }
}
