#![allow(dead_code)]

// Auto-generated by `scripts/headless-protocol-codegen.mjs`.
// Do not edit manually; update `headless-protocol.manifest.json` instead.

pub const HEADLESS_PROTOCOL_VERSION: &str = "2026-04-02";
pub const HEADLESS_SERVER_REQUEST_TYPES: &[&str] = &["approval", "client_tool", "user_input"];
pub const HEADLESS_SERVER_REQUEST_RESOLUTIONS: &[&str] = &[
    "approved",
    "denied",
    "completed",
    "failed",
    "answered",
    "cancelled",
];
pub const HEADLESS_SERVER_REQUEST_RESOLVED_BY: &[&str] = &["user", "policy", "client", "runtime"];
pub const HEADLESS_CONNECTION_ROLES: &[&str] = &["viewer", "controller"];
pub const HEADLESS_NOTIFICATION_TYPES: &[&str] =
    &["status", "heartbeat", "connection_info", "compaction"];
pub const HEADLESS_THINKING_LEVELS: &[&str] = &["off", "minimal", "low", "medium", "high", "ultra"];
pub const HEADLESS_APPROVAL_MODES: &[&str] = &["auto", "prompt", "fail"];
pub const HEADLESS_ERROR_TYPES: &[&str] = &["transient", "fatal", "tool", "cancelled", "protocol"];
pub const HEADLESS_UTILITY_OPERATIONS: &[&str] = &["command_exec", "file_search", "file_watch"];
pub const HEADLESS_UTILITY_COMMAND_STREAMS: &[&str] = &["stdout", "stderr"];
pub const HEADLESS_UTILITY_COMMAND_SHELL_MODES: &[&str] = &["shell", "direct"];
pub const HEADLESS_UTILITY_COMMAND_TERMINAL_MODES: &[&str] = &["pipe", "pty"];
pub const HEADLESS_UTILITY_FILE_WATCH_CHANGE_TYPES: &[&str] =
    &["create", "modify", "delete", "rename"];
pub const HEADLESS_TO_AGENT_MESSAGE_TYPES: &[&str] = &[
    "hello",
    "init",
    "prompt",
    "interrupt",
    "tool_response",
    "client_tool_result",
    "server_request_response",
    "utility_command_start",
    "utility_command_terminate",
    "utility_command_stdin",
    "utility_command_resize",
    "utility_file_search",
    "utility_file_watch_start",
    "utility_file_watch_stop",
    "cancel",
    "shutdown",
];
pub const HEADLESS_FROM_AGENT_MESSAGE_TYPES: &[&str] = &[
    "ready",
    "response_start",
    "response_chunk",
    "response_end",
    "tool_call",
    "tool_start",
    "tool_output",
    "tool_end",
    "client_tool_request",
    "server_request",
    "server_request_resolved",
    "utility_command_started",
    "utility_command_resized",
    "utility_command_output",
    "utility_command_exited",
    "utility_file_search_results",
    "utility_file_watch_started",
    "utility_file_watch_event",
    "utility_file_watch_stopped",
    "error",
    "status",
    "compaction",
    "session_info",
    "connection_info",
];
