#![allow(dead_code)]

// Auto-generated by `scripts/headless-protocol-codegen.mjs`.
// Do not edit manually; update `headless-protocol.manifest.json` instead.

pub const HEADLESS_PROTOCOL_VERSION: &str = "2026-04-02";
pub const HEADLESS_SERVER_REQUEST_TYPES: &[&str] = &["approval", "client_tool", "user_input"];
pub const HEADLESS_SERVER_REQUEST_RESOLUTIONS: &[&str] = &[
    "approved",
    "denied",
    "completed",
    "failed",
    "answered",
    "cancelled",
];
pub const HEADLESS_SERVER_REQUEST_RESOLVED_BY: &[&str] = &["user", "policy", "client", "runtime"];
pub const HEADLESS_CONNECTION_ROLES: &[&str] = &["viewer", "controller"];
pub const HEADLESS_THINKING_LEVELS: &[&str] = &["off", "minimal", "low", "medium", "high", "ultra"];
pub const HEADLESS_APPROVAL_MODES: &[&str] = &["auto", "prompt", "fail"];
pub const HEADLESS_ERROR_TYPES: &[&str] = &["transient", "fatal", "tool", "cancelled", "protocol"];
pub const HEADLESS_UTILITY_OPERATIONS: &[&str] = &["command_exec"];
pub const HEADLESS_UTILITY_COMMAND_STREAMS: &[&str] = &["stdout", "stderr"];
pub const HEADLESS_UTILITY_COMMAND_SHELL_MODES: &[&str] = &["shell", "direct"];
